### ISSUE TITLE
[Bug] Apps backed up in main profile get restored to work profile too

### ISSUE THREAD

**Issue by heinhuiz** [NeoApplications/Neo-Backup#203]
I'm working with two profiles, main and work, set up with Shelter.
An app that only exists in the main profile also gets installed in the work profile when restored. That only happens if the app has been uninstalled before the restore.
Only the app seems to be installed then and luckily not the data, but still it should not happen. 

 - Device: Mi 9T
 - Android Version: 10
 - ROM: Lineageos 17.1 + microg
 - App's Version: 4.0.0

**Comment by 07416** [comment]
@heinhuiz Does whether the work profile is closed or not while restoring have any effect?

**Comment by heinhuiz** [comment]
Sorry @07416, can't answer that because I have moved to Seedvault.

**Comment by aviladev** [comment]
Also happens to me.

@07416 

> Does whether the work profile is closed or not while restoring have any effect?

Even when closed (WP), the app is installed to the work profile.

Also, when uninstalled through oAndBackupX, the work profile app is also uninstalled, which I think is another issue.
