### ISSUE TITLE
[Bug] java.io.IOException: Unable to create folder

### ISSUE THREAD

**Issue by ondro1030a** [NeoApplications/Neo-Backup#211]
**Description**
On AOSP 8.1 data doesn not restoring from encrypted backup.

**Steps To Reproduce**
1. Open OandBackupX
2. Backup Gmail with enabled encryption
3. Restore Gmail app + data or restore Gmail app (without error), then restore data with error.
4. error  java.io.IOException
`RestoreFailedException: Could not read the input file or write an output file due to IOException: java.io.IOException: Unable to create folder /data/user/0/com.machiav3lli.backup/cache/restore_3049370736955113394/cache/WebView/SafeBrowsingRestoreFailedException: Could not read the input file or write an output file due to IOException: java.io.IOException: Unable to create folder /data/user/0/com.machiav3lli.backup/cache/restore_3347681246555328431/cache/WebView/SafeBrowsing
RestoreFailedException: Could not read the input file or write an output file due to IOException: java.io.IOException: Unable to create folder /data/user/0/com.machiav3lli.backup/cache/restore_7883586034088685443/cache/WebView/SafeBrowsing`

**System Information(please complete the following information):**
 - Device: Xiaomi Remi 5a
 - Android Version: 8.1
 - ROM: AOSP
 - App's Version: 4.0.0

-------------------------------
**Additional Notes**
How-to decrypt data.tar.gz.enc offline on linux ?

**Comment by machiav3lli** [comment]
So, just to get it right. If you try to restore the both(apk&data) or only apk it works just fine, but if you try to restore only data then it gets such an error?
The Data seems to have another structure from what I'd excpect from Gmail. Does this happens to other apps or only to couple of them? if yes, could you list them here. Thanks.

**Comment by machiav3lli** [comment]
And for your question on how to decrypt on linux here you can find the encryption preferences:
https://github.com/machiav3lli/oandbackupx/blob/master/app/src/main/java/com/machiav3lli/backup/handler/Crypto.kt

**Comment by ondro1030a** [comment]
I am trying restore only apk without data, and it works fine. Then i am restore apk+data and only data from Skype, FairMail, Telegram always reseive this error.

**Comment by machiav3lli** [comment]
Could you please check the just-released 5.0.0 and report back, thanks.

**Comment by hg42** [comment]
should not happen any more
