### ISSUE TITLE
[Bug] Could not copy apk to staging directory

### ISSUE THREAD

**Issue by Generator** [NeoApplications/Neo-Backup#223]
**Description**
When trying to restore any backup it ends with `Could not copy apk to staging directory`

**Steps To Reproduce**
1. Backup any app
2. Restore APK (or APK and data)

**System Information(please complete the following information):**
 - Device: X96 Max+ (Android TV Box)
 - Android Version: 9
 - ROM: SLIMBOX (AOSP)
 - App's Version: OAndBackupX 4.0.0

-------------------------------
**Additional Notes**
Logcat: [logcat.txt](https://github.com/machiav3lli/oandbackupx/files/5541492/logcat.txt)

**Comment by machiav3lli** [comment]
What's your root solution? 
Maybe there's something special about android tv system structure. I never used one.

**Comment by Generator** [comment]
SuperSU (comes pre-installed with the ROM). 

Titanium Backup can restore without issues.

**Comment by machiav3lli** [comment]
Can you please check the just-released 5.0.0 and report back, thanks.

**Comment by hg42** [comment]
all kinds of su solutions should work now or in next release (well, some configuration is necessary), look for "suCommand", the "Preferences" button on the "root missing" screen jumps to it.
