### ISSUE TITLE
[Bug] could not list contents of user data

### ISSUE THREAD

**Issue by nutpantz** [NeoApplications/Neo-Backup#278]
Latest update from fdroid
Backup all user apps
Android 8 Samsung s7 edge oem rom masjesk latest.

After the update over 30% of my apps failed to update with this error.

**Comment by Taknok** [comment]
Same on oneplus 7 stock ROM + root.
Exemple:
- App Quick edit
- Manual backup apk, data and protected data return
```
a: Could not list contents of /data/user/0/com.rhmsoft.edit
```

But the folder is there:
![Screenshot_20211101-221623](https://user-images.githubusercontent.com/12498020/139743245-3f88885e-78e5-4278-a5c4-528b8132aaf8.jpg)

**Comment by smemsh** [comment]
Same on Pixel 6 Pro:
```
Errors occurred
Airbnb: a: Could not list contents of
/data/user/0/com.airbnb.android
```
tons of apps have the issue

**Comment by Taknok** [comment]
Killing the app from app manager solves the issue sometimes (crappy work around).

**Comment by MartinX3** [comment]
Same issue here with LineageOS 18.1 (Android 11)
But I use the option `Closing app process before backup`

**Comment by dptsolutions** [comment]
This keeps happening to me. A reboot seemed to somewhat work. But eventually it seems the app crashed again and restarting it caused this issue to occur.

**Comment by mimmiechan** [comment]
Same trying to backup Gboard on Project Sakura Rom (based on LineageOS), Gboard flashed with OpenGApps.

`a: Could not list contents of /data/user/0/com.google.android.inputmethod.latin`

Tried changing keyboard (falling back to a non-Google keyboard I have), disabling the app, stop services. Didn't work. Then rebooted and it worked.



> I use the option `Closing app process before backup`

I don't see such an option. Perhaps default in 7.0? It says that it will give the app the stop signal.

**Comment by machiav3lli** [comment]
Try restoring in main (single) if it works then it's a racing condition issue on Android's side. In batch: restoring apps alone first then data alone should solve this.

**Comment by machiav3lli** [comment]
And yeah, this is already handled better in the latest v8 alphas

**Comment by Switch123456789** [comment]
Switching the "Files & media" permissions of OABX to "Deny" and then to "Allow management of all files" fixed it for me. Before it seemed to be not set properly, showing conflicting information in different Pages in the Ui, about if it is denied or allowed.
![Screenshot_20220304-232809_Lawnchair](https://user-images.githubusercontent.com/25269380/156851146-78166f47-a6bc-4a01-bde7-ff8be277fab3.png)
FP3 (LOS18.1)

**Comment by dschrempf** [comment]
I can confirm that the workaround of @Switch123456789 works.
