### ISSUE TITLE
[Bug] Backup problems, possibly EMUI related

### ISSUE THREAD

**Issue by PookaMustard** [NeoApplications/neo-backup#327]
**Description**
I'm unable to backup the data for virtually any app on a Mate 10 lite, preventing me from actually using OABX for its intended purpose.

Apps tested:
- DuckStation
- Dragon Quest I
- [Sonic 1 SMS](https://sonic-sms-remake.blogspot.com/p/one.html)
- Cookie Clicker
- Antiyoy

**Steps To Reproduce**

1. Select an app
2. Click backup, click both
3. Check backup folder
4. The backup folder for the app only includes a properties file and the APK of the app. That's it.

In some cases (Dragon Quest and Sonic 1 SMS in this test), an error is thrown, failing the APK backup as well.

**Expected behavior**
Data successfully backed up and available in the backup folder.

**Screenshots**
The error thrown when backing up Dragon Quest/Sonic 1 SMS:
![photo_2021-03-12_19-36-54](https://user-images.githubusercontent.com/19552979/110981277-9b987300-836f-11eb-9140-ac16b5bd385f.jpg)

**System Information(please complete the following information):**

- Device: Huawei Mate 10 lite
- Android Version: Android Oreo 8.0
- ROM: EMUI8
- App's Version: RC 5.1.0, F-Droid 5.0.2

**Comment by hg42** [comment]
I think this should be fixed with https://github.com/machiav3lli/oandbackupx/pull/493, needs to be proved

**Comment by PookaMustard** [comment]
Thanks! I'll try to prove the fix this week.

**Comment by hg42** [comment]
no release yet, only an "neo alpha7" in the Telegram group

**Comment by PookaMustard** [comment]
Oh yeah, I forgot about the Telegram group. I'll get it from there and give it a spin.

**Comment by PookaMustard** [comment]
Yep, I don't think this issue occurs anymore. Except DuckStation (which I didn't try), all the apps I listed backup and restore properly now, plus apps I tested for #509. I think it's fair to close this now.

Many thanks!
