### ISSUE TITLE
random? stuck during backup

### ISSUE THREAD

**Issue by R44D44** [NeoApplications/Neo-Backup#328]
being on android 11 i select all apps (~500)+all data to backup to external sd. oandbackupx will "randomly" get stuck at some app. thats what the pulldown info shows. after finishing it shows 40-50 errors and oandbackupx says there is no backups at all. even i find hundreds of folders i  the  backup location manually.

**Comment by hg42** [comment]
this is probably fixed with https://github.com/machiav3lli/oandbackupx/pull/493, but should be proved

**Comment by DottoreG** [comment]
I do have the same problem in v 8.3.4
Trying to back up the app Osmand NB hangs. It starts normally, creates several backup files but then no further progress can be seen. NB keeps telling it's backing up. I have to cancel it.

NB How can I create a log in NB? The corresponding window ("Protokoll anzeigen") is always empty.

**Comment by machiav3lli** [comment]
@DottoreG Osmand is usually huge (depending on the installed maps), sometimes multiple GiB, which is why it takes long and NB doesn't provide progress of the singular backups.

**Comment by machiav3lli** [comment]
Otherwise the original issue is already solved since a while.
