### ISSUE TITLE
Extremely long loading at startup

### ISSUE THREAD

**Issue by Atrate** [NeoApplications/Neo-Backup#364]
Situation:
It takes OABX an extremely long time to load the main app list (and re-load it) when there are many backups in the backup directory.

It becomes even slower, reaching a couple of minutes, on slow SD cards, making the app highly tedious to use.

Proposed solution:
Cache app and backup metadata in some way — while apps themselves change dynamically (updates etc.) and the cache would often need to be refreshed, caching all of the backup metadata should be safe enough and coupd speed it all up considerably

Related issue in different project: https://github.com/MuntashirAkon/AppManager/issues/468

**Comment by JohnCGH** [comment]
If it will help, I noticed that AFwall+ (open source) also loads the app list very fast - maybe the method they use to do it could help speed up the app list loading in NeoBackup:

https://github.com/ukanth/afwall/

**Comment by Atrate** [comment]
The problem here is that NeoBackup needs to load significantly more information, many of which isn't returned by native Android APIs but read directly from storage (backup state, amount of backups, size of and type of data, etc.), which can also be slow (slow SD cards). AFWall on the other hand only needs to get packages and filter by the ones that have internet permission, that's it.

**Comment by JohnCGH** [comment]
Understood.

But do you know if a caching and/or backround process will be implemented in version 8.0 to speedup the list loading?

1) Cache: Save all info from last fully completed scan and use it to rapidly fill app list on app start, then
2) Use Background process: to verify all cached data is accurate and update it if not

**Comment by machiav3lli** [comment]
Caching is already implemented since a while in the v8-alphas, but needs some optimization to not block the UI-Thread etc..

**Comment by JohnCGH** [comment]
Cool. I am using v7 and I am looking forward to v8.

**Comment by machiav3lli** [comment]
So I just released 8.0.0, unfortunately it's not fully what you'd call stable, but this had to be done as the unintended release (#532) had to be covered). It should provide better experience than v7 in most aspects, nonetheless it's not the best from UI aspect. I'll keep this issue open, as some optimizations will come in later v8s.

**Comment by JohnCGH** [comment]
I very much appreciate the update :)

**Comment by JohnCGH** [comment]
The new caching method to load the app list is working great!

It was THE biggest reason I was not using it as much as I wanted to, but now I can.

Thank you!

**Comment by machiav3lli** [comment]
So I guess this can be closed.

**Comment by JohnCGH** [comment]
I thought this issue was already closed, but I just wanted to add my comment to thank you for doing a great job in fixing it.

Did my comment re-open it? (like this comment might do)
