### ISSUE TITLE
[Feature Request] Cancel button in backup notification

### ISSUE THREAD

**Issue by Taknok** [NeoApplications/Neo-Backup#384]
A button in the foreground service notification to stop the backup process could be useful. Specially when accidentally starting two backup (to kill only one process).

**Primer solution**
Add a button to the notification passed in the `startForeground`. The action linked to the button would called the workmanager to finish the current app and remove the other applications from the `workList` or send the event to finish the work.

**Comment by opusforlife2** [comment]
Also, a button on the app details screen to cancel the backup would be nice. The user will be able to cancel quickly after tapping the Backup button.

**Comment by hg42** [comment]
I think this should be fixed with https://github.com/machiav3lli/oandbackupx/pull/493
