### ISSUE TITLE
[Bug] Data restore fails with error

### ISSUE THREAD

**Issue by iripu** [NeoApplications/Neo-Backup#429]
**Description**
Can't restore Data backup

**Steps To Reproduce**
1. click restore button and select data.
2. shows error that restore failed.

**Expected behavior**
Restore should complete without error.

**System Information(please complete the following information):**
- Device: Asus Zenfone Max Pro M2
- Android Version: 11
- ROM: custom ROM: [OctaviOS v1.4](https://forum.xda-developers.com/t/rom-official-11-0-octavi-os-aosp-x01bd-15-12-2020.4198351/)
- App's Version: 7.0.0 (from F-Droid store)

-----------------------------

**Additional Notes**

* error log:
`{"logDate":"2021-11-22T15:03:37.655","deviceName":"ASUS_X01BDA","sdkVersion":"11","cpuArch":"arm64-v8a","logText":"a: Could not list contents of /data/user/0/com.lb.app_manager"}`

* OAndBackupX has root permission.
* I tried restoring one more app, which also gave similar error. The app file restore works fine, issue is with only data restore.

**Comment by machiav3lli** [comment]
Does restoring app at first and then data afterwards work?

**Comment by iripu** [comment]
> 

Sorry for the late reply. No, even when app is already installed, data restore does not work.

I am sending you the apk file link that has this issue, you can try it yourself, just don't update the app.
https://send.tresorit.com/a#Cj1C32O2Akujm9iP-SMj6w

**Comment by hg42** [comment]
probably fixed with #493 (must be proved)

**Comment by hg42** [comment]
@iripu this is very old, I close it now
