### ISSUE TITLE
[Feature Request] Show backup size

### ISSUE THREAD

**Issue by opusforlife2** [NeoApplications/Neo-Backup#440]
**Is your feature request related to a problem? Please describe.**

No problem. Just a wish to see some additional info.

**Describe the primer solution**

Show the backup size, probably after the date and time info of the backup.

**System Information(please complete the following information):**

- App's Version: 7.0.0

**Comment by opusforlife2** [comment]
As an aside: Is it possible to show both the old and new app sizes, like the old and new versions are shown, with the new one in brackets?

**Comment by JohnCGH** [comment]
++1

With newer phones only having internal memory, it would be VERY handy to see how much space a backup is using up of that memory.

This was if I see an app's backup is only 20MB, then I wont mind having 5+ backups of it.

But if I see that an app's backup is 500MB in size, then I would keep at most 1-2 backups of it.

Right now, it is not possible to see the backup size within the app.

**Comment by theoware** [comment]
Maybe also add the option to allow retention based on the backup's size

**Comment by opusforlife2** [comment]
Implemented in v8.1.0.
