### ISSUE TITLE
[Feature Request] Suggested Method to Notify user of newly installed "User" apps w/o backup

### ISSUE THREAD

**Issue by MrEngineerMind** [NeoApplications/Neo-Backup#483]
**Is your feature request related to a problem? Please describe it.**

Problem: I will forget to backup a newly installed app.

Right now, OABX will popup a "reminder" notification when I install a newer version of an app that "already" has one or more backups for it. This pop-up basically means "Hey, you installed a newer version of an app and you do not have a backup for it, so this is a reminder for you to perform a backup for it so that you are protected.

This pop-up will appear regardless if "New and Updated apps" is selected as a "Special filter" or not, and rightfully so because it is important to remind users to have backups of any newer app versions.

I would like to think that other users would similarly like to be reminded that a new app they installed has NO backups at all, and a reminder of that would be equally important.

**Describe the primary solution**
Titanium Backup had an interesting solution for this situation - they would place any newly installed apps at the top of the list even though the list is sorted (see screen shot below). This served as a way to bring attention to the user that a newly installed app did not have any backups at all (by displaying "No Backup yet" for that app), so they would know to do a backup of that app.  

If OABX can do something similarly like this, that would be great!

But I would also like to make another suggestion...

When OABX is first run and when it does its first scan of all the apps, it would store the "Last Install Date of a User App", which is the date that the latest user app was installed on the device.

Then whenever OABX is run again and does a scan, it can then see if a newer "user" app was installed since that date. And if it finds any, it will add those apps to the "Updated Apps" pop-up reminder (along with any newer versions of apps that already have backups) and I guess the name of this pop-up should be "New and Updated Apps" instead of just "Updated Apps".

And as a last suggestion, I think it would be helpful if this pop-up "New and Updated apps" reminder would be dismissable by the user, instead of always being visible. So, if the user does dismiss the pop-up, OABX will then update the value of "Last Install Date of a User App" to be the present date/time, so that the pop-up will appear again if a new or updated app is found after the new date/time. And when a backup is done for the newly installed app, it will also reset this date value to the current date/time. (NOTE: I'm guessing this "Newly Installed App" check should just search for new "user" apps so it won't add any OTA updated system apps to the pop-up notification list of apps)

My point is that even though a user could just *remember* to choose the filter "New and Updated Apps" every once in a while to check to see if there are any "updated" apps (for the EXISTING apps that they ALREADY have older backups for), the "pop-up" reminder of these "updated" apps was still added as an *additional* feature to the app because obviously it is important that the user know when they don't have a backup of a *newer* version of an app. So, wouldn't it be equally important to remind a user that they don't have ANY backups for a "newly installed" app *without* the user having to keep "remembering" to selecting the "New and Updated Apps" filter to check for them?

**Screenshots**

![TIB-New](https://user-images.githubusercontent.com/18239066/153273070-910f73b8-c164-45cb-8ed4-9f8c4382a43e.png)

**Comment by MrEngineerMind** [comment]
Bump...

Right now Neobackup has a special filter called "New and updated apps" in the "Sort and Filter" settings.

Just the fact that you named this filter "NEW and Updated apps" shows that you believe the two types of apps are related and it warranted to have such a filter that will display BOTH of these app types.

So, if you agree that the two types are similiar, then why are you only displaying "Updated" apps in that persistance pop-up bubble on the main screen after it does a scan?

Wouldn't it also be helpful to include "new" apps in that bubble so it will remind users to at least perform a first backup of a newly installed app?

It doesn't make sense that you think the two are related and have a dedicated "special filter" for them both, but then break that relationship when displaying the bubble.

So many times I forget to backup an app because neo never gave me an indication that there was no backup for a newly installed app. Yes, I can select the filter to display apps with no backup, but that's a hassle because I would then have to keep switching the list filter between "All Apps" and "New and Updated".

Please at least add a setting to "Include New Apps in Bubble notification".

Thank you.

**Comment by machiav3lli** [comment]
Actually in the latest 8.3.2-rc1 build, I've revamped filtering, micro-filtering is now possible along all the previous special filters (and more)…
![Sort/Filter Sheet of latest rc](https://github.com/NeoApplications/Neo-Backup/assets/40302595/91c6c9e8-5b53-4070-8d37-438e7405d157)

**Comment by machiav3lli** [comment]
But yeah, I'll add an option to include new apps in the bubble

**Comment by MrEngineerMind** [comment]
:) :) :)
