### ISSUE TITLE
[Bug] Tool - Remove backups - not working on first usage.

### ISSUE THREAD

**Issue by MartinX3** [NeoApplications/Neo-Backup#502]
**Description**
The tool "remove backups" doesn't work on the first usage.
It tells me that it needs to load the list of backups.
But it did already load them, since I deleted them one by one before seeing this tool.
A second click on the tool shows me the list.

**Steps To Reproduce**

1. Wait for the backuplist being loaded.
1. Open the tools section.
1. Click on "delete backups".
1. Only a warning appears.

**Expected behavior**
My list of backups to remove.

**Screenshots**
N/A

**System Information:**

- Device: Sony Xperia XZ2
- Android Version: 11
- ROM:  LineageOS
- App's Version: 7.0.0

**Comment by hg42** [comment]
the list you see is a mix of cached and already updated items and list loading takes much longer as you think.
If you do some manual operations you trigger the list loading again.

The manual operations only need this one item, if you see it, it is existing and can be used.
But an operation on the whole list needs it completed loaded before it can filter it etc. (or let's say it's not done incrementally).

One of the next iterations will have an indicator, while the list is still loading (from my POV it's a bit uncertain, which parallel operations to take into account).
