### ISSUE TITLE
[Bug] could not list contents /data/users/0/

### ISSUE THREAD

**Issue by Reporter1** [NeoApplications/Neo-Backup#504]
I am trying to do my first backup and after so many apps I see the error I have the status notification bar 

App name a: could not list contents of /data/user/0/ app directory 

**Steps To Reproduce**

1. Open oandbackupx
2. Select backup tab
3. Select all user apps, from filters make sure user apps is only selected and system apps is unselected
4. Select backup 

**Expected behavior**
All apps to backup with no errors. 

**Screenshots**
Only if there's no clear logs, add screenshots to help explain your problem.

**System Information(please complete the following information):**

- Device: Pixel 5
- Android Version: 11
- ROM: lineage 18.1
- App's Version: latest from fdroid 7.0

-----------------------------

**Additional Notes**
From settings I have selected

Execlude app cache
Backup device protected data
External data 
Media
Obb

Disable verify apps over USB ticker 
Stop cont pre Post ticked 

Verify apps over USB in settings ticked 

Root is also enabled on the app via magisk. 

I also have tested the backup by going to the said fail app, I. E. Titanium backup, zoom, torque, killed all (just as a prereq as it not running in the background anyway) and selecting backup on the menu of the app, the app backup still fails. 

![Screenshot_20220319-144414_OAndBackupX](https://user-images.githubusercontent.com/34857551/159126808-84d83f94-a31c-4eaf-a4f4-7779bd5615b5.png)
![Screenshot_20220319-143958_Firefox_Focus_Nightly](https://user-images.githubusercontent.com/34857551/159126812-e8a17407-1feb-455c-8efa-65788c92a22c.png)

**Comment by Reporter1** [comment]
Log file entry of the individual backup I tested that failed, youtube (vanced version) 

{"logDate":"2022-03-19T15:15:48.353","deviceName":"redfin","sdkVersion":"11","cpuArch":"arm64-v8a","logText":"a: Could not list contents of /data/user/0/com.google.android.youtube"}}

Torque Pro 

{"logDate":"2022-03-19T15:16:27.151","deviceName":"redfin","sdkVersion":"11","cpuArch":"arm64-v8a","logText":"a: Could not list contents of /data/user/0/org.prowl.torque"}

**Comment by lukszi** [comment]
I'm having the same issue, any help would be appreciated

**Comment by Reporter1** [comment]
Hi just want to update, i tried the latest Alpha apk from the community group (not sure if i can say which?) and looks like the issue is solved and the app is working alot smoother. 

At this min, all 220 apps local have backup, just on the final one, WhatsApp (as I selected media to backup to) so is taking a bit of time.

At this moment the backup size of the directory is 26.61 gb so i can safely say v8 is a working for me so far on backing up. 
Will try a restore test once the backup is complete.
Very happy with this, now I have some trust on the backup and can now move rom to 12.

Thank you for the great work.
