### ISSUE TITLE
[Feature Request] A WAY TO INSTALL BACKUPS IN WORKPROFILE

### ISSUE THREAD

**Issue by Raif1** [NeoApplications/Neo-Backup#505]
**Is your feature request related to a problem? Please describe it.**
No

**Describe the primary solution**
I want an option to install backed up apps in my workprofile

**Describe alternative solutions, 
No

**Screenshots**
If you're willing to add demonstrative screenshots, you're welcome to do so.

**System Information (please complete the following information):**

- Device:Phh
- Android Version: 11
- ROM: lineageos 
- App Version: 7.0.0

**Comment by machiav3lli** [comment]
You can install NB in the work profile and operate it from there (Magisk multi-user should be also on). In our latest alpha the double restore issue is also solved.
