### ISSUE TITLE
[Feature Request] Improve tags

### ISSUE THREAD

**Issue by HyperCriSiS** [NeoApplications/Neo-Backup#526]
Hi,

it would help a lot if the tags could be used for filters for the automatic backup instead of the actual implementation with the "own list".
Also actually setting tags is quite a pain, because you have to write it every time for each app. The already used tags should be available for selection.
What I also miss is the ability to backup app data only if it was changed.

Best regards,
Hyper

**Comment by machiav3lli** [comment]
Most of the mentioned is already on the long list, but don't know when will it be a todo
