### ISSUE TITLE
Noaccess to SDcard since update to Neo

### ISSUE THREAD

**Issue by bernique** [NeoApplications/Neo-Backup#538]
**Description**
I recently updated OAndBackup to Neo Backup, and since it always asks me to choose a folder for my backup.

**Steps To Reproduce**

1. Have OandBackup installed and used with backup on external SD
2. Update to Néo Backup
3. Open it, it asks for a backup folder, choose the one used by OAndBackup
4. Result: forced close, reopen and it asks again for a backup folder

**Expected behavior**
Keep the previous folder as a backup folder. I also tried to choose a new empty folder, but without success

**Screenshots**
I have tried to manually set the backup path in the xml sile, but I get:
![image](https://user-images.githubusercontent.com/9451214/165682192-6999871a-b675-4b7e-b2ce-bfd4c1bb748d.png)

- Device: Samsung A320FL 2017
- Android Version: 10
- ROM: (AOSP, MIUI, OOS...) CRDroid 6.25
- App's Version: 8.0.0

**Comment by bernique** [comment]
FYI, I'm back on OAndBackup, and everything works back again.

**Comment by machiav3lli** [comment]
Please read #532
