### ISSUE TITLE
8014.  Restore  not installed apps. Cannot  show apps

### ISSUE THREAD

**Issue by SamOctober** [NeoApplications/Neo-Backup#539]
**Description**

**Steps To Reproduce**

1. ...
2. ...
3. ...
4. Crash, Nothing happens ....

**Expected behavior**

**Screenshots**
Only if there's no clear logs, add screenshots to help explain your problem.

**System Information(please complete the following information):**

- Device: 
- Android Version: 
- ROM: (AOSP, MIUI, OOS...)  
- App's Version: 

-----------------------------

**Additional Notes**

* If you're on the latest Test version(from the TG-Channel or Matrix-Room) please report there directly, not here.

* If you're on the latest github version:
  
  * Please read the [FAQ](https://github.com/machiav3lli/oandbackupx/blob/master/FAQ.md) first.
  * Please read all the open Issues. If one does match yours, leave a comment there if there's some extra information you can provide.

* If you're not on the latest github version. Update, then make sure that the bug is still there. If it's go further with reporting.

Thanks for reporting.

**Comment by andreapx** [comment]
@machiav3lli 
I still have this problem with version 8.3.1.
I saw he app I needed to restore, I've tried to restore everything, but it gave me the error that the installed app was newer than the one backed up, so I've uninstalled the app and now I don't see anymore this app in the restore section.
