### ISSUE TITLE
Crashes 

### ISSUE THREAD

**Issue by ansarimohammed422** [NeoApplications/Neo-Backup#541]
**Description**
When i open the app it just suddenly crashes 

I am on android 12l redmi note 4

What to do

**Steps To Reproduce**

1. ...
2. ...
3. ...
4. Crash, Nothing happens ....

**Expected behavior**

**Screenshots**
Only if there's no clear logs, add screenshots to help explain your problem.

**System Information(please complete the following information):**

- Device: 
- Android Version: 
- ROM: (AOSP, MIUI, OOS...)  
- App's Version: 

-----------------------------

**Additional Notes**

* If you're on the latest Test version(from the TG-Channel or Matrix-Room) please report there directly, not here.

* If you're on the latest github version:
  
  * Please read the [FAQ](https://github.com/machiav3lli/oandbackupx/blob/master/FAQ.md) first.
  * Please read all the open Issues. If one does match yours, leave a comment there if there's some extra information you can provide.

* If you're not on the latest github version. Update, then make sure that the bug is still there. If it's go further with reporting.

Thanks for reporting.

**Comment by tsiflimagas** [comment]
At least mention the app's version, if you want to expect any help. Also, the crashlog will be needed.

**Comment by ansarimohammed422** [comment]
> At least mention the app's version, if you want to expect any help. Also, the crashlog will be needed.



Crash log url

https://paste.evolution-x.org/6ZyVLM

**Comment by ansarimohammed422** [comment]
Have it

**Comment by RustyNova016** [comment]
Same problem here. 

Ulefone Armor6, android 8.1.0, version 8.0.2

I start the app and it crashes less than a second later

**Comment by RustyNova016** [comment]
Actually I think I found my problem. My phone isn't rooted. 

F-Droid didn't specified that

**Comment by franco27** [comment]
same thing.  
After installing from F–Droid, I cannot open the application.  
I don't see the application window.  
Crash immediately after clicking the icon.  
I give you my system information from my mobile.
Xiaomi Redmi 8 
Android Version 10 Android 10 
MIUI
V12.5.2.0.QCNEUXM

Architecture
 64-bit

Instruction sets
arm64-v8a armeabi-v7a armeabi Qualcomm®
Snapdragon™ 439

CPU
4 x Cortex-A53
Cores 8
RAM size 4 GB

**Comment by hg42** [comment]
@ansarimohammed422 @franco27 is your device rooted?

8.0.3-alpha1 from the telegram group has a fix to show the "not rooted" dialog before it uses root (a bug I introduced)

**Comment by franco27** [comment]
My phone is not rooted

**Comment by machiav3lli** [comment]
@franco27 So case solved! I'd go and guess that the same applies to @ansarimohammed422 and close the issue, if not feel free to write back.

**Comment by franco27** [comment]
I no longer have an immediate close when opening your application.
 But I still can't try your app.  There is a message telling me that my mobile phone is not rooted.

**Comment by machiav3lli** [comment]
@franco27 as already said, it's clear that you're missing root. Root is required: this is mentioned in all communication channels (app description, FAQ etc..)

**Comment by franco27** [comment]
Thank you for your reply.  It's a pity that it is necessary to have a rooted mobile
