### ISSUE TITLE
[Bug] Serializer for class c is not found

### ISSUE THREAD

**Issue by gerroon** [NeoApplications/Neo-Backup#545]
**Description**
I am getting this error while trying to back up an app.

**Steps To Reproduce**

1. Open the app
2.Select the app to backup
3.Back it up
4. Error mesage

**Expected behavior**
It should backup without borking the procesd

**Screenshots**
![chrome_8qZT54n8cD](https://user-images.githubusercontent.com/8519469/166116466-ca348538-eee4-4388-90b6-22c1e281b0f5.jpg)

**System Information(please complete the following information):**

- Device: Pixel 4
- Android Version: LineageOS 18.1
- App's Version: 8.0.0

**Comment by Jakeler** [comment]
I had the same problem with 8.0.0, but after updating to 8.0.2 it works fine. Unfortunately this update is not available on F-Droid for some reason...

**Comment by machiav3lli** [comment]
It takes couple of days till FDroid detects, builds then serves updates

**Comment by machiav3lli** [comment]
Duplicate #532
