### ISSUE TITLE
[Bug] super laggy, doesn't backup

### ISSUE THREAD

**Issue by erahhal** [NeoApplications/Neo-Backup#546]
**Description**
On opening the app, have to wait 30-40 seconds for it to become responsive, ignoring android messages asking to kill the app.  Once it is responsive, executing a backup doesn't work, just stuck at 0/376. Lastly, root message "Neo Backup was granted Superuser rights" is stuck at the bottom of the screen and doesn't go away without rebooting phone.

Something does seem to be happening behind the scenes as various apps are getting killed and locked for several seconds in the background. It does seem to eventually make progress, but with hundreds of notification errors, and ends with failure.

**Steps To Reproduce**

1. use as described in "Description" section

**Expected behavior**
Loads immediately without hang, backup works, and root permissions message goes away.

**Screenshots**
![Screenshot_20220430-150436_Neo_Backup.png](https://user-images.githubusercontent.com/1174130/166124338-1dd82e0a-17d9-400b-a367-b6f276b3fed3.png)

![Screenshot_20220430-150255_Nova7.png](https://user-images.githubusercontent.com/1174130/166124439-8a793162-4950-4355-89d2-83873f1355e9.png)

![Screenshot_20220430-151738_Nova7.png](https://user-images.githubusercontent.com/1174130/166124441-5a27fc5d-341a-4d7b-a976-ead16c7052b2.png)

![Screenshot_20220430-154333_Signal.png](https://user-images.githubusercontent.com/1174130/166125004-30e2c986-d4a3-4ffe-9e70-f27a7d33918c.png)

**System Information(please complete the following information):**

- Device: OnePlus 7 Pro
- Android Version: LineageOS 18.1 + MicroG
- App's Version: 8.0.0, latest from Fdroid

**Comment by machiav3lli** [comment]
For reference read #532
