### ISSUE TITLE
[Bug] Vanishing restored data after reboot

### ISSUE THREAD

**Issue by SamOctober** [NeoApplications/Neo-Backup#550]
**Description**

**Steps To Reproduce**

1. ...Clean install  rom
8.02
restore 70 app + data
well done  to   use
but   reboot   >>>>   all   data   lost   !

lineage 19.1   (  android   12.1  )
aosp

2. ...
3. ...
4. Crash, Nothing happens ....

**Expected behavior**

**Screenshots**
Only if there's no clear logs, add screenshots to help explain your problem.

**System Information(please complete the following information):**

- Device: 
- Android Version: 
- ROM: (AOSP, MIUI, OOS...)  
- App's Version: 

-----------------------------

**Additional Notes**

* If you're on the latest Test version(from the TG-Channel or Matrix-Room) please report there directly, not here.

* If you're on the latest github version:
  
  * Please read the [FAQ](https://github.com/NeoApplications/Neo-Backup/blob/master/FAQ.md) first.
  * Please read all the open Issues. If one does match yours, leave a comment there if there's some extra information you can provide.

* If you're not on the latest github version. Update, then make sure that the bug is still there. If it's go further with reporting.

Thanks for reporting.

**Comment by machiav3lli** [comment]
The vanishing data issue has been reported by couple of users (most testers didn't face it), and while we couldn't find the variable that makes it happen, an affected user reported that excluding device-protected data makes the restored data survive reboot, please try this and report back.

**Comment by SamOctober** [comment]
folder  with  device_protected_files.tar.gz  
user rom     Backup and Restore   good use

----------------------------------------------------   
Clean install rom

folder  with  device_protected_files.tar.gz
Restore
reboot  >   all  data  lost

-----------------------------------------------------

folder  with  NO  device_protected_files.tar.gz
reboot  >  all  data  no lost

How to skip  all  the   (  device_protected_files.tar.gz )  ?    batch restore 


RedMi_Note_4  ( mido )   lineage 19.1   (  android 12.1  )

bad english  
thank you

**Comment by machiav3lli** [comment]
@SamOctober just disable device protected data from settings>service
