### ISSUE TITLE
[Bug] Slow and: g: serializer for class c is not found 

### ISSUE THREAD

**Issue by starbrights** [NeoApplications/Neo-Backup#551]
**Description**
The app acts very slow (it even pops up a window: wait or force)
When push to "save" it ends up with the above mentioned error message.

**System Information(please complete the following information):**

- Device: S10e 
- Android Version: 11 / LOS 18.1 
- ROM: LineageOS for microG
- App's Version:  8.0.0.

It was working in a previous version.

**Comment by JohnCGH** [comment]
I think version 8.0.2 fixes that.

**Comment by machiav3lli** [comment]
Duplicate to #532
