### ISSUE TITLE
[Bug] App Updates Remove Scheduled Jobs

### ISSUE THREAD

**Issue by DavidBerdik** [NeoApplications/Neo-Backup#557]
**Description**
I use the Neo Backup distribution provided via F-Droid on my phone. The first version of the app that I installed on my phone was the last version that used the OAndBackupX branding (7.0.0). When F-Droid updated the app to the horribly broken Neo Backup 8.0.0 release, I noticed that my scheduled jobs were gone and I had to reconfigure them. Even though the scheduled job did not do anything thanks to the issues with that release, I figured it would at least be configured for when the issue was fixed. Neo Backup 8.0.2 has since been released, and my scheduled jobs are gone again.

**Steps To Reproduce**

1. Install OAndBackupX 7.0.0 and configure a scheduled job.
2. Update to Neo Backup 8.0.0. The configured job will be missing. Configure a new job.
3. Update to Neo Backup 8.0.2. The configured jobs will again be missing.

**Expected behavior**
The scheduled jobs should not be wiped every time an app upgrade is pushed.

**System Information:**

- Device: Pixel 6 Pro
- Android Version: 12.1
- ROM: Google Official Factory Image
- App's Version: 7.0.0, 8.0.0, and 8.0.2

**Comment by machiav3lli** [comment]
To make two things clear:
- 8.0.0 was released accidentally and shouldn't be released.
- 8.0.2 is more or less a three-quarter-finished 8.0.0.

Now to the issue: We already have an export/import tool for schedules since couple of versions in settings>tools. Otherwise we'll try to keep the DB stable (or provide (auto-)migrations) for next releases but that's something that no one can say for sure that it happens, as I surely have other priorities than yours and limited time to fulfill my plans.

**Comment by DavidBerdik** [comment]
So, to be clear, this was an accident and should not be expected to be the norm?

Also, I know about the import and export tool, but isn't that intended for migrating your settings to a different phone? If so, it does not sound like a workable solution to this problem if this is in fact a problem.

**Comment by machiav3lli** [comment]
@DavidBerdik nah you mixed what I've wrote.

What is accident is the earlier 8.0.0 release, it shouldn't have been published (but F-Droid tag scanner had another opinion) as we were still working on v8 and in a declared alpha state. Part of the the planned v8 had to do with reforming the schedules and that's what would cause removing the schedules anyway which is part of 8.0.2, which is a compromise-release considering the flood of issues that the accidentally release caused. The planned 8.0.0-state isn't there yet, but schedules should be "safe" till next major release.

Export/import is only intended for schedules and does nothing else.

**Comment by DavidBerdik** [comment]
Ah okay! I understand now. In that case, I'll just hold out. Thanks for continuing to maintain this application. It really helps fill the void that was left by Titanium Backup becoming abandonware. 🙂

**Comment by JohnCGH** [comment]
+1 what he said!
