### ISSUE TITLE
[Bug] Cannot open the App

### ISSUE THREAD

**Issue by fnfontana** [NeoApplications/Neo-Backup#558]
**Description**
The app closes itself immediately after opening it.

**Steps To Reproduce**

1. Just click on the app icon
2. Crash, Nothing happens ....

**System Information:**

- Device: Redmi Note 8 Pro
- Android Version: 11
- ROM: MIUI 12.5
- App's Version: 8.0.2

-----------------------------

**Additional Notes**

* A few weeks ago the app was normally working.

* My smartphones is not root, since then I have installed magisk, but not activate it yet.

* Using the latest version available on F-droid.

* Looks like it started to happen since the last update. Buy I'm not sure if this can be a conflict with another app.

**Comment by tsiflimagas** [comment]
Neo-Backup needs root access to work, that's mandatory. Make sure to give root access in magisk app.

**Comment by BenHerbst** [comment]
Is there no better way to give this information to the user than just crashing?
Maybe show a dialog window: "You have to get root access to use this app"

**Comment by machiav3lli** [comment]
@BenHerbst there was, but then through  some refactoring and lib updates, this wasn't valid. This was since last public release fixed.
