### ISSUE TITLE
[Bug] Backups are missing in 8.x.x

### ISSUE THREAD

**Issue by boocov** [NeoApplications/Neo-Backup#561]
The version 8.0.2 does not find all backups of my apps, which I created with 7.0.0 (or maybe below). I also tested 8.0.3-alpha1, but still the same problem.
With 7.0.0 it takes about 90 seconds to load the list containing all backups. Unfortunately version 8.0.2 does not find all.
I have a huge amount of app backups of about 250.
I also tested on another device (with LOS 19/Android 12) with fewer backups, but there are also missing backups.

 #### System Information (please complete the following information):
-   Device: Redmi Not 4 (mido)
-   Android Version: 11
-   ROM: (AOSP, MIUI, OOS...) LineageOS
-   App's Version: 8.0.2 and  8.0.3-alpha1

**Comment by mddvul22** [comment]
I have this problem, also.  I have many backups that were made back in 2021.  These backups do not appear in the newest version of Neo Backup.

**Comment by boocov** [comment]
I think I found the cause of this behavior (at least for some of my missing backups).
The problem seems to be that if the iv byte array is missing in the properties file, the backup is missing in Neo Backup 8.x.x, also tested with 8.1.3.
To reproduce this problem, use an old backup of an app and check it is not recognized in NB. Then add `,"iv":[]` in the properties file and reload NB, the backup will now be found.


https://user-images.githubusercontent.com/83028254/191364519-ca0eef71-dfde-4462-a0c8-f015ecb83660.mp4


Backup is missing in NB with this properties file:
```
{"backupDate":"2021-06-09T09:50:06.034","hasApk":true,"hasAppData":false,"hasDevicesProtectedData":false,"hasExternalData":false,"hasObbData":false,"cpuArch":"arm64-v8a","packageName":"com.amaze.filemanager","packageLabel":"Amaze","versionName":"3.3.2","versionCode":77,"profileId":0,"sourceDir":"/data/app/~~IAqibBnlT3XVCda08hEfkg\u003d\u003d/com.amaze.filemanager-7qtoVRdgia4Wz149TNPR3A\u003d\u003d/base.apk","splitSourceDirs":[],"isSystem":false}
```

Backup is found in NB with this properties file (with manually added `,"iv":[]`):
```
{"backupDate":"2021-06-09T09:50:06.034","hasApk":true,"hasAppData":false,"hasDevicesProtectedData":false,"hasExternalData":false,"hasObbData":false,"cpuArch":"arm64-v8a","packageName":"com.amaze.filemanager","packageLabel":"Amaze","versionName":"3.3.2","versionCode":77,"profileId":0,"sourceDir":"/data/app/~~IAqibBnlT3XVCda08hEfkg\u003d\u003d/com.amaze.filemanager-7qtoVRdgia4Wz149TNPR3A\u003d\u003d/base.apk","splitSourceDirs":[],"isSystem":false,"iv":[]}
```

This can also be reproduced, when you create a backup with NB 8.1.3 and remove the iv from properties file, then the backup is missing.

**Comment by hg42** [comment]
> add `,"iv":[]` in the properties file and reload NB, the backup will now be found.

ok, thanks for investigating, I'll have a look

**Comment by hg42** [comment]
should be solved, next pumpkin in Telegram group should contain it (also next release)

**Comment by boocov** [comment]
Thanks in advance. Will check it as soon as it is released
