### ISSUE TITLE
[Bug] Restored app loses all data after update from F-Droid

### ISSUE THREAD

**Issue by dionorgua** [NeoApplications/Neo-Backup#566]
**Description**
Strange thing happens with at least two apps: Gadgetbridge and FairEmail. 

OnePlus 8 Pro. Android 11 -> 12 update happens. 

In short (app means Gadgetbridge or Fairemail):
- Backup made on Android 11.
- Restored on Android 12. Works fine, 
- Update happens in F-Droid.
- Once update installed, app is like fresh install without any data
- Tried to restore everything except APK: nothing happens.
- Restore everything (with allowed downgrade in settings): nothing
- Uninstall app completely then restore same old backup: success, got data
- Tried update again: data loss again.

Device:

- Device: OnePlus 8 Pro
- Android Version: 12
- ROM: (AOSP, MIUI, OOS...)  OxygenOS 12
- App's Version: 8.0.2

**Comment by dionorgua** [comment]
Yep. I was able to:
* Uninstall app
* Restore it again without device-protected data
* Update from F-Droid

It works this way

**Comment by machiav3lli** [comment]
Ok, so let's close this for now (as a related/duplicate). We're working with the community trying to find out the source of the issue. Another "hack" would be to just disable restoreTarCmd (under settings→advanced→developer settings), then you should be able to restore the device-protected data too.
