### ISSUE TITLE
[Feature Request] Neo-Backup as system app should work on none rooted devices

### ISSUE THREAD

**Issue by LeOS-GSI** [NeoApplications/Neo-Backup#572]
I'm building the ungoogled LeOS-GSI (Android 10 / 11 / 12.1). I have integrated Seedvault backup, because no rooted device is needed. But seedvault can't backup all apps and data. So I want integrate Neo_backup in my GSIs, but the app still needs a rooted device. 

Pls implement Neo-Backup to run as a system app with full access like seedvault. I think this is  very important, because a lot of people don't want root the device, because some apps, especial Banking Apps, wont work on rooted devices.

Thx

**Comment by tsiflimagas** [comment]
That's not possible. Neo backup is made to work with root access. Making it a system app won't change anything. To work like seedvault, it will have to receive a lot of changes, which I think are out of scope for NB, and it would still not backup/restore anything more than seedvault. Also, though I don't know if you meant it like that, I don't think installing NB as a system app is something that can be implemented in the app itself.

**Comment by machiav3lli** [comment]
A short answer: A system app still has a lot of restrictions (this is mainly why Seedvault failed), while root is a MUST (and this seems to not be going anywhere soon) if NB would fullfill what is developed to. This has already been suggested multiple times (even pretty early at the project start #44) and as said, there's no prospect for it to get implemented. I'll close this and you can write us in the TG group, if you see the need for discussion.
