### ISSUE TITLE
no toybox found

### ISSUE THREAD

**Issue by hg42** [NeoApplications/Neo-Backup#576]
Hi, i have the same crash on startup, but differet logcat:
Android 12.1 
```
06-09 20:11:34.395 11418 11434 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 1110341; state: ENABLED
06-09 20:11:34.403 11418 11418 D h@7:g$a : Command(s) "/data/local/toybox" --version ended with -1
06-09 20:11:34.403 11418 11418 D h@1:g$a : Running Command: "/data/local/toybox"
06-09 20:11:34.403 11418 11418 D h@7:g$a : Command(s) "/data/local/toybox" ended with -1
06-09 20:11:34.404 11418 11418 D h@1:g$a : Running Command: "toybox" --version
06-09 20:11:34.404 11418 11418 D h@7:g$a : Command(s) "toybox" --version ended with -1
06-09 20:11:34.404 11418 11418 D h@1:g$a : Running Command: "toybox"
06-09 20:11:34.404 11418 11418 D h@7:g$a : Command(s) "toybox" ended with -1
06-09 20:11:34.404 11418 11418 D <init>@7:g: No more options for utilbox. Bailing out.
06-09 20:11:34.404 11418 11418 D AndroidRuntime: Shutting down VM
06-09 20:11:34.404 11418 11418 E AndroidRuntime: FATAL EXCEPTION: main
06-09 20:11:34.404 11418 11418 E AndroidRuntime: Process: com.machiav3lli.backup, PID: 11418
06-09 20:11:34.404 11418 11418 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.machiav3lli.backup.OABX: y7.g$e:
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6767)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at android.app.ActivityThread.access$1500(ActivityThread.java:256)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7870)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
06-09 20:11:34.404 11418 11418 E AndroidRuntime: Caused by: y7.g$e:
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at y7.g.<init>(:7)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at com.machiav3lli.backup.OABX.onCreate(:1)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1229)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6762)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        ... 9 more
06-09 20:11:34.406  1396 11444 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
06-09 20:11:34.406  1396  9305 W ActivityTaskManager:   Force finishing activity com.machiav3lli.backup/.activities.SplashActivity
06-09 20:11:34.408 11418 11418 I Process : Sending signal. PID: 11418 SIG: 9
06-09 20:11:34.409  1396  1487 I EventSequenceValidator: dec AccIntentStartedEvents to 1
06-09 20:11:34.417  1396  9305 I ActivityManager: Process com.machiav3lli.backup (pid 11418) has died: fg  TOP
06-09 20:11:34.421   682   682 I Zygote  : Process 11418 exited due to signal 9 (Killed)
06-09 20:11:34.422  1396  1503 I libprocessgroup: Successfully killed process cgroup uid 1110341 pid 11418 in 5ms
```

_Originally posted by @ashjas in https://github.com/NeoApplications/Neo-Backup/issues/499#issuecomment-1151215644_

**Comment by hg42** [comment]
> Hi, i have the same crash on startup, but differet logcat

as you already said yourself, it's not the same crash, but a very different...
So, this should be a separate issue.

You don't have a toybox on your system, which is weird, I think.
Why is it missing? toybox should be provided by any Android version supported by NB.
Also, NB cannot work without toybox. And yes we know busybox, but it's even more complicated with this.

**Comment by ashjas** [comment]
I dont know why its missing.
I am using arrowos 12.1 vanilla build for poco x3 pro.
I have yet to see any app not working due to toybox before NB.
I guess its installation also requires root ?

**Comment by machiav3lli** [comment]
@ashjas there's a magisk module to install it, but even this would need some optimization from our side.
It's really weird that it's removed from system, is the build official or unofficial? If official it's more worrying direction that the ROM developers are taking.

**Comment by machiav3lli** [comment]
@ashjas there's a magisk module to install it, but even this would need some optimization from our side.
It's really weird that it's removed from system, is the build official or unofficial? If official it's more worrying direction that the ROM developers are taking.

**Comment by ashjas** [comment]
its official version.

**Comment by hg42** [comment]
most root apps seem to only use simple commands or if they need more they are using busybox.
I tried busybox, too, but it doesn't provide all features we need (mainly for ls and tar).
There are also other reasons about providing busybox, dependencies and such.

**Comment by hg42** [comment]
> I guess its installation also requires root ?

wait...does it mean, your device isn't rooted?

**Comment by hg42** [comment]
> there's a magisk module to install it, but even this would need some optimization from our side.

actually the current main branch already picks up the "best" toybox from this list:

`            "/data/local/toybox", 
             "toybox-ext", 
             "toybox_vendor", 
             "toybox",
`

the toybox-ext would be the one from the magisk module.

"best" means newest in the supported(=tested) range, excluding version ranges with erroneous behavior, if possible otherwise enabling workarounds.

From memory, this should be included in the 8.0.3-beta1 apk pinned in the telegram group

**Comment by hg42** [comment]
@ashjas is it solved?

**Comment by ViktorWalter** [comment]
I am using the version found on f-droid at the current date.
The toybox executable is located at different directory for me - `/system/bin/toybox`, so Neo-Backup throws hundreds of warnings looking for it and fails to backup.
I have fixed this issue through workaround - creating a symlink to the above in `/data/local/`.
But the app probably shouldn't rigidly use a hard-coded address for the executable.

**Comment by hg42** [comment]
@ViktorWalter

> on f-droid at the current date

don't do that, please explicitly show the version you use, we don't know what is current for you or was at the time of the message, or which f-droid client you use, or if it shows all versions, etc. pp.

And I don't get why you didn't add the info you refer to, e.g. the logcat you are looking at ("hundreds of errors").
Why do we need to ask for it?

As you see in the list, only one path is hardcoded, when trying to execute the toybox versions:

> "/data/local/toybox", 
> "toybox-ext", 
> "toybox_vendor", 
> "toybox",

that one is hardcoded, because
* `/data/local/toybox` should have priority over the others
* `/data/local` is not in the path

warnings at the start of NB are expected (but not hundreds, only a few), while trying to execute these toybox variants and getting version and eventually other features of the toybox variant via shell commands.

For each toybox, NB calculates a score (listed in the log, you can also find it under preferences / tools / terminal, info button).
The score considers known bugs and slightly prefers newer versions and some variants.
The score list looks like this and is sorted by the score:
```
toybox: 0.8.0 (unknown) -> 2010008002 good, no known bugs
toybox_vendor: 0.8.0 (unknown) -> 2010008001 good, no known bugs
/data/local/toybox: ShellCommandFailedException
toybox-ext: ShellCommandFailedException
toybox-stock: ShellCommandFailedException
```
Then the one at the top is chosen and used as listed before the colon.

In your case (before putting toybox in `/data/local/`) the last toybox should be executable, because `/system/bin` is probably in the system path.

If you get hundreds of errors it is probably because of other problems.
If execution of a command fails, the calling entity (e.g. the su library) gets an error from the shell which usually lists the command that it tried, in this case `/system/bin/toybox`, probably just because the `toybox` command (without path) was found at this place.
Why you get errors should be shown in the error lines...

So, please attach parts of a logcat from the start of NB, it should include the toybox score list and at least one of the hundreds of errors, you get.

Alternatively you may use the built in terminal to create such a log:

* press Clear (in case the terminal is not empty)
* press info (to get the score list and info about the su / root solution)
* enter a command (e.g. `echo test` this will probably throw such an error that you mention)
* press ->Log (this creates an entry in the Logs and clears the terminal)
* goto preferences / tools / logs
* you should see the text from the terminal
* press share button and send the log file to your mail or something to be able to add it here
  you may also share it directly to the telegram group if you have telegram, or to my email address here

**Comment by hg42** [comment]
no answer... especially not a log that could clarify some questions, so I'll close it.

I think toybox detection works well...
I guess toybox is in /system/bin for most users (mine is), so that's definitely not a problem...

**Comment by ViktorWalter** [comment]
Sorry, I didn't find the time to do this properly.
