### ISSUE TITLE
[Bug] Apps data get reset after reboot.

### ISSUE THREAD

**Issue by HaukaMirai** [NeoApplications/Neo-Backup#578]
**Description**
Hello,after June security patch update on any rom (Android 12L) apps data get resets if I reboot the phone,it didn't happens may security patch roms.

**Steps To Reproduce**

1. Flash ROM,install and open neo backup grant all the permissions.
2. restore any previously backed up apps with data,apps restored normally without any problem.
3. Now,reboot the phone,boom all the restored apps data resets.
4. Try to open the any restored app,it shows welcome screen as if it's freshly installed.

**Expected behavior**
Nothing should happen even if I reboot the phone,data should be there.

**System Information**

- Device: Redmi Note 9 pro
- Android Version: Android 12L (12.1)
- ROM: AOSP ROM
- App's Version:  8.0.2

-----------------------------

**Comment by machiav3lli** [comment]
Duplicate of #550. To fix on your side for now, avoid restoring device protected data. Otherwise a fix has been already introduced in latest test builds in the community group and will come with next release
