### ISSUE TITLE
[Bug] App keeps crashing! 

### ISSUE THREAD

**Issue by GraphixMedia** [NeoApplications/Neo-Backup#581]
**Description**
Today I installed the app and it crashed immediately Android says: "app keeps crashing". 

**Steps To Reproduce**
1. Deleted cache and data
2. Reinstalled the app
3. Crash, Nothing happens ....

**Expected behavior**
I dont know why  A clear and concise description of what you expected to happen.

**Screenshots**
Only if there's no clear logs, add screenshots to help explain your problem.

**System Information(please complete the following information):**

- Device: Samsung Galaxy S10 5G 
- Android Version: Android 12
- ROM: (AOSP, MIUI, OOS...) Standard, not rooted. 
- App's Version: on F-droid it says 8.0.2

-----------------------------

**Additional Notes**

* If you're on the latest Test version(from the TG-Channel or Matrix-Room) please report there directly, not here.

* If you're on the latest github version:
  
  * Please read the [FAQ](https://github.com/NeoApplications/Neo-Backup/blob/master/FAQ.md) first.
  * Please read all the open Issues. If one does match yours, leave a comment there if there's some extra information you can provide.

* If you're not on the latest github version. Update, then make sure that the bug is still there. If it's go further with reporting.

Thanks for reporting.

**Comment by JohnCGH** [comment]
ROM: (AOSP, MIUI, OOS...) Standard, **not rooted**.

The FAQ did say you need a rooted device...
https://github.com/NeoApplications/Neo-Backup/blob/main/FAQ.md#do-i-need-a-rooted-phone

**Comment by deep-freeze** [comment]
This is true, but I think better feedback to the user in the form of a clear message than a crash would improve the user experience.

**Comment by deep-freeze** [comment]
I would say that it is quite sufficient for NeoBackup to try to get root privileges and then display an error message if this did not work. If the user actively hides root privileges from NeoBackup, it is their own fault.
