### ISSUE TITLE
[Feature Request] Installation Source set optionally

### ISSUE THREAD

**Issue by MichaelZ4714** [NeoApplications/Neo-Backup#582]
**Is your feature request related to a problem? Please describe it.**
It is quite important for me that the backup software also sets during restore in the operating system that the application was installed by Google Play (mark as installed from). Some applications refuse to run if this is not marked. So it is not only a display property in Settings Apps (as mentioned in [https://github.com/NeoApplications/Neo-Backup/issues/516#issuecomment-1086899484](url) but an important property for the health of an application.

**Describe the primary solution**
This could be optionally activated in the options. It could be active for all restores in that run and does not need an interface to select per application to be set on restore.

**Describe alternative solutions, if any**
Another solution would be to read the installation source during backup, add it to the properties file, and then restore it.

**Screenshots**

**System Information (please complete the following information):**

- Device: independent
- Android Version: independent
- ROM: (AOSP, MIUI, OOS...)  independent
- App Version: 8.0.2

**Comment by hg42** [comment]
the setting is implemented now, but I think saving and restoring it would be better

**Comment by machiav3lli** [comment]
Please be aware that starting A13 apps installed using other methods than session installer would have many permission restrictions (and the tendency is that A14 would bring more of those) which render the option (and all its variants) useless. To be able to reproduce your wished result, Google has to open an API that allows other apps to "send" packages to Play Store for it to install.

**Comment by Asmageddon** [comment]
> Please be aware that starting A13 apps installed using other methods than session installer would have many permission restrictions (and the tendency is that A14 would bring more of those) which render the option (and all its variants) useless.

What does this actually mean for the users of NeoBackup intending to restore apps on A13? Will I run into problems if I restore my apps with NB?

**Comment by machiav3lli** [comment]
@Asmageddon nope, session installer only restricts the installation process, so that NB can't mock other apps (e.g. Play Store) as installer of the restored app.

**Comment by MichaelZ4714** [comment]
I can confirm that it works on my Android 12 device. There was an update today of my banking app, installed through an alternative app store (Aurora Store). The app refused to start because of installed by untrusted store. I made a backup with Neo and restored it with setting the source to com.android.vending. After that the app started fine. Now I don't have to use Titanium Backup for this any more, wouldn't work with split apks anyhow.
Many thanks, Michael
