### ISSUE TITLE
[Feature Request] Save User Data not only for User 0

### ISSUE THREAD

**Issue by MichaelZ4714** [NeoApplications/Neo-Backup#583]
**Is your feature request related to a problem? Please describe it.**
On my device I have an additional user (work profile, in my case its user 11). This data is not included in backup. I also need that data.
Neo Backup crashes on start when copied to work profile using Insular([https://f-droid.org/en/packages/com.oasisfeng.island.fdroid/](url), fork of Island).

**Describe the primary solution**
Tha data of additional users is also put into the backup. It is automatically restored if that user number exists on that device, otherwise a warning will be shown.

**Describe alternative solutions, if any**
The backup of additional users could be controlled in the options.

**Screenshots**

**System Information (please complete the following information):**

- Device: independent
- Android Version: independent
- ROM: (AOSP, MIUI, OOS...)  independent
- App Version: 8.0.2

**Comment by machiav3lli** [comment]
Further discussion at #795
