### ISSUE TITLE
[Bug] code_cache directory is not chown'd when restoring a backup containing cache, causing data loss on reboot

### ISSUE THREAD

**Issue by chenxiaolong** [NeoApplications/Neo-Backup#589]
**Description**

When a backup is taken with cache *not* excluded, upon restoring the backup, the `/data/data/<package>/code_cache` directory is not chown'd. At least on Android 13, when this directory is not owned by the correct user, the app data is cleared after a reboot.

**Steps To Reproduce**

1. Uncheck `Exclude app's cache`
2. Back up an app
3. Reinstall the app so that it has a different UID
4. Restore the app data
5. Run `ls -lZ /data/data/<package>` to see that `code_cache` has the old/original UID/GID, while everything else (correctly) has the new UID/GID
6. Reboot
7. Android cleared the app's data

**Expected behavior**

Ideally, Neo Backup should ensure that the ownership of `code_cache` is correct. I noticed this was excluded intentionally so I'm not sure if fixing this bug would cause other bugs: 

https://github.com/NeoApplications/Neo-Backup/blob/d8acc3ebe3d6ceeb2954a05ca36356327ecba451/app/src/main/java/com/machiav3lli/backup/actions/RestoreAppAction.kt#L670

**Screenshots**

Using `com.brave.browser` as an example, this is the result after restoring the app's data. The UID from the original backup was 10214 and the new UID is 10251.

```
raven:/ # ls -lZ /data/data/com.brave.browser/
total 24
drwx------ 20 u0_a251 u0_a251       u:object_r:app_data_file:s0:c251,c256,c512,c768  3452 2022-07-03 09:29 app_chrome
drwxrwx--x  3 u0_a251 u0_a251       u:object_r:app_data_file:s0:c251,c256,c512,c768  3452 2022-07-01 16:55 app_tabs
drwxrwx--x  2 u0_a251 u0_a251       u:object_r:app_data_file:s0:c251,c256,c512,c768  3452 2022-07-02 22:19 app_textures
drwxrwx--x  2 u0_a251 u0_a251       u:object_r:app_data_file:s0:c251,c256,c512,c768  3452 2022-07-02 11:57 app_top_sites
drwxrws--x  2 u0_a214 u0_a214_cache u:object_r:app_data_file:s0:c251,c256,c512,c768  3452 2022-07-01 22:39 code_cache
drwxrwx--x  2 u0_a251 u0_a251       u:object_r:app_data_file:s0:c251,c256,c512,c768  3452 2022-07-01 16:55 databases
drwxrwx--x  4 u0_a251 u0_a251       u:object_r:app_data_file:s0:c251,c256,c512,c768  3452 2022-07-02 12:37 files
drwxrwx--x  2 u0_a251 u0_a251       u:object_r:app_data_file:s0:c251,c256,c512,c768  3452 2022-07-03 09:50 shared_prefs
```

**System Information(please complete the following information):**

- Device: Google Pixel 6 Pro
- Android Version: Android 13 Beta 3.2
- ROM: Stock (Pixel)
- App's Version: Compiled from source from commit d8acc3ebe3d6ceeb2954a05ca36356327ecba451

**Comment by machiav3lli** [comment]
Oh that's a good report, will (try to) fix in a sec.

**Comment by hg42** [comment]
right, I already noticed/commented/"todo"ed it:

```
            //TODO hg42 directories we exclude would keep their uidgidcon from before
            //TODO hg42 this doesn't seem to be correct, unless the apk instlal would manage updating uidgidcon
```

especially if we don't install an apk (I think I just had this case, LOL, should read my own comments)

**Comment by hg42** [comment]
hmm, apart from my comment, I thought we wipe the directory and the caches should not be there.
Even with apk installation it would be wiped when restoring the data.

tarcmd:

```
targetDir.mkdirs()  // in case it doesn't exist
wipeDirectory(
    targetDir.absolutePath,
    DATA_EXCLUDED_BASENAMES
)
```

tarapi is more complicated:

```
if (OABX.prefFlag(PREFS_RESTOREAVOIDTEMPCOPY, true)) {
    // clear the data from the final directory
    wipeDirectory(
        targetPath,
        DATA_EXCLUDED_BASENAMES
    )
    archiveStream.suUnpackTo(RootFile(targetPath), forceOldVersion)
} else {
    // Create a temporary directory in OABX's cache directory and uncompress the data into it
    //File(cachePath, "restore_${UUID.randomUUID()}").also { it.mkdirs() }.let {
    Files.createTempDirectory(cachePath?.toPath(), "restore_")?.toFile()?.let {
        tempDir = RootFile(it)
        archiveStream.suUnpackTo(tempDir!!, forceOldVersion)
        // clear the data from the final directory
        wipeDirectory(
            targetPath,
            DATA_EXCLUDED_BASENAMES
        )
        // Move all the extracted data into the target directory
        val command =
            "$utilBoxQ mv -f ${quote(tempDir.toString())}/* ${quote(targetPath)}/"
        runAsRoot(command)
    } ?: throw IOException("Could not create temporary directory $targetPath")
}
```

Without a temporary directory it's also wiped.
With a temporary directory it's the same because the target is wiped and then the extracted data is moved inside (which should be the same like extracting directly).
This is why I didn't keep an eye on this.

The cache directories only exist if included in the backup.
This is exactly what you wrote above.

I never thought, it would be a good idea to backup the cache...
May be this depends on the definition of a cache.
But the fix is correct for that case (mostly).

The only problem is that the permissions are "fixed" by copying them from the data directory (the one that is wiped).

In the example the code_cache will get teh group `u0_a251` instead of `u0_a251_cache`. Not sure how to handle that. Should we create an exception? are all code_cache like this one? I cannot be sure on my devices/emulators, because I already have wrong restores on all of them...

Btw. it's interesting that the selinux context contains `c251`, I would think it should have `c214` instead. Who changed that?

**Comment by hg42** [comment]
just restored the data of NekoX (my test case which failed before). And it worked now.
Though, I don't have the cache in my backup.
Both cache and code_cache have the `xxx_cache`:
```
drwxrwx--x 2 u0_a671 u0_a671       u:object_r:app_data_file:s0                       4096 2021-11-27 15:46 app_textures
drwx------ 3 u0_a671 u0_a671       u:object_r:app_data_file:s0                       4096 2022-06-29 16:14 app_webview
drwxrws--x 2 u0_a671 u0_a671_cache u:object_r:app_data_file:s0:c159,c258,c512,c768   4096 2022-07-05 19:58 cache
drwxrws--x 2 u0_a671 u0_a671_cache u:object_r:app_data_file:s0:c159,c258,c512,c768   4096 2022-07-05 20:21 code_cache
drwxrwx--x 2 u0_a671 u0_a671       u:object_r:app_data_file:s0                       4096 2022-01-28 01:46 databases
drwxrwx--x 5 u0_a671 u0_a671       u:object_r:app_data_file:s0                      12288 2022-07-05 20:23 files
drwx------ 2 u0_a671 u0_a671       u:object_r:app_data_file:s0                       4096 2022-01-28 01:46 languages
drwxrwx--x 2 u0_a671 u0_a671       u:object_r:app_data_file:s0                       4096 2022-07-05 20:23 shared_prefs
```

I'm a bit surprised, because my test case is without cache.
This would mean, the difference is in the `DATA_EXCLUDED_BASENAMES`, but there is neither a `lib` nor a `no_backup` directory in my test case.

**Comment by chenxiaolong** [comment]
> In the example the code_cache will get teh group `u0_a251` instead of `u0_a251_cache`. Not sure how to handle that. Should we create an exception? are all code_cache like this one?

Would it make sense to hardcode that for the `cache` and `code_cache` directories? It appears that's what AOSP's installd does: https://android.googlesource.com/platform/frameworks/native/+/37ebee73710cbed9e38a44886f780153f76fe722/cmds/installd/InstalldNativeService.cpp#550

The `cacheGid` parameter comes from the result of a `multiuser_get_cache_gid` call, which is defined as: https://android.googlesource.com/platform/system/core/+/827389c9a495bda4440477a00c7ce56935ad7def/libcutils/multiuser.cpp#51

**Comment by hg42** [comment]
I'm not the main developer, but generally I would like to avoid hardcoded stuff as muich as possible.
Android versions might change the strategy and they might change the constants.

I would prefer to either ask the system (use system functions, or properties or similar), so it adapts automatically to the running system and it's constants.

Or may be look at NB directories to determine which directories to change and how. While this strategy is dirty af, it would at least reduce the version dependency.
It assumes less than hardcoding.

If doing this or hardcoding, we should create a module for dirty hacks (may be called like this), that offers functions and constants and can handle version dependencies.
We already have such a constant I think, the PIDs below 1000 are handled as system processes.

Is there a module, that gives us the constants from the C-space? or can we call those functions? (I'm not a java guy as you see).
In my spheres it's usually called `ffi` (=foreign function interface) or similar.

Btw. there are more such constants for _external_ and _shared_...

```
#define AID_APP_START        10000 /* first app user */
#define AID_CACHE_GID_START  20000 /* start of gids for apps to mark cached data */
#define AID_EXT_GID_START    30000 /* start of gids for apps to mark external data */
#define AID_SHARED_GID_START 50000 /* start of gids for apps in each user to share */
```
did anyone see those somewhere?

**Comment by chenxiaolong** [comment]
> #define AID_EXT_GID_START    30000 /* start of gids for apps to mark external data */

Specifically for this one, I know NB does not chmod the external directory. However, Android seems to chown the directory on it's very quick after a restore. Sometimes, it's done before I even have a chance to run `ls -lZ`.

**Comment by hg42** [comment]
right, and the external directory is usually group sdcard_rw (1015?)

**Comment by hg42** [comment]
I found this in java space:

https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/os/UserHandle.java

It looks like the constants are defined in Process (also that first user PID).
Not sure if we have access to such functions...

**Comment by chenxiaolong** [comment]
> right, and the external directory is usually group sdcard_rw (1015?)

On my device (Android 13), the group for the external directory is `ext_data_rw` (1078).

**Comment by hg42** [comment]
wow, A13?
That's why I would like to avoid hardcoding if possible.

**Comment by chenxiaolong** [comment]
> I found this in java space:
>
> https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/os/UserHandle.java
>
> It looks like the constants are defined in Process (also that first user PID).
> Not sure if we have access to such functions...

Nice find. It should be possible to access those via Java reflection. They're marked as `@UnsupportedAppUsage`, but Android itself does not block access to them. (Google Play Store's upload scan does block them, but NB isn't published there anyway.)

**Comment by hg42** [comment]
well, there are at least _some_ UIDs in android.os.Process (using AS to jump to the class)  but not those we want:

```
    public static final int BLUETOOTH_UID = 1002;
    public static final int FIRST_APPLICATION_UID = 10000;
    public static final int INVALID_UID = -1;
    public static final int LAST_APPLICATION_UID = 19999;
    public static final int PHONE_UID = 1001;
    public static final int ROOT_UID = 0;
    public static final int SHELL_UID = 2000;
    public static final int SIGNAL_KILL = 9;
    public static final int SIGNAL_QUIT = 3;
    public static final int SIGNAL_USR1 = 10;
    public static final int SYSTEM_UID = 1000;
```

**Comment by hg42** [comment]
we can get a `UserHandle` via `myUserHandle()`, but not sure if this helps...

**Comment by hg42** [comment]
> Looks like there's a function on the Java side to get the cache gid

yes, I noticed it, but at least it's not directly accessible (as you said). What we see is something rudimentary.

I think cache and code_cache could be retrieved from the path, getCacheDir() and getCodeCacheDir()

**Comment by chenxiaolong** [comment]
Oh, like call `Context.getCacheDir()`/`Context.getCodeCacheDir()` for NB itself and use that to determine the paths for the restored apps?

**Comment by hg42** [comment]
these variants result in nulls:
```
        //val userHandle = android.os.Process.myUserHandle()
        val userHandle = android.os.UserHandle.getUserHandleForUid(android.os.Process.myUid())
        Timber.i("$userHandle ${userHandle?.javaClass?.enumConstants}")
```

**Comment by hg42** [comment]
> for NB itself

yes, it's also an assumption, so it's also dirty, but less than hardcoding

**Comment by chenxiaolong** [comment]
I think it returns nulls because of `enumConstants` and `UserHandle` is not an `enum`. `javaClass?.declaredFields` may work.

**Comment by hg42** [comment]
may be but UserHandle itself seems to be empty:
`UserHandle{0} null`

**Comment by hg42** [comment]
this was in a test environment... not sure if it's the same

**Comment by chenxiaolong** [comment]
I think that's correct. User ID 0 is the default/primary user on Android. Eg. On my device, 0 is primary and 10 is work profile:
```
raven:/storage/emulated/0/Android/data # pm list users
Users:
        UserInfo{0:Andrew:c13} running
        UserInfo{10: Island :1030} running
```

**Comment by hg42** [comment]
oh, ok... at least I get something with declaredFields...

**Comment by hg42** [comment]
another way could be to use a shell command...if it's somewhere hidden in the system

**Comment by hg42** [comment]
at least the constants are in fields, e.g.
`... public static final int android.os.UserHandle.AID_CACHE_GID_START`
but getCacheAppGid isn't in methods...

that thread is interesting:
https://stackoverflow.com/questions/55970137/bypass-androids-hidden-api-restrictions
but I think it has certainly more dependencies than using hardcoded constants...

**Comment by hg42** [comment]
LOL, when trying to implement something, I noticed that we already have the gid as String.

So it's simply:
```
val gidCache = "${gid}_cache"
```

**Comment by hg42** [comment]
untested, but a trivial change: #590

**Comment by chenxiaolong** [comment]
Thanks! I'll test it out after work today.

**Comment by tokariu** [comment]
Well, this bug SUCKS.
I made a backup yesterday of all apps with cache, then wiped my phone to install a fresh Android 12 upgrade/ROM. I didn't know of any related bugs and was assuming everything is working as before.
Now when I try to restore my app backups, after every boot all app data and settings are suddenly gone again (refering to the problem described in the opening post).
It is my daily driver phone, I'm in a hurry to get things working again and I have only the neobackups with cache from yesterday. How am I supposed to get this working in a hurry? 
I can't wait until f-droid updates to a fixed version.

**Comment by JohnCGH** [comment]
I would try:
1) To restore one app at a time and not batch.
2) Uncheck the "cache" option when restoring - App's should be able to run just fine if their cache is cleared.

**Comment by tokariu** [comment]
> I would try:
> 
>     1. To restore one app at a time and not batch.
> 
>     2. Uncheck the "cache" option when restoring - App's should be able to run just fine if their cache is cleared.

thanks for a helping hand. However, there is no such option "uncheck the 'cache' option" when restoring.. If I manually try to restore an app I only get these options:

App:
✅ APK
✅ Data
✅ Protected Device-Data
✅ External Data

that's it. no separate cache checkbox option. I guess it's bundled with "Data".

Any other idea?

**Comment by chenxiaolong** [comment]
If you don't want to compile from source yourself, here's a debug build compiled from PR #590 (commit 4afc0e184a4515b38f5269443542f743385d9eb9).
[pr590-4afc0e184a4515b38f5269443542f743385d9eb9.zip](https://github.com/NeoApplications/Neo-Backup/files/9072698/pr590-4afc0e184a4515b38f5269443542f743385d9eb9.zip)

I would not suggest using this debug build for anything more than getting your system running again.

**Comment by tokariu** [comment]
@chenxiaolong thanks for the rapid response, really appreciated! I'll try as you mentioned it! I'll probably upgrade to the next f-droid version afterwards if it's released.
if it's working I'll be back in a minute updating info.

**Comment by tokariu** [comment]
@chenxiaolong Alright, first app restore worked out of the box, data is being kept after reboot. I'm working through the rest of my backup now and see if everything works. 
thanks again for the debug build in this emergency!

**Comment by hg42** [comment]
> thanks for a helping hand. However, there is no such option "uncheck the 'cache' option" when restoring.. If I manually try to restore an app I only get these options:

the cache option is in the settings:

service / exclude app's cache

as far as I see, the option is basically designed to not include the cache into the tar archives on backup.

However, restore with tarcmd (the default) also respects the setting on extraction, so it should work with enabling "exclude app's cache".

newer apk isn't available, yet

**Comment by Valentin-N** [comment]
Is this a good place to ask about chowning `/storage/emulated/0/Android/data/<package_id>`? I noticed for past and current versions of NB that apps restored with NB don't have the current UID for the above path and all its subdirs. I've observed this behavior on Android 11 and 12 (LOS 18.1 and 19.1). I can speculate that the UID after restore is the UID of the original backed up dir which does not match the current app UID. I fixed the problem by manually chowning everything using termux, but it's very tedious and prone to errors.

Another odd thing is that the above path seems to be created by NB even when it did not exist for the original backed up app.

**Comment by hg42** [comment]
actually, there isn't any fiddling with permissions etc. at all for external Android directories.

I guess this is because those directories always were on FAT.

**Comment by hg42** [comment]
basically, we could do the same for the external directories as for the internal.

This currently works by copying the permissions from the directory created by the system when installing the app or using the existing directory attributes if the apks are not restored.

With those external directories there will be some more things to solve:

* we need a detection (or may be exception handler), if the directory is on a file system with permission handling (and selinux?)
* I think to remember the directory is not created by default when installing an app, so there is no directory to copy the permissions from
* which means we need to get the permissions from somewhere else. We could take the known app uid, but selinux context may be difficult
* I need to create an environment to test or debug this (format internal storage with a file system that handles permissions)

> Another odd thing is that the above path seems to be created by NB even when it did not exist for the original backed up app

with the tarcmd implementation the directory is packed into the tar even if it's empty.
Not sure what happens if no directory exists. It's probably an empty tar then.
("not sure" means, I have to investigate the code)

The reason for saving the empty directory or an empty tar is, that if the directory was empty on backup, it should be empty after a restore,
and if it's non-existent, it should be deleted on restore.

The older implementation (I call it tarapi, tar via a library using an API) would not create a backup tar and would not touch the directory on restore, so it would not be cleared or deleted on restore.

I'm not sure what exactly happens on restore, if the directory is backed up, but wasn't existing.
At least it worked when creating the implementation, but may be the permission correction code or other corrections changed something.
With a FAT file system you don't see how it behaves.

**Comment by hg42** [comment]
@Valentin-N 

my current solution is this:
```
val uidgidcon = try {
    shell.suGetOwnerGroupContext(extractTo)
} catch(e: Throwable) {
    val fromParent = shell.suGetOwnerGroupContext(File(extractTo).parent!!)
    val fromData = shell.suGetOwnerGroupContext(app.dataPath)
    arrayOf(
        fromData[0],    // user from app
        fromParent[1],  // group is independent of app
        fromParent[2]   // context is independent of app //TODO hg42 really? some seem to be restricted to app? or should at least...
                        // note: restorecon does not work, because it sets storage_file instead of media_rw_data_file
                        // otherwise "?" could be returned here
        )
}
```
in short:
* if the data directory (e.g. `Android/data/the.package.name`) exists, the user/context is copied from there
* otherwise
  * user is from what we retrieved from the package manager
  * group and context are retrieved from the parent directory (where the data directory will be created, e.g. `Android/data`)

this is because the group for external data is not the app group, but some more general group, and it's different for data/obb/media and may be even for different ROMs or Android versions.

If you have access to the Telegram group, please test the pumpkin apk.

I noticed that the selinux context are not all the same in the original directory. It may not be exactly correct to set all the contents to the selinux context of the parent.
I'm not sure what happens, if the selinux context doesn't contain the user related labels.

**Comment by ildar** [comment]
> > thanks for a helping hand. However, there is no such option "uncheck the 'cache' option" when restoring.. If I manually try to restore an app I only get these options:
> 
> the cache option is in the settings:
> 
> service / exclude app's cache
> 
> as far as I see, the option is basically designed to not include the cache into the tar archives on backup.

@hg42 , I see the option is by default to SAVE the app cache.

**Comment by hg42** [comment]
@ildar yes...this was already existent when I started contributing...

not sure what is the current reasoning
