### ISSUE TITLE
[Feature Request] Ability to store backup configurations

### ISSUE THREAD

**Issue by barackenkumpel** [NeoApplications/Neo-Backup#595]
**Is your feature request related to a problem? Please describe it.**
I have some apps whose data I don't want to backup (because it's to big and downloadable (not personal data)) and I have to manually uncheck the data buttons everytime I make a backup.

**Approximate design suggestion**
The selection could be similar to the backup/restore page where you choose the apps and what to backup. Next to the Blocklist button there could be a button to open a drop down menu (or something similar) to select a configuration to either backup or restore depending on which page you are.

**Comment by hg42** [comment]
for grouping app lists / filtered lists with configurations, you can use schedules, just don't enable them (that's for scheduling them automatically).
Then you can start them manually.
In the future there will be something to filter by tags.

**Comment by barackenkumpel** [comment]
Yes, I see. Thank you
