### ISSUE TITLE
Restore Feature of a Separate Icon for Diabled Apps

### ISSUE THREAD

**Issue by landry314** [NeoApplications/Neo-Backup#597]
It used to be that Disabled apps in the Main list had greyed out icons to the right to show they are disabled. Now they are all orange or blue circles regardless of if they are disabled.

I found this useful to see which apps were disabled so I could quickly scan this list to see if I needed to enable them or disable them. I know I can filter for them but still, the quick look was useful while looking for apps in the "All apps" filter to see if I want to disable them.

Why was this useful differentiation removed?

**Comment by JohnCGH** [comment]
+1

**Comment by landry314** [comment]
> I just noticed that this smaller icon on the right side is a duplicate of the main icon that will appear as a generic android icon if an app is disabled, so I guess the small icon on the right is not really needed.

i do not see this. i see the disabled apps with normal icons and no discernible difference between active apps.

**Comment by JohnCGH** [comment]
DOH! I am using version 7, so that would explain that!

Wow to go from having two icons to visually indicate an app is disabled in v7 (the main and smaller right icon) to no visual indication in v8 is not good.
