### ISSUE TITLE
[Bug] Dialog indicating that an app has been updated is way TOO BIG

### ISSUE THREAD

**Issue by JohnCGH** [NeoApplications/Neo-Backup#608]
**Description**
If an app has a backup in Neobackup, then I install an update for that app from the playstore, the next time I run neobackup, it will display this crazy big 1/2 screen dialog telling me that an app was updated.

**Steps To Reproduce**

1. Backup an app using neobackup
2. Install an update for that app from the playstore
3. Rerun neobackup and it will display this huge dialog which then hinders my ability to use the app until I perform that backup because I can only see two apps in the app list at a time when this dialog is being displayed.

**Screenshots**
![TooBugUpdateDialog](https://user-images.githubusercontent.com/18239066/180610618-75cdf992-5c73-404b-a366-a6adf731105a.png)

**System Information(please complete the following information):**

- Device: Pixel 4a
- Android Version: 10 (stock)
- App's Version: 8.1.0

**Comment by machiav3lli** [comment]
Hm, I think I'll try to take more consideration to low dpis

**Comment by JohnCGH** [comment]
Why not have the dialog simply be two rows:

1) The first (top) row will display all the app icons of the apps that were detected as being "updated"
2) And the second (bottom) row be the "Backup all Updated Apps" button.

This way you won't need to display the text "x updated app" which will cause the dialog to grow vertically like a totem pole because it's trying to fit in a narrow vertical column to the right of the button. By having two rows and NOT displaying the text "x updated apps"), everything will fit nicely in a compact two-row dialog.
