### ISSUE TITLE
[Feature Request] No Root Backups

### ISSUE THREAD

**Issue by maverick74** [NeoApplications/Neo-Backup#610]
This is related to #86 but not the same.

There are certain "areas" that can Backed-up that do not need Root.

For example I, personally, only want to backup Contacts, SMS and MMS.

As of now I can't do this using NB because as soon as it starts it asks for root.

My suggestion is that, for unrooted devices, it should allow to perform the backups that do not require root!

**Comment by machiav3lli** [comment]
Nope, I don't have enough resources to do such differentiation and carry this on with further development, for the mentioned specific data there's already many specialized FOSS solutions.

**Comment by maverick74** [comment]
@machiav3lli could you please share which FOSS solutions you refer too?

I just can't find any that does Contacts+SMS+MMS in the FOSS world.......

About the feature request: I always had the feeling it was a long shot... But I had to try. Ahah

**Comment by machiav3lli** [comment]
@maverick74 here you go (both seems to be maintained):
- https://github.com/tmo1/sms-ie
- https://gitlab.com/axet/android-sms-gate

**Comment by machiav3lli** [comment]
For contacts/calendar/tasks I suggest using DecSync (a multi-platform technology): https://www.f-droid.org/de/packages/org.decsync.cc/

**Comment by maverick74** [comment]
That kills the all-in-one intention :)

But will take a look at it, anyway.

Thank you soo much for sharing these links. Will look at them closely!

**Comment by 07416** [comment]
Sharing from another issue:

[QKSMS](https://github.com/moezbhatti/qksms) can import & export SMS messages without root.
I've understood that you can change your default SMS app after the process has been completed, if you so desire.

At least the LineageOS contacts app `com.android.contacts` supports import & export (.vcf file).

**Comment by MrEngineerMind** [comment]
> [QKSMS]I've understood that you can change your default SMS app after the process has been completed, if you so desire.

Having to remember to manually switch which apps have access to SMS database is not a good UX.

**Comment by 07416** [comment]
> > [QKSMS]I've understood that you can change your default SMS app after the process has been completed, if you so desire.
> 
> Having to remember to manually switch which apps have access to SMS database is not a good UX.

I've only used the app when changing phones or before wiping all data — admittedly not a process to be used often.
