### ISSUE TITLE
Says phone isn't rooted, even though it is

### ISSUE THREAD

**Issue by philipm92** [NeoApplications/Neo-Backup#615]
Hi,

my phone is rooted, but when I open the App it tells me that my phone is not rooted, so I cannot use the App.

- Device: Samsung Galaxy S10 (SM-G973F)
- Android Version/ROM: LineageOS 18.1-20220401-microG-beyond1lte
- App's Version: 8.1.0

Thanks for the help :)!

**Comment by machiav3lli** [comment]
Maybe you rejected giving root permission? Check magisk to be sure

**Comment by philipm92** [comment]
Hi. 
I don't have magisk installed.

**Comment by machiav3lli** [comment]
What root solution then? Some user reported issues with root-solution supplied with GSIs, which was solved by installed magisk.

**Comment by philipm92** [comment]
I rooted it regulary and then flashed LineageOS with Heimdall or Odin

**Comment by machiav3lli** [comment]
Ok, I guess you're mixing root with unlocking bootloader.
You don't have root right now, and you need to flash magisk if you'd like to have root and i.a. use NB.

**Comment by philipm92** [comment]
Yeah I just noticed, my bad, sorry about that. With a lot of tutorials rooting and bootloader come up at the same time, so I simply assumed I did that as well.

Since I should be updating to 19.1 soon, I might give rooting with magisk a try if it isn't too much of a hassle.

Thanks for the response, and you can delete this thread if you'd like.

**Comment by machiav3lli** [comment]
No issue at all, happy rooting!
