### ISSUE TITLE
[Bug] Missing schedule after update

### ISSUE THREAD

**Issue by uok** [NeoApplications/Neo-Backup#616]
Thanks for this great app!

Recently I updated to v8.1.0 and backup stopped working because tab "scheduling" is empty.
How can I get back the settings? Is Neo Backup included in the regular backups?
Or should I revert to older version?

**Comment by machiav3lli** [comment]
I forgot to add to changelog that database will get wiped, NB hides itself from the backup list, so you wouldn't find a backup if its data. For this time, you don't have a way to retrieve the settings/schedules, except if you've exported the schedules earlier using the tool in settings/tools

**Comment by uok** [comment]
That's bad because usually users read changelog after upgrade to see what's new.
How can I include Neo Backup in regular backups? This would be a simple solution for scenarios like this.

**Comment by machiav3lli** [comment]
It's no use to backup NB if you use an encryption password. There's already in tools>import/export schedules option to "backup" your defined schedules (will be kept wihtin the backups folder) and get them back when needed.
