### ISSUE TITLE
[Feature Request] Back up device-protected data/external data/obb files/media files on a per-app basis

### ISSUE THREAD

**Issue by xKippi** [NeoApplications/Neo-Backup#620]
I would like to backup those things for most apps. However, some apps have huuuge files in the external data directory (OsmAnd Maps for example).

So it would be nice to have the "Back up device-protected data/external data/obb files/media" settings on a per-app basis.

- Device: herolte
- Android Version: 10
- ROM: /e/OS  
- App Version: 8.1.0

**Comment by machiav3lli** [comment]
As you possibly see, there's no space for such easy picks in the list layout. You have two options:

- Use schedules to define different set of apps having the different default selection
- or use the main page and do single backups.

For now, there's no easy solution for all the possible complex use-cases and there'll never be, so users have to show some flexibility and adapt, using the options the app already provide.
