### ISSUE TITLE
[Bug] 8.1.1 broke theming

### ISSUE THREAD

**Issue by opusforlife2** [NeoApplications/Neo-Backup#627]
**Description**

The theme related settings have stopped working:
- There is a single theme set after the update, different from the user-selected theme.
- In the theme menu, selecting any theme doesn't work. Also, the radio buttons function like check boxes instead.
- The overall theme is stuck on "Light", but the app is dark, so the settings UI likely doesn't reflect the active theme.

**Steps To Reproduce**

1. Update from 8.1.0 to 8.1.1.
2. Notice the theme changed from your selection.
3. Try changing any of the theme settings.

**System Information(please complete the following information):**

- Device: Xiaomi Mi 5
- Android Version: 10
- ROM: LOS 17.1
- App's Version: 8.1.1

**Comment by machiav3lli** [comment]
The automatic reset of theme is to be expected, but the issue you mentioned with selecting a theme is irreproducible on my side…
A more informative step-for-step guide to reproduce including clear declaration of the states: real App Theme, set App Theme and system's theme would eventually help. Thanks!

**Comment by opusforlife2** [comment]
Sigh. Bug vanished, likely upon restarting the app. Maybe it can be reproduced only on the first start after upgrading?

The only evidence left was that the `Theme` was still set to `Light` despite the real theme being `Dark`. Switching around between them fixed that as well. Going back to `Light` correctly applied it.

The radio buttons work fine now as well. The selected `Accent` and `Secondary` colors are applied correctly.
