### ISSUE TITLE
[Bug] Failure Trying to Downgrade an App

### ISSUE THREAD

**Issue by whitedavidp** [NeoApplications/Neo-Backup#632]
**Description**
I could not help but notice that in the settings there is a switch to permit downgrading. I used to be able to do this on older Android but have never been successful on Android 9. So when I saw this I decided to test the function, which I had enabled. Last night, Tasker had been backed up by Neo on my LG V40, Android 9 w/Magisk and there was an update this morning. I installed it and tried to downgrade from last night's Neo backup. I get the error shown in the attached screen shot.

**Steps To Reproduce**

1. Make sure an app has been backed up using Neo.
2. Install update of that app.
3. Make sure downgrading is enabled and then perform restore of that app.
4. Error message as shown in attachment.

**Expected behavior**
Ideally, this would over write the app with the older version in the backup history. However, it does not. The reason for this seems clear to me: I have read that on later Android downgrading had been disabled (except for system apps, if I recall correctly). And this is what I have repeatedly seem trying many various approaches to doing the downgrade (all requiring root). So this may be expected and not a bug. But it seems to me that Neo should be able to detect that this will not work and disable the downgrade option so as to avoid confusion. Of course, if there is some way known to make this work on later Android for user apps, I would love it! Thanks

**Screenshots**
Only if there's no clear logs, add screenshots to help explain your problem.

**System Information(please complete the following information):**

- Device: LG V40
- Android Version: 9
- ROM: (AOSP, MIUI, OOS...)  Stock with Magisk
- App's Version: 8.1.1

-----------------------------

**Additional Notes**

* If you're on the latest Test version(from the TG-Channel or Matrix-Room) please report there directly, not here.

* If you're on the latest github version:
  
  * Please read the [FAQ](https://github.com/NeoApplications/Neo-Backup/blob/master/FAQ.md) first.
  * Please read all the open Issues. If one does match yours, leave a comment there if there's some extra information you can provide.

* If you're not on the latest github version. Update, then make sure that the bug is still there. If it's go further with reporting.

Thanks for reporting.
![Screenshot_20220818-112039](https://user-images.githubusercontent.com/12023355/185473149-d1e693f9-0de2-49c8-879a-dfab11986e99.png)

**Comment by hg42** [comment]
the code should be correct. The `-d` in

```
pm install -d ...
```

should allow downgrading.

However I see in the A13 emulator I have just running, that this option has a
```
(debuggable packages only)
```
attached to it.
I also see this on my A10 ROM.

**Comment by MrEngineerMind** [comment]
I don't know if this info will help, but I just tried downgrading with the "Allow Downgrading" Enabled and it gave me this error:

![Downgrade](https://user-images.githubusercontent.com/18239066/185493635-d03d3179-8e04-4d43-a6bd-0793596413e9.png)

My device is a Pixel 4a running stock A10

**Comment by whitedavidp** [comment]
> the code should be correct. The `-d` in
> 
> ```
> pm install -d ...
> ```
> 
> should allow downgrading.
> 
> However I see in the A13 emulator I have just running, that this option has a
> 
> ```
> (debuggable packages only)
> ```
> 
> attached to it. I also see this on my A10 ROM.

Yes, I think that is the caveat now - debuggable only - I was incorrect when I said system apps. Sorry. This is confirmed, I think, in the source code for pm (supposedly for Android 8):

https://android.googlesource.com/platform/frameworks/base/+/android-8.0.0_r4/cmds/pm/src/com/android/commands/pm/Pm.java

Cheers

**Comment by hg42** [comment]
> I don't know if this info will help, but I just tried downgrading with the "Allow Downgrading" Enabled and it gave me this error:

that seems to be another problem...

it's about the part after the apk install, that restores the permissions that were granted to the restored app at backup time.

**Comment by whitedavidp** [comment]
> > I don't know if this info will help, but I just tried downgrading with the "Allow Downgrading" Enabled and it gave me this error:
> 
> that seems to be another problem...
> 
> it's about the part after the apk install, that restores the permissions that were granted to the restored app at backup time.

Yes, I can see that. I see a Restore with all permissions setting in Neo. Have not enabled/tried that yet. But at least with a downgrade, I cannot get that far. Have you tested the permissions restoration on a "normal" restore (ie., a restore to an app that has been manually uninstalled)?

**Comment by hg42** [comment]
> only - I was incorrect when I said system apps
> Sorry

in fact I'm sorry, for some reason I didn't read that part about system apps...

> This is confirmed, I think, in the source code for pm (supposedly for Android 8):
> https://android.googlesource.com/platform/frameworks/base/+/android-8.0.0_r4/cmds/pm/src/com/android/commands/pm/Pm.java

thanks for finding that. Will have a look later.

I think, we should add that restriction to the description of the option.

Or, may be, find a way to work around it.

**Comment by hg42** [comment]
oh, and it doesn't seem to make sense as a global option

**Comment by MrEngineerMind** [comment]
> > I don't know if this info will help, but I just tried downgrading with the "Allow Downgrading" Enabled and it gave me this error:
> 
> that seems to be another problem...
> 
> it's about the part after the apk install, that restores the permissions that were granted to the restored app at backup time.

OK, I will start a new issue for it.

**Comment by hg42** [comment]
> Yes, I can see that. I see a Restore with all permissions setting in Neo. Have not enabled/tried that yet.

restoring **all** permissions is an option of the install command,
restoring them individually creates a command for each permission to grant it.

> But at least with a downgrade, I cannot get that far

yes, your case is that downgrading is only allowed for debug versions

> Have you tested the permissions restoration on a "normal" restore (ie., a restore to an app that has been manually uninstalled)?

his problem is the sdk version of the apk in the backup. sdk22 is quite old.

In general, I think we should probably change our error strategies.
Everything NB does is kind of illegal from the POV of the API or Android system.
So we probably shouldn't be so picky about complaints but be more fault tolerant.

So, some errors could be warnings instead.

We would need a way to communicate those warnings (and errors).

Some ideas based on some former projects:

I think, it should be a hierarchical structure.

It should be grouped by batch/schedule/operation, then grouped by package. So at a first glance you could see the affected packages (together with a short summary of warnings+errors).

Warnings and errors should have short unique names (like WPERM), to create such summar7es, this also simplifies communication, no more translation or lengthy descriptions.

For details you could enter or expand the package. 

The short names could also be counted, so a result of a batch could say something like: WPERM*23, EWRITE*3

such summaries could directly link to a more detailed list

**Comment by whitedavidp** [comment]
So in the case of the SDK error, did the restore actually complete (except for restoration of granted permissions)? If so, I do think this should be considered a warning, not an error.

**Comment by whitedavidp** [comment]
> 
> yes, your case is that downgrading is only allowed for debug versions
> 
So if one wants to "restore" an older version and it is not a debug apk, it seems the best thing is to completely uninstall the current and then restore the older version from Neo? Or maybe uninstall leaving data behind (pm uninstall -k) and then restore apk only?

**Comment by MrEngineerMind** [comment]
> So in the case of the SDK error, did the restore actually complete (except for restoration of granted permissions)? If so, I do think this should be considered a warning, not an error.

If you are directing a questions to me, I started a new bug report on my particular issue here:

https://github.com/NeoApplications/Neo-Backup/issues/633

**Comment by hg42** [comment]
> So in the case of the SDK error, did the restore actually complete (except for restoration of granted permissions)? If so, I do think this should be considered a warning, not an error.

my assumption, that that sdk error originated from restoring the permissions (by NB) was wrong, it seems to be an implicit operation of the downgrade, I guess the pm install tries to migrate the runtime  permission to the old apk.

**Comment by hg42** [comment]
> So if one wants to "restore" an older version and it is not a debug apk, it seems the best thing is to completely uninstall the current and then restore the older version from Neo?

yes, at least that's the explicit way, only a user can decide

> Or maybe uninstall leaving data behind (pm uninstall -k) and then restore apk only?

this may be a possible solution for handling downgrading automatically
