### ISSUE TITLE
Instagram issue: You've Been Logged Out Please log back in.

### ISSUE THREAD

**Issue by TruongTuyen** [NeoApplications/Neo-Backup#634]
Thank you for your awesome app.

I'm getting an issue when trying to restore Instagram backup with the message: You've Been Logged Out. Please log back in. Does anyone have any solution for this issue?

**Steps To Reproduce**
1. Backup Instagram
2. In Apps -> Instagram -> Storage -> Clear Data.
3. Restore Instgram.
4. Launch Instagram and got this message.

Thanks

**Comment by MrEngineerMind** [comment]
This is a known problem:

- Apps which use android's keystore to identify users e.g. Signal, Element.

**Comment by TruongTuyen** [comment]
@MrEngineerMind Do you have any way for this issue? I have 5 Instagram accounts. I'm finding a way to backup and restore each of them with full "logged in".

**Comment by MrEngineerMind** [comment]
From what I understand that login data is a location (or type of data) that can not be backed up (possibly due to encryption).

**Comment by hg42** [comment]
it's usually a secret stored in hardware

I think, there are also software implementations, if the hardware doesn't exist.

as far as I understand, this binds the secret to the device and to the ROM (nit sure if the developer can choose)

even if it's implemented by software, the purpose is to prevent copying.

that said, which exact data is stored in the keystore is up to the developer.
Additionally, it's possible to store only an encryption key, and use it to encrypt other kinds of data. This still means all that data is useless without the key.

I think many apps overuse this. They probably don't want to think about every part of their data, if it could be used to break security.

btw. NB only stores the encryption password in the keystore.
I see other apps that encrypt everything AND store the key in the keystore (as the name seems to suggests).

From my POV, most devs (including me) should think more clearly about which data should be **bound** (or belongs) to which entity (device, system, user profile, app user etc.) and even more, which data should be **locked** to which entities.

**Comment by TruongTuyen** [comment]
@MrEngineerMind , @hg42 Thank for the explanation.

**Comment by machiav3lli** [comment]
@hg42 it binds it not only to the device and rom but also to the installation, so if an app is uninstalled and then reinstalled, it'll be using a different key (or set of keys) from the first installation. If I recall right, the installation time is used as randomization factor or UID.
