### ISSUE TITLE
[Enhancment] Number of backup revision as number

### ISSUE THREAD

**Issue by mwelsch** [NeoApplications/Neo-Backup#635]
Either display the number selected with the slider or let the user enter a number in a text/number field. 

Why? I can only guess or work with trial & error to know how many revisions are kept. 

![Screenshot_20220819-105543_Neo Backup_1](https://user-images.githubusercontent.com/31733941/185584367-74c33fc7-2f77-4108-9b5c-1cfb498b8103.png)

![Screenshot_20220819-105529_Neo Backup_1](https://user-images.githubusercontent.com/31733941/185583446-6f295dc1-a58a-4859-a4a9-eac2ea7c1645.png)

Anyone able to tell me what I selected in the screenshots without guessing?

**Comment by machiav3lli** [comment]
You'd be able to see on light mode, otherwise it's already fixed for dark mode

**Comment by MrEngineerMind** [comment]
This seems like a duplicate of my other bug report:

https://github.com/NeoApplications/Neo-Backup/issues/623

So I guess that other one can be closed too.
