### ISSUE TITLE
[Feature Request] Too many Backup Details on one line - info is being cropped

### ISSUE THREAD

**Issue by MrEngineerMind** [NeoApplications/Neo-Backup#646]
Neobackup is trying too hard to put a lot of info on a single line on the screen, causing cut-off's and overlapses.

For example, when trying to view the details of a backup (with the system font set to larger than normal), you can barely see the arm64 when a backup has three badges/icons (see screen shot).

I'm worried that if the backup has additional badges or the version number has more digits, I will not be able to see much of the info on that line.

Is there a particular reason why the app is trying to display FOUR different types of info (version, cpu, size, data type icons) on a single line instead of using two lines? 

It would be perfectly fine if you would put the cpu type and size on a separate line so that everything can comfortably fit and be fully visible :)

**Screenshots**
![Screenshot_20220920-211005](https://user-images.githubusercontent.com/18239066/191393460-6004f72c-3b72-45ae-b984-10fccf8729dc.png)

**System Information (please complete the following information):**
- Device:  Pixel 4a
- Android Version: 10
- ROM: (AOSP, MIUI, OOS...)  Stock
- App Version: 8.1.3

**Comment by hg42** [comment]
I guess, small devices / big fonts are uncommon for a usual developer :-)
I suggest wrapping the info texts, but keep the icons separate, also wrap the backup info (version, compression, encryption) which can also become a bit longer
