### ISSUE TITLE
[Feature Request] NOT a fan at all of the new "Chips" app info details :(

### ISSUE THREAD

**Issue by MrEngineerMind** [NeoApplications/Neo-Backup#648]
**Is your feature request related to a problem? Please describe it.**
The new 8.1.3 version introduces a new UI method to display an apps info in separate labels/islands/"chips".

I am definately not a fan of this because it requires me to horizonal scroll to see info that should be display on one screen and viewable at a glance without having to horizonally scroll.

**Describe the primary solution**
Please bring back the original method of displaying all the apps info so it can be view quickly with one glance.

**Screenshots**
![Screenshot_20220920-205114](https://user-images.githubusercontent.com/18239066/191394318-932112d2-3912-4852-afdd-d4111e62264d.png)

**System Information (please complete the following information):**

- Device: Pizel 4a
- Android Version: 10
- ROM: (AOSP, MIUI, OOS...)  Stock
- App Version: 8.1.3

**Comment by hg42** [comment]
I agree basically, though the chips might be ok, but I would wrap them (taking less space than the former solution)

**Comment by MrEngineerMind** [comment]
But even if you wrap them, since the size of each chip will vary depending on it's the contents, it will result in a somewhat no-aligned grid layout similar to the appearance of the "filter" chips which force me to have to spend time to visually search for the info I need because the location of the desired info may be different from app to app. With the previous layout, everything was at the same location regardless of the app's data values and was visually easy to locate in a consistent manner.

Was the reason for the new layout was because the old payout took too much space? If so, I would take the old layout instead or having randomly sized chips.

**Comment by machiav3lli** [comment]
The main reason behind the redesign was the importance/relevancy of the information. Sizes of app, data and cache are less relevant and distract users in some instances, which is why they're order as last in the chips group, while type of app and if it's updated are more critical and shown first.

That said, I wouldn't be maintaining thoroughly two different UIs, this is all that you'll get from this issue.

**Comment by MrEngineerMind** [comment]
The data size is very important to me because it helps me determine if I want to backup an apps data or not (if its too large).
