### ISSUE TITLE
[Feature Request] Please use different color for UI card background or allow users to select color

### ISSUE THREAD

**Issue by MrEngineerMind** [NeoApplications/Neo-Backup#649]
**Is your feature request related to a problem? Please describe it.**
The app is using some non-appealing purple/brown color for the background color of the cards in the UI.

**Describe the primary solution**
Please use a neutral color like gray or allow user's to select the background color of the cards.

**Screenshots**
![Screenshot_20220920-205310](https://user-images.githubusercontent.com/18239066/191394715-fe7d4756-8850-4539-a8bf-e593fb7d55d6.png)

**System Information (please complete the following information):**

- Device: Pizel 4a
- Android Version: 10
- ROM: (AOSP, MIUI, OOS...)  Stock
- App Version: 8.1.3

**Comment by hg42** [comment]
looks like it's already solved (though I don't know how)

**Comment by machiav3lli** [comment]
@hg42 I solved it earlier today. It'll be in the next release
