### ISSUE TITLE
[Bug] App name and ID field margin issue

### ISSUE THREAD

**Issue by aDifferentBook** [NeoApplications/Neo-Backup#651]
**Description**
After opening app details (tapping on app from list) it shows general information about app but it looks like there is a margin issue for app name and ID which is getting cut by half as we can see in screenshot.

**Steps To Reproduce**

1. Open Neo Backup 
2. Tap on any app (to see details)

**Expected behavior**
App name and ID needs to show clearly 

**Screenshots**
![IMG_20220922_225916_406](https://user-images.githubusercontent.com/80353171/191813125-986d9e4f-63f6-4eea-b5c1-4a9f34442c17.jpg)

**System Information(please complete the following information):**

- Device: PocoF1
- Android Version: Android 12.1 (Awaken 2.10)
- ROM: AOSP  
- App's Version: 8.1.2 (F-droid)

**Comment by machiav3lli** [comment]
Already fixed on 8.1.3. Just wait for F-Droid to build & publish it
