### ISSUE TITLE
[Bug] App's icons grayed out

### ISSUE THREAD

**Issue by ourslfs** [NeoApplications/Neo-Backup#652]
**Description**
Some icons grayed out or completely invisible after updating to 8.1.3

**Screenshots**
![Screenshot_20220922-224438.jpg](https://user-images.githubusercontent.com/78319733/191837838-e82202ee-f794-4eae-b7bb-cf3be17c1e3c.jpg)

**System Information(please complete the following information):**

- Device: 
- Android Version: 9
- ROM: Aosp
- App's Version: 8.1.3

-----------------------------

**Comment by machiav3lli** [comment]
Could it be that you have set a low animation ratio in your system's developer settings?

**Comment by ourslfs** [comment]
nope, default values
![Screenshot_20220923-220304_GitHub.png](https://user-images.githubusercontent.com/78319733/192039299-410d397d-a06e-4c0f-b7ae-916d1086f188.png)

**Comment by hg42** [comment]
when the settings had a dark red background, I noticed, that the background faded into gray at the top (permanent).
May this be somehow related?
Though this one looks more like fading into transparency (not gray) and only the icons.

**Comment by hg42** [comment]
when the settings had a dark red background, I noticed, that the background faded into gray at the top (permanent).
May this be somehow related?
Though this one looks more like fading into transparency (not gray) and only the icons.

**Comment by machiav3lli** [comment]
@hg42 nope, the prefs gradual is intended and still applies whatever the primary color is.

The main change I did considering the icons lately is adding crossfade to the loader, maybe it has some bugs on older Android versions?!

**Comment by bdantas** [comment]
I am on LineageOS 16 and am also affected by this. The ones that are grayed out are the ones that, when scrolling through list of apps, start out as a little android robot on an orange background before the app's actual icon loads. When the actual icon loads, it is very dark and difficult to see.

**Comment by ourslfs** [comment]
seems to be fixed with latest release

**Comment by bdantas** [comment]
Hi, ourslfs. FWIW I'm still affected by this bug in the latest stable version (8.2.5).

**Comment by ourslfs** [comment]
@bdantas 8.3.0 is the latest

**Comment by bdantas** [comment]
Oops. I refreshed repositories on F-Droid and 8.2.5 was the latest version. I installed 8.3.0 from github and can confirm that the bug is gone.

**Comment by machiav3lli** [comment]
@bdantas F-Droid take a while till they update an app (mostly up to one week). You may use izzy-on-droid's repo to update directly (same as the GH builds).
