### ISSUE TITLE
[Feature Request] Show error if encryption passphrase wasn't confirmed properly

### ISSUE THREAD

**Issue by Zulgrib** [NeoApplications/Neo-Backup#654]
**Is your feature request related to a problem? Please describe it.**
When encrypting backups, one could write something completely different in the confirmation field for the passphrase and don't see any error displayed.

**Describe the primary solution**
Force the user to re-write the passphrase or disable encryption if both values aren't identical

**System Information (please complete the following information):**

- Device: Xperia 5
- Android Version: 11 
- ROM: (AOSP, MIUI, OOS...)  
- App Version: 8.1.2

**Additional Notes**
 Asked on Matrix if intentional and checked if an issue already exist for this before opening the suggestion.
Currently unclear if the backup would fail, if the backup will be made without encryption or if the confirmation field is just a dummy at this time.

**Comment by hg42** [comment]
it's rewritten now to handle all in the password dialog
