### ISSUE TITLE
[Feature Request] Restore: Selection of back revision 

### ISSUE THREAD

**Issue by jochen-01** [NeoApplications/Neo-Backup#662]
**Description**

I've set number of backup revisions to 5.
When trying to restore I cannot select, which revision to restore.

I made sure that in fact more than one revision has been backed up:
List has: Oct, 13, 2022 **3**
Backup location shows 3 subdirs below package name with backups.

**System Information (please complete the following information):**

- Device: HTC U11 (rooted)
- Android Version: 8
- ROM: (AOSP, MIUI, OOS...)  stock
- App Version: 8.1.3

**Comment by machiav3lli** [comment]
Batch restore isn't designed to be fine-tuned that much. From AppSheet (in Home) you can restore directly your preferred  revision

**Comment by jochen-01** [comment]
Thank you for clarification. Please take it as a feature request. I think, it is useful, if one can select the backup revision in batch restore.
