### ISSUE TITLE
[Feature Request] Please add space between name and value of App info Chips

### ISSUE THREAD

**Issue by MrEngineerMind** [NeoApplications/Neo-Backup#668]
**Is your feature request related to a problem? Please describe it.**
The new app info chips display both the chip value name and it's value after a colon - for example "App Size:122 MB" but by placing both text items right next to each other, it visually appears cramped and not easy to see the value part of the chip.

**Describe the primary solution**
Please add a space between the chip name and it's value.

For example, please display it as "App Size: 122 MB" (with a space between "Size:" and the "122 MB".

**Screenshots**
![addspeace](https://user-images.githubusercontent.com/18239066/197340505-5c3907a4-8e10-401f-847b-ee0b116bedfc.png)

**Comment by wviana** [comment]
Took a look around. It probably could be achieved by some changes in this file. As I'm understanding it suggests that those that has : should have a blank separator between label and value. 

https://github.com/NeoApplications/Neo-Backup/blob/main/app/src/main/java/com/machiav3lli/backup/ui/compose/recycler/Recyclers.kt

**Comment by MrEngineerMind** [comment]
Yes :)

**Comment by hg42** [comment]
No :)

the chips don't manipulate the chip.text

it's set in `Package.infoChips()`
in `app/src/main/java/com/machiav3lli/backup/utils/ItemUtils.kt`

I added a space for all three...
