### ISSUE TITLE
[Bug] No themed icon on A12

### ISSUE THREAD

**Issue by morning-paradigm** [NeoApplications/Neo-Backup#671]
**Description**
8.2.0 changelog states `Add: Support for themed icon on A13`. Themed icons should work on A12 too, but it's not the case with NeoBackup.
For example, Shazam has recently added support for themed icon and it works on my A12 ROM (downgrading the app confirms it's app-based, and not provided by the launcher).
Thus I don't see why it shouldn't work the same on A12 for any of the NeoApplications.

**Steps To Reproduce**

1. Update to 8.2.0
2. No themed icon on A12

**Expected behavior**
Self-explanatory.

**Screenshots**
Self-explanatory.

**System Information:**

- Device: OnePlus 6T
- Android Version: 12
- ROM: crDroid 8.9
- App's Version: 8.2.0

**Comment by machiav3lli** [comment]
Nope, system-based themed icons are only supported starting A13, I'm not interested in investing time backporting system features.

If there's someone keen to do so he/she can contribute it..

**Comment by morning-paradigm** [comment]
I see, I guess I was misinformed. Sorry.

I'm not a coder, so I can't contribute, but for anyone interested, there's quite a few open source apps that have working themed icons on A12 (AnkiDroid, Simple Gallery, KeePassDX, Syncthing, AuroraDroid to name a few), so you might look into those.
