### ISSUE TITLE
[Feature Request] Restore of uninstalled apps

### ISSUE THREAD

**Issue by jochen-01** [NeoApplications/Neo-Backup#675]
**Is your feature request related to a problem? Please describe it.**

I noticed that it's not possible to restore apps which has been uninstalled after backup up. Sometimes a loved old app is not longer available in the play store. Restoring from backup makes further usage possible.

**Comment by MrEngineerMind** [comment]
You should be able to restore an app that was uninstalled, so either the backup or restore was not done correctly.

What error message do you get?

Does the app not restore at all, or does the app restore but all the data is missing?

**Comment by jochen-01** [comment]
I re-checked it, you are right. Even uninstalled apps can be restored that way.
Sorry for the hassle.
