### ISSUE TITLE
[Feature Request] Show info tooltip when holding buttons

### ISSUE THREAD

**Issue by larena1** [NeoApplications/Neo-Backup#677]
**Is your feature request related to a problem? Please describe it.**
![Screenshot_20221031-203807_Neo Backup~2](https://user-images.githubusercontent.com/60823161/199096431-5ba5b967-31d4-432a-8507-b618a5715833.png)

Especially for new users, the meaning of the buttons isn't always clear. I've seen other apps show an info tooltip with a textual representation of the action behind it when tapping and holding buttons.

Also, a button with a cog as icon that leads to the app's settings would be great. 

**Describe the primary solution**
A clear and concise description of what you want to happen. You can also list it in steps.

**Describe alternative solutions, if any**

**Screenshots**
If you're willing to add demonstrative screenshots, you're welcome to do so.

**System Information (please complete the following information):**

- Device: 
- Android Version: 
- ROM: (AOSP, MIUI, OOS...)  
- App Version:

**Comment by hg42** [comment]
we had this already, but they are gone with the redesign using the new Jetpack Compose lib (which eases development a lot).

The Compose lib doesn't support tooltips, yet.
We don't want to write our own workaround or use some existing from others, because it will probably be implemented in the main libs not too far in the future (hopefully).

The buttons are explained on the info page (settings / top right info button `(i)`).

**Comment by larena1** [comment]
While trying to find the `(i)` you mentioned, I found that the `(i)` next to the app name will send you straight to the app info. Never noticed that before but it works for me.

Maybe some day Jetpack Compose will also support tooltips but as far as I'm concerned, this request can be closed now.

**Comment by hg42** [comment]
at least it's on a todo list somewhere

**Comment by hg42** [comment]
> While trying to find the `(i)` you mentioned

I thought the buttons are explained there, but they are not, sorry for that

the five buttons are:

Epsilon is exodus privacy report
Launch
Disable/Enable
Uninstall
Add to Blocklist

**Comment by hg42** [comment]
I added "Uninstall" and "Add to global blocklist" to HelpPage
