### ISSUE TITLE
[Feature Request] add support for MIUI optimizations

### ISSUE THREAD

**Issue by yoshimo** [NeoApplications/Neo-Backup#681]
**Is your feature request related to a problem? Please describe it.**
MIUI breaks the restore process for apps and you have to disable the miui optimizations in the developer settings.
This unfortunately revokes all app permissions you granted and is annoying as hell.

**Describe the primary solution**

Deal with the changes MIUI did in a native way so you can restore apps without having to disable and re-enable the miui optimizations. We have root after all

**System Information (please complete the following information):**

- Device: Poco X4 Pro 5G
- Android Version: 11
- ROM:  MIUI
- App Version: 8.2.0

**Comment by machiav3lli** [comment]
MIUI (with its MIUI-optimizations-thingy) doesn't support "normal" APIs and still forces a legacy installer that moving forward (starting A13 already) will cause a lot of restrictions to the installed apps. Therefore I don't see hope for a solution for this.
