### ISSUE TITLE
[Question] Having a single backup of the APKs in combination with daily automatic data backups.

### ISSUE THREAD

**Issue by RobertZenz** [NeoApplications/Neo-Backup#699]
I'm unsure whether this is currently possible or not. Currently I have a daily backup scheduled (custom list) which runs great, it performs a backup of both the APKs and the data of a largish number of apps. That means that the daily backups are in the size of several gigabytes.

I'd like to cut down on that and perform only data backups daily (as I do app updates manually for several reasons once a week), with one backup of the APKs which I'd do manually. But from what I could gather Neo Backup is designed to keep only X number of backups regardless of what they contain. Is that correct? There is the new lock feature to keep backups, but that would require me to do all that manually.

Is there a way that I can have an automatic data backup schedule (daily), and perform APK backups manually at will (ideally a disabled schedule with a custom list, executed manually) without these getting overridden by the daily backups?

**Comment by hg42** [comment]
being able to override the backup directory in a schedule would be a solution, and it would be useful for more use cases, e.g. local and remote backups.

The backup directory selection could be replaced by a list of configured directories (with add and remove function).
So switching would be easier and a schedule could just choose from them (but store the path).

**Comment by hg42** [comment]
apart from that, I would not recommend to separate apk and data.
Data that is created by apk A isn't necessarily compatible with apk B.
Actually, usual apps are probably only compatible with the previous version of their data to allow upgrading.

You might separate schedules for important and not so important data, with different backup frequence.

**Comment by RobertZenz** [comment]
> being able to override the backup directory in a schedule.  
 > It would also be useful for more use cases, e.g. local and remote backups.

That would work, yes.

 > apart from that, I would not recommend to separate apk and data.  
 > Data that is created by apk A isn't necessarily compatible with apk B.

Yes, my case is quite an edgecase. A similar (well, more sane, too) case would be if someone only wants to backup the APK together with the data if the app has been updated. I believe Neo Backup does offer options to do that.

 > You might separate schedules for important and not so important data, with different backup frequence.

Explain that one please.

**Comment by hg42** [comment]
I was referring to

> That means that the daily backups are in the size of several gigabytes.
> I'd like to cut down on that

e.g. setup two schedules, one daily and one weekly, and add packages by sorting them by importance of data.
Only a few are usually of the "daily" category.

E.g. my whole backup is about 10-15GB (200-400 user apps), but not many of those are used daily.

Many of my apps don't have important data (e.g. a lot of tools are used like they were installed without any changed preferences).
It's even unimportant to backup each apk, because those can be downloaded again.
But for those with "living" data, I also backup the apk.

However, your use case sounds special. The suggestion may not fit at all.

**Comment by RobertZenz** [comment]
> e.g. setup two schedules, one daily and one weekly, and add packages by sorting them by importance of data.  
 > Only a few are usually of the "daily" category.

That's right, yes.

 > It's even unimportant to backup each apk, because those can be downloaded again.

Yes. I'm a little bit paranoid regarding that, as I do have apps installed which are no longer available (but still useful). Downloading APKs from third-party websites/archives is always possible, but has that stale taste. So having the APK would be nice. It also gives me the possibility to revert back to before the update without breaking a sweat...whether that breaks the app or not is a different matter.

 > However, your use case sounds special.

Yeah, I have that a lot for some reason. I guess what would work for me would be to have two schedules:

 1. Data of all apps in this custom list.
 2. APKs of all apps that were updated since last backup.

And as far as I can see, and as you've already said, everything's already in place (which says a lot how great this software is) except the ability to change target backup directories.

**Comment by hg42** [comment]
"apks no longer updated" is a one time backup (no schedule necessary) and could be locked.
They can be backed up in a different directory by manually changing it.
Better use a safe place and some copies.

**Comment by hg42** [comment]
why?

you switch the backup directory,
backup all the apks that never change again,
switch back,
finished.

Because they don't change, you never have to do that again.
Maybe adding some new apks of that category from time to time.

Or:

you backup the end-of-life apks once,
lock those backups,
finished


In both cases you only backup data for these apks (per schedule).

**Comment by hg42** [comment]
and let's assume some data is also never updated, like obb, just add this to the locked backup (or to the "other" backup) and exclude it from the schedule

**Comment by RobertZenz** [comment]
> why?
 > 
 > you switch the backup directory,  
 > backup all the apks that never change again,  
 > switch back,  
 > finished.  

Oh, that's what you meant. Sorry, misunderstood you there.

**Comment by machiav3lli** [comment]
Just do a backup with only apk and lock it (the small lock button left of the backup item), then increase the backups number with 1 (as it'll be kept e.g with 3 you'll have this one backup and 2 data backups). 
Voila!

**Comment by hg42** [comment]
oh, I thought, a locked backup wouldn't count.

I think it shouldn't, because if you lock one backup, you do not want to keep more backups for all other apps. The locked backup should simply be out of the game (still shown but not considered in housekeeping)

**Comment by machiav3lli** [comment]
I think it goes both ways, I lock a backup to rotate the second (limited to 2 backups). So I see the number as sn absolut value, rather dynamic (except when all backups are locked, then you'll get one more with the new backup)

**Comment by hg42** [comment]
> except when all backups are locked, then you'll get one more with the new backup

ok, that covers the case I was thinking of... locked backups should never prevent the most current backup to be kept.
Otherwise you wouldn't have it in a schedule or batch and do manual backups instead.

**Comment by lexelby** [comment]
> being able to override the backup directory in a schedule.

I kind of implemented this on the user end by cloning Neo Backup using App Cloner.  The main copy has the schedule to back up app data and the clone does APKs and OBBs.  They have separate data directories.
