### ISSUE TITLE
[Bug] Restore data causes the app to hang/not open

### ISSUE THREAD

**Issue by andreapx** [NeoApplications/Neo-Backup#702]
**Description**
For some apps when I restore the backup it goes well, but the app doesn't work anymore (it was working before, just without any data).
For example after restoring data for Signal, it opens a black screen and I have to kill the app; Splitwise opens and suddenly closes (and after a while the message "Splitwie keeps stopping" appears).
**Steps To Reproduce**

1. Install the app with Google Play Store/F-Droid/restore with Neo Backup
2. Restore apps data
3. the app craches

**Expected behavior**
The data should be restored and the app should wotk

**System Information(please complete the following information):**

- Device: Pixel 7 Pro
- Android Version: 13
- ROM: stock
- App's Version: 8.2.5

-----------------------------

>Thanks for reporting.

Oh no, thank you for developing the app!!!

**Comment by DamienCassou** [comment]
I face the same issue for Signal: after restoring the data, I can't open the app anymore.

**Comment by MrEngineerMind** [comment]
If you are restoring data that was backed up from a different version of the app than the app you are restoring that data to, you may have problems.

**Comment by andreapx** [comment]
> If you are restoring data that was backed up from a different version of the app than the app you are restoring that data to, you may have problems.

I've restored app and data and I got the error, so the version was the same

**Comment by DamienCassou** [comment]
I also restored the apk with Neo Backup.

**Comment by machiav3lli** [comment]
Like we note in the [FAQ](https://github.com/NeoApplications/Neo-Backup/blob/main/FAQ.md) (which you seems to haven't read). tldr (only on this issue); there's apps that use Android's KeyStore to encrypt its data, those will definitely fail and funny enough we used Signal as an example of such apps. Signal has an excellent backup system, use it for this.

Feel free to open a new issue for other apps if you're 100% sure it's not KeyStore the issue. This would ease our job.
