### ISSUE TITLE
[Bug] Neo-Backup hangs on startup

### ISSUE THREAD

**Issue by ZhymabekRoman** [NeoApplications/Neo-Backup#708]
**Description**
Neo-Backup just hangs on startup

**Steps To Reproduce**

1. Open Neo-Backup
2. Hangs and crash

**Expected behavior**

Neo-Backup must be started

**Video**

https://user-images.githubusercontent.com/61125068/211180396-72710a83-5252-4468-90d9-e44cf4ca3d06.mp4

**System Information(please complete the following information):**

- Device: Lenovo TB-J716F
- Android Version: 11
- ROM: ZUI  13.1.560 ST
- App's Version: 8.2.5

**Comment by hg42** [comment]
is this the first run?
or is it configured?
where is the backup directory? could it be that it's hanging on the backup directory, not available or something, or via network?

What root solution are you using?

**Comment by ZhymabekRoman** [comment]
> is this the first run?

Yes

> What root solution are you using?

Magisk

I think I know a reason why it's hangs, because these hangs start on other device with barely the same applications installed. I'll test my conclusions and write up the results.

**Comment by machiav3lli** [comment]
This is already fixed for the upcoming 9.3.0
