### ISSUE TITLE
Empty Folders Not Removed

### ISSUE THREAD

**Issue by G-i-o** [NeoApplications/Neo-Backup#714]
Hi.

When deleting backups, NB leaves behind empty folders.

For example, if a backup was created of APK1 (placed in the folder /NEOBACKUPS/APK1) and deleted at some point afterwards, NB deletes all files in the folder (/NEOBACKUP/APK1) but does not remove the actual, now empty, folder.

Thank You!

**Comment by hg42** [comment]
version?

**Comment by G-i-o** [comment]
Apologies.....v8.2.5 on LineageOS v19.1 but also noticed on previous versions (both apk and OS).

**Comment by hg42** [comment]
just tried, it works with current sources (with about 80 new commits)

**Comment by hg42** [comment]
if you want to try you may join the Telegram group (look for the latest pinned "pumpkin" apk, and read the #pumpkin_disclaimer)

**Comment by G-i-o** [comment]
Thank You.

**Comment by tsiflimagas** [comment]
I think this can be closed now.

**Comment by hg42** [comment]
yes, this one should be solved
