### ISSUE TITLE
[Bug] No pacifier during some processing operations

### ISSUE THREAD

**Issue by MrEngineerMind** [NeoApplications/Neo-Backup#725]
**Description**
When I first start the app, for the first 1-2 seconds it will just show "The filtered list is empty", then all of the sudden the list of apps appears.

Also, when I do something to an app that *will* cause it to change it's position in the currently sorted list, I will tap the refresh button to update the list order, and it seems like nothing is happening for 2-3 seconds, then in a flash the order of the list updates.

**Expected behavior**
For operations that *could* take more than 1/2 second (maybe the time depends on device's hardware power), it should display some type of pacifier, like it does when doing a backup, so it will at least indicate to the user that some operation is in progress.

- Device: Pixel 4a
- Android Version: 10
- ROM: (AOSP, MIUI, OOS...)  Stock
- App's Version: 8.3.0

**Comment by hg42** [comment]
yes, Antonios accidentally removed the transparency of certain parts, so the laser beam animation on the background doesn't show through.
You can test my next variant in the TG group, just fading some gray background and a rotating refresh button in red...
