### ISSUE TITLE
[Feature Request] Support For Kernelsu root

### ISSUE THREAD

**Issue by lsander** [NeoApplications/Neo-Backup#730]
App gets root but simply doesn't backup apps. Only some few out of 90 i got. Possible to fix it to work with kernelsu?

**Comment by THMonster** [comment]
Same problem here, just cannot restore any backup with kernelsu.

**Comment by hg42** [comment]
so backup is the "same" like restore?

from what we investigated earlier, kernelsu should work.

Though we made a change lately, that was supposed to make NB even more compatible to root solutions.

will add more info later

**Comment by hg42** [comment]
btw. you totally ignored the issue template...

we need at least NB version, which ROM etc.

**Comment by hg42** [comment]
I was assuming you tried the latest beta...(see telegram group)

if so, does 8.3.2-alpha02 work?

as far as I see official 8.3.1 release only includes the first step, which should work with phh su but not with kernelsu.

this part should be included in 8.3.2-alpha03 and up

**Comment by someone5678** [comment]
> I was assuming you tried the latest beta...(see telegram group)

I think they're using stable release. That's what I did before with KernelSU.
Obviously it's not working well...

But after I install beta release of NeoBackup from telegram group (as you mentioned) and apply latest KernelSU source, it's works without any issue.
Backup, restore, kill, etc. all works fine in my side!
