### ISSUE TITLE
[Feature Request] Restore the origin of an application

### ISSUE THREAD

**Issue by gab12** [NeoApplications/Neo-Backup#732]
**Is your feature request related to a problem? Please describe it.**
Hello, 

When restoring an application, the origin of the application is not kept with NeoBackup.

Indeed, when you go to "application information" (Android side) of a restored application, at the bottom there is "applis details in store": often it is written "Application downloaded from Google Play".
But when NeoBackup restores it says "Application downloaded from Neo Backup".

This behavior is not practical because we lose the information about the source. So it is not restored in the same way. Usually backup applications like Titanium or Swift Backup keep the origin.

This is annoying because:
- We can no longer identify the source of the application has been downloaded: Google play, F-droid etc. ...
- When the source is google play, you can click on the menu and it leads directly to the application file on the Store. I often use it for example to rate the application without having to find it on the store.

**Describe the primary solution**
I find that this is a missing point. Could you also restore the origin ? 

**Describe alternative solutions, if any**
Add an option in NeoBackup to choose the restoration of the origin, or put Neobackup.

**System Information (please complete the following information):**
Android 11 Samsung A50
Neobackup 8.3.1

**Screenshots**
![Screenshot_20230225-150353_Settings](https://user-images.githubusercontent.com/6320898/221361467-fec1355e-2793-43a0-aea5-81d5aa402ad2.jpg)

**Comment by machiav3lli** [comment]
Here's some explination:
- Starting with A13, apps not installed by the Session Installer will face permission restrictions. Session installer doesn't support setting a custom install source.
- There's already an option in service settings to set an installation source which only works when the session installer is disabled.

Considering these two facts, it doesn't make sense to invest time in an already depricated feature. As long as you're on a device running a system under A13, you should be fine setting the mentioned setting to play store package name while having session installer disabled.
