### ISSUE TITLE
[Bug] Restore fail EPIPE

### ISSUE THREAD

**Issue by 404neko** [NeoApplications/Neo-Backup#736]
Log shows :

03-04 23:31:53.419 13030 13107 D NeoBackup>ShellHandler$Companion:17::runAsRoot: Running Command: sh /data/user/0/com.machiav3lli.backup/files/assets/package.sh post-restore "toybox"  com.sakura.rikka 10114 Unknown command: stop-app

then restore stopped

and notification say EPIPE

**Comment by hg42** [comment]
you won't get help if you don't provide the minimum info we ask for

**Comment by 404neko** [comment]
I think the reason of #736 is toybox, so you needn't handle this.
Thanks for your work : )
