### ISSUE TITLE
[Bug] Can't see uninstalled applications

### ISSUE THREAD

**Issue by DamienCassou** [NeoApplications/Neo-Backup#739]
**Description**

When an application is installed, I can restore it. As soon as I uninstall it, it disappears from NeoBackup: this is true whatever the tab is ("home" or "restore"), whatever the filter is ("all apps", "not installed apps" or "apps without backup") and whatever the app is (I tried with [Cuppa](https://f-droid.org/en/packages/com.nathanatos.Cuppa/) and [Métronome](https://f-droid.org/en/packages/de.moekadu.metronome/), both simple apps).

**Steps To Reproduce**

1. Install an application (e.g., [Cuppa](https://f-droid.org/en/packages/com.nathanatos.Cuppa/) from fdroid)
2. Open Neobackup and backup both the data and the apk for this app
3. Wait for the backup to finish
4. Kill the Neobackup application (to make sure you start it fresh)
5. Start Neobackup and check that the new application appears in both "home" and "restore" tabs
6. Uninstall the application
8. Kill the Neobackup application (to make sure you start it fresh)
9. Start Neobackup

You can see that the application doesn't appear anymore, whatever tab/filter you use.

If you install the application from fdroid again, the application magically reappears within Neobackup and I can restore the data.

This bug means I can't use Neobackup to restore my applications, only their data

**Expected behavior**

I would expect that uninstalled applications (that have been backed up before) appear within Neobackup so I can restore them from the backed up apk.

**System Information(please complete the following information):**

- Device: OnePlus 1
- Android Version: 11
- ROM: LineageOS 18 (February 15 2023)
- App's Version: 8.3.1 from fdroid

**Comment by hg42** [comment]
this should be solved by commit a3aa44a8c2866bcd9915eea98490c4f1ec7857f4
thanks for reporting
