### ISSUE TITLE
[Bug] Neo Backup no root Detected Magisk

### ISSUE THREAD

**Issue by Werve** [NeoApplications/Neo-Backup#747]
**Description**
Neo Backup starts but says it did not detect root permissions even though the request screen from Magisk 21.4 appeared and allowed.

**Steps To Reproduce**

1. Open Neo Backup
2. (already accepted Magisk root request)
3. Some magisk tost messages are shown indicating that Neo Backup has used root permissions
4. Neo Backup says no root detected.

**Expected behavior**
Opening the app normally with root.

**Screenshots**
Logcat: 
[logcat.txt](https://github.com/NeoApplications/Neo-Backup/files/11240828/logcat.txt)

**System Information(please complete the following information):**

- Device: Samsung Galaxy Note GT-N7000
- Android Version: 9
- ROM: Custom ROM Lineage 16 on a very old phone (Samsung Note n7000)
- App's Version: 8.3.1

-----------------------------

Same other apps also do not detect root but some others do (Mixplorer, 3c All-in-One Toolbox, SmartPack ecc)

**Comment by bill-mcgonigle** [comment]
Did you go into Magisk and tap the 'shield' tab and see if there's an entry?
I've had some that show up there but I have to turn it on manually even though I clicked OK/forever when the toast came up.  In recent-ish Magisks only.
