### ISSUE TITLE
Hope to add full system backup function

### ISSUE THREAD

**Issue by ae86ssl** [NeoApplications/Neo-Backup#761]
Some APPs that need to be logged in, if they are restored, they need to log in again because of the change of hardware information, etc., I hope to add an option whether to backup hardware information, such as imei, brand model, and other mobile phone hardware related information

**Comment by MrEngineerMind** [comment]
Some apps store their security credentials in the devices keystore, which can NOT be backed up by NeoBackup. Thats why you need to re-log into certain apps after restoring them.

**Comment by ae86ssl** [comment]
I know that some xp modules that modify the hardware information of the mobile phone through root can simulate hardware information, so as to avoid login and restore the login status at the time of backup. I don’t know if similar functions can be added

**Comment by ae86ssl** [comment]
It would be great if it can simulate restored hardware parameters, or just record hardware information

**Comment by machiav3lli** [comment]
Key Store the contruct which holds the encryption keys of system handled data is either software-base or hardware-based depending on the device, on both ways there's no documentation of anyone being able to knock it (neither security rsearchers nor magisk module devs), and this will stay probably true. This kills your main wish.

More comprehensibly, NB isn't meant for a full system backup, for that you have NAndBackups aka TWRP backups, even those can't keep the access to the Key Store.
