### ISSUE TITLE
[Feature Request] Backing up without force closing app

### ISSUE THREAD

**Issue by sombresu** [NeoApplications/Neo-Backup#764]
**Is your feature request related to a problem? 
No. But letting the program run while doing  back up and not one sidedly closing it would be nice.

**System Information

- Device: POCO
- Android Version: 12
- ROM: MIUI 13.0.5
- App Version: 8.3.1

**Comment by machiav3lli** [comment]
Settings → Advanced → developer settings  → advanced users → make sure that both backupPauseApps & backupSuspendApps disabled
