### ISSUE TITLE
[Icon Legend] Help should have a legend to various icons used in the app.

### ISSUE THREAD

**Issue by ashjas** [NeoApplications/Neo-Backup#771]
It's difficult to know what all icons used in the app actually mean. I can't seem to find any existing legend feature that describe icons.

**Example:**
 
![69483756-085c-4e7c-9553-881c87a8f18d](https://github.com/NeoApplications/Neo-Backup/assets/788766/2ec5c7b6-53c4-446b-a007-8450593130aa)

**Comment by hg42** [comment]
just look around, it's all there

**Comment by tsiflimagas** [comment]
Settings>info icon in the top right corner
