### ISSUE TITLE
[Bug] Old backup files are not detected on new phone

### ISSUE THREAD

**Issue by Lightfire228** [NeoApplications/Neo-Backup#782]
**Description**
I just switched from a Pixel 5 to an S23 Ultra, and copied over the backup folder using syncthing.  However, on the new phone, the list of backups and restores is empty

**Steps To Reproduce**

0. Acquire a fresh Android
1. Copy over NB backup folder (using syncthing)
2. Install NB
3. Restore list is empty

**Expected behavior**
The app provides a list of found backup files, even if the target apps aren't installed

**Screenshots**

<details><summary>Filter Settings</summary>

![Screenshot_20230801_123956_Neo_Backup_4](https://github.com/NeoApplications/Neo-Backup/assets/15241322/2e0ec3cc-0d7e-4441-89e4-d06c91cd201e)

![Screenshot_20230801_124003_Neo_Backup_3](https://github.com/NeoApplications/Neo-Backup/assets/15241322/530ef114-4013-4d8e-adb3-20b067f41cb9)

</details>

<details><summary>Restore Page</summary>

![Screenshot_20230801_124015_Neo_Backup_2](https://github.com/NeoApplications/Neo-Backup/assets/15241322/57c9cb10-b35a-4953-87b0-a08e2929050e)

</details>

<details><summary>Backup folder in Amaze</summary>

![Screenshot_20230801_124048_Amaze](https://github.com/NeoApplications/Neo-Backup/assets/15241322/dbb2aac2-863f-405b-95e8-131a4d87f5e4)

</details>

<details><summary>NB settings and backup folder</summary>

![dragon](https://github.com/NeoApplications/Neo-Backup/assets/15241322/7c9a6fde-c678-4902-ac51-897b86c81778)

</details>

<details><summary>File Picker when choosing backup folder</summary>

![Screenshot_20230801_131718_Files](https://github.com/NeoApplications/Neo-Backup/assets/15241322/8f3e317b-6550-4fa8-99f3-abd66bae3867)

</details>

**System Information:**

- Device: 
  - Samsung S23 Ultra
- Android Version: 
  - 13
- ROM: 
  - Stock Samsung with Magisk
  - Baseband version `S918BXXS3AWF7`
- App's Version: 
  - 8.3.2
-----------------------------

**Additional Notes**

I noticed the space in the `~/Backups /` path in Amaze file explorer, and removed it, but that didn't fix it.

Additionally, the target path in NB looks mangled: 
`content://com.android.externalstorage.documents/tree/primary%3ABackup%2FNeo%20backup/document/primary/%3ABackup%2FNeo%20backup`. 

The actual target path on disk is `~/Backup/Neo Backup/`

It looks like this is an issue of file path encoding between NB and the file picker

Edit: the path in NB looks the same on my Pixel 5, and it's fine, so I have no clue

**Comment by MrEngineerMind** [comment]
I would renavigate to the directory where you placed the backups using the "Backup Folder" button in settings.

**Comment by Lightfire228** [comment]
@MrEngineerMind  I did

I updated the issue with a screenshot of the file picker (at the bottom)

**Comment by Lightfire228** [comment]
I think I might've figured out what the issues is

![Screenshot_20230801_164951_Amaze](https://github.com/NeoApplications/Neo-Backup/assets/15241322/7e803238-a1ac-44b3-960f-8a2249c175b0)

**Comment by Lightfire228** [comment]
Yup, I didn't check to see if all of the files transferred correctly 

I just did an `adb pull` and `adb push`, and they're all there

<details><summary>These screenshots are so huge</summary>

![image](https://github.com/NeoApplications/Neo-Backup/assets/15241322/e4db23f8-cf5c-489b-b641-4e0f0cf32206)

<details>
