### ISSUE TITLE
[OTHER] The application for some reason gets ROOT access after some time after turning on the device

### ISSUE THREAD

**Issue by Artem13327** [NeoApplications/Neo-Backup#789]
I don't have scheduled backup enabled
I'm not particularly happy that the application gets ROOT access, although it's not boring for him😐

**Comment by machiav3lli** [comment]
If you mean reboot with "turning on the device", it has to do with the fact that NB has a reboot receiver and creates a (root) shell whenever it's started. If you mean something else, then you can gladly re-open the issue
