### ISSUE TITLE
[Bug] Backup fails with "ScriptException: tar: chdir '--exclude' - tar: chdir '--exclude'"

### ISSUE THREAD

**Issue by benoiton** [NeoApplications/Neo-Backup#793]
Trying to backup any application always leads to a backup failure.

```
Backup FAILED: false BackupAppAction$BackupFailedException: com.machiav3lli.backup.actions.BaseAppAction$ScriptException occurred on data backup: com.machiav3lli.backup.actions.BaseAppAction$ScriptException: tar: chdir '--exclude' - tar: chdir '--exclude'
```
[Full log](https://github.com/NeoApplications/Neo-Backup/files/12641372/2023-09-16-20-13-42-747.log.txt)

- Device: herolte
- Android Version: Android 9
- ROM: LineageOS 16.0
- App's Version: 8.3.2 from FDroid

**Comment by MrEngineerMind** [comment]
Try rebooting your device and see if it still happens.

**Comment by benoiton** [comment]
Just rebooted: same error.

**Comment by benoiton** [comment]
After installing a new version of busybox, it finally works.
