### ISSUE TITLE
Crash while backing up

### ISSUE THREAD

**Issue by Turhvjbufv** [NeoApplications/Neo-Backup#817]
**Description**
I think NB crashes some apps that have background proceses active since they only crash if backup is active

**Steps To Reproduce**

Backup apps data and apk
Apps crash

**Expected behavior**
For apps not to crash

**Screenshots**
Only if there's no clear logs, add screenshots to help explain your problem.

**System Information(please complete the following information):**

- Device: A72
- Android Version: 13
- ROM: (AOSP, MIUI, OOS...)  Lineage
- App's Version: 8.3.4 fdroid

Molly crash:
ANR in im.molly.app
PID: 6617
Reason: Broadcast of Intent { act=org.thoughtcrime.securesms.util.AlarmSleepTimer.AlarmReceiver.WAKE_UP_THREAD.0 flg=0x14 (has extras) }
ErrorId: b182990e-8b21-4e2b-a923-639681718df0
Frozen: false
Load: 15.93 / 16.66 / 10.34
----- Output from /proc/pressure/memory -----
some avg10=0.18 avg60=0.41 avg300=0.69 total=10181130
full avg10=0.00 avg60=0.00 avg300=0.06 total=3986942
----- End output from /proc/pressure/memory -----
CPU usage from 1ms to 16180ms later (2023-12-01 20:42:44.362 to 2023-12-01 20:43:00.541):
  253% 7127/com.machiav3lli.backup: 226% user + 26% kernel / faults: 121819 minor 62 major
  29% 2062/system_server: 20% user + 8.5% kernel / faults: 17432 minor 1422 major
  28% 3716/com.android.providers.media.module: 13% user + 15% kernel / faults: 14539 minor 22 major
  24% 5016/com.android.systemui: 20% user + 4.1% kernel / faults: 18644 minor 148 major
  12% 10349/com.aliucord: 11% user + 1.2% kernel / faults: 7111 minor 18 major
  9.9% 6082/com.google.android.inputmethod.latin: 8.1% user + 1.8% kernel / faults: 11416 minor 104 major
  7.9% 1294/surfaceflinger: 4.7% user + 3.2% kernel / faults: 730 minor
  7.1% 27412/com.fmwhatsapp: 5.3% user + 1.8% kernel / faults: 9098 minor 34 major
  5.3% 9660/com.f0x1d.logfox: 4.4% user + 0.8% kernel / faults: 11234 minor 26 major
  5% 144/kswapd0: 0% user + 5% kernel
  4.8% 3777/com.tombayley.volumepanel: 3.8% user + 1% kernel / faults: 592 minor
  3.8% 3865/de.nulide.findmydevice: 3.2% user + 0.6% kernel / faults: 5550 minor 9 major
  3.3% 4621/com.android.externalstorage: 1.5% user + 1.7% kernel / faults: 352 minor
  3.3% 25297/org.mozilla.fenix:tab31: 2.6% user + 0.7% kernel / faults: 1256 minor 55 major
  2.2% 254/kworker/u16:5: 0% user + 2.2% kernel
  2.1% 253/kworker/u16:4: 0% user + 2.1% kernel
  2.1% 1210/android.hardware.graphics.composer@2.4-service: 1.2% user + 0.8% kernel / faults: 23 minor
  1.7% 26032/toybox: 0% user + 1.7% kernel
  1.7% 539/logd: 0.4% user + 1.2% kernel / faults: 144 minor
  1.4% 262/crtc_commit:96: 0% user + 1.4% kernel
  1.3% 24808/org.mozilla.fenix: 1.2% user + 0% kernel / faults: 396 minor 4 major
  1% 3025/com.android.phone: 0.8% user + 0.1% kernel / faults: 3784 minor 20 major
  0.9% 3526/irq/78-90cd000.: 0% user + 0.9% kernel
  0.8% 269/kgsl_worker_thr: 0% user + 0.8% kernel
  0% 1378/media.codec: 0% user + 0% kernel / faults: 3531 minor 21 major
  0.8% 3490/kworker/u16:17: 0% user + 0.8% kernel
  0.7% 304/kworker/u16:8: 0% user + 0.7% kernel
  0.7% 26408/toybox: 0% user + 0.7% kernel
  0.6% 3524/irq/77-90b6300.: 0% user + 0.6% kernel
  0.6% 8089/toybox: 0% user + 0.6% kernel
  0.6% 9/rcu_preempt: 0% user + 0.6% kernel
  0.6% 329/irq/231-fts_tou: 0% user + 0.6% kernel
  0.6% 5651/advanced.scientific.calculator.calc991.plus: 0.4% user + 0.1% kernel / faults: 278 minor 9 major
  0.5% 46/rcuop/4: 0% user + 0.5% kernel
  0.5% 1222/android.hardware.wifi@1.0-service: 0.2% user + 0.3% kernel / faults: 218 minor
  0.5% 9708/logcat: 0.3% user + 0.1% kernel
  0.4% 12/rcuop/0: 0% user + 0.4% kernel
  0.4% 1126/statsd: 0.1% user + 0.3% kernel / faults: 118 minor 3 major
  0% 1397/media.swcodec: 0% user + 0% kernel / faults: 5115 minor 31 major
  0.4% 3854/io.github.jd1378.otphelper: 0.3% user + 0.1% kernel / faults: 191 minor 16 major
  0.4% 5608/com.google.android.gms:persistent: 0.3% user + 0.1% kernel / faults: 3754 minor 30 major
  0.4% 20764/toybox: 0% user + 0.4% kernel
  0.4% 62/rcuop/6: 0% user + 0.4% kernel
  0% 1364/media.extractor: 0% user + 0% kernel / faults: 1895 minor 13 major
  0% 2967/.qtidataservices: 0% user + 0% kernel / faults: 3151 minor 13 major
  0.3% 4825/net.kollnig.missioncontrol.fdroid: 0.1% user + 0.1% kernel / faults: 11 minor
  0.3% 7175/sh: 0.1% user + 0.2% kernel / faults: 609 minor
  0.3% 4/kworker/0:0: 0% user + 0.3% kernel
  0.3% 54/rcuop/5: 0% user + 0.3% kernel
  0.3% 70/rcuop/7: 0% user + 0.3% kernel
  0.3% 1217/android.hardware.sensors-service.samsung-multihal: 0.1% user + 0.1% kernel
  0.3% 2641/com.android.networkstack.process: 0.1% user + 0.1% kernel / faults: 3065 minor 10 major
  0.3% 2653/com.topjohnwu.magisk: 0.2% user + 0% kernel / faults: 50 minor
  0% 3000/com.android.se: 0% user + 0% kernel / faults: 2874 minor 9 major
  0% 3729/org.lineageos.settings.doze: 0% user + 0% kernel / faults: 2858 minor 2 major
  0.2% 8/ksoftirqd/0: 0% user + 0.2% kernel
  0.2% 10/rcu_sched: 0% user + 0.2% kernel
  0.2% 30/rcuop/2: 0% user + 0.2% kernel
  0% 3736/org.lineageos.audiofx: 0% user + 0% kernel / faults: 2869 minor 3 major
  0.1% 1/init: 0% user + 0.1% kernel
  0.1% 22/rcuop/1: 0% user + 0.1% kernel
  0.1% 38/rcuop/3: 0% user + 0.1% kernel
  0.1% 631/android.hardware.power-service.samsung-libperfmgr: 0.1% user + 0% kernel
  0% 641/tombstoned: 0% user + 0% kernel / faults: 5 minor 3 major
  0.1% 770/magiskd: 0% user + 0.1% kernel / faults: 546 minor
  0.1% 783/lspd: 0% user + 0.1% kernel / faults: 1 minor
  0.1% 1232/vendor.qti.hardware.display.allocator-service: 0% user + 0.1% kernel
  0.1% 2464/com.drdisagree.iconify: 0.1% user + 0% kernel / faults: 164 minor
  0% 3724/com.android.nfc: 0% user + 0% kernel / faults: 3021 minor 6 major
  0.1% 63/rcuos/6: 0% user + 0.1% kernel
  0.1% 95/system: 0% user + 0.1% kernel
  0.1% 263/crtc_event:96: 0% user + 0.1% kernel
  0.1% 629/f2fs_discard-25: 0% user + 0.1% kernel
  0% 655/loop7: 0% user + 0% kernel
  0.1% 1127/netd: 0% user + 0.1% kernel / faults: 84 minor 2 major
  0.1% 1353/cameraserver: 0% user + 0.1% kernel / faults: 61 minor
  0.1% 1379/rild: 0% user + 0% kernel
  0.1% 3835/com.google.android.gms: 0% user + 0% kernel / faults: 27 minor 9 major
  0.1% 18690/kworker/0:1H: 0% user + 0.1% kernel
  0% 15/migration/0: 0% user + 0% kernel
  0% 31/rcuos/2: 0% user + 0% kernel
  0% 47/rcuos/4: 0% user + 0% kernel
  0% 71/rcuos/7: 0% user + 0% kernel
  0% 110/kworker/3:1: 0% user + 0% kernel
  0% 151/kworker/5:1: 0% user + 0% kernel
  0% 540/lmkd: 0% user + 0% kernel
  0% 542/hwservicemanager: 0% user + 0% kernel
  0% 554/vold: 0% user + 0% kernel / faults: 65 minor 6 major
  0% 598/keystore2: 0% user + 0% kernel / faults: 50 minor
  0% 662/loop10: 0% user + 0% kernel
  0% 673/loop16: 0% user + 0% kernel
  0% 735/loop29: 0% user + 0% kernel
  0% 1119/wlan_logging_th: 0% user + 0% kernel
  0% 1153/kworker/1:1H: 0% user + 0% kernel
  0% 1181/qrtr_rx: 0% user + 0% kernel
  0% 1212/android.hardware.health@2.1-service-samsung: 0% user + 0% kernel
  0% 1239/vendor.samsung.hardware.thermal@1.0-service: 0% user + 0% kernel
  0% 1282/audioserver: 0% user + 0% kernel / faults: 62 minor
  0% 1363/installd: 0% user + 0% kernel
  0% 1374/wificond: 0% user + 0% kernel
  0% 2046/scheduler_threa: 0% user + 0% kernel
  0% 2047/cds_ol_rx_threa: 0% user + 0% kernel
  0% 7320/com.radolyn.ayugram: 0% user + 0% kernel / faults: 5 minor 4 major
  0% 13711/com.angolix.android.wallpaper.slideshow: 0% user + 0% kernel / faults: 2 minor
  0% 17040/kworker/2:0: 0% user + 0% kernel
  0% 24061/kworker/7:2: 0% user + 0% kernel
  0% 26912/kworker/4:2: 0% user + 0% kernel
 +0% 28010/su: 0% user + 0% kernel
 +0% 28017/sh: 0% user + 0% kernel
 +0% 28020/sh: 0% user + 0% kernel
 +0% 28021/sh: 0% user + 0% kernel
 +0% 28022/toybox: 0% user + 0% kernel
 +0% 28086/su: 0% user + 0% kernel
 +0% 28090/sh: 0% user + 0% kernel
 +0% 28091/sh: 0% user + 0% kernel
 +0% 28092/sh: 0% user + 0% kernel
 +0% 28093/toybox: 0% user + 0% kernel
69% TOTAL: 48% user + 17% kernel + 0.8% iowait + 1.5% irq + 1.2% softirq
CPU usage from 97ms to 601ms later (2023-12-01 20:42:44.458 to 2023-12-01 20:42:44.962):
  240% 7127/com.machiav3lli.backup: 223% user + 16% kernel / faults: 2035 minor
    46% 7241/DefaultDispatch: 40% user + 6.6% kernel
    36% 7230/DefaultDispatch: 33% user + 3.3% kernel
    33% 10030/DefaultDispatch: 30% user + 3.3% kernel
    30% 10017/DefaultDispatch: 26% user + 3.3% kernel
    30% 11239/DefaultDispatch: 30% user + 0% kernel
    26% 7158/DefaultDispatch: 26% user + 0% kernel
    23% 10014/DefaultDispatch: 20% user + 3.3% kernel
    10% 7141/HeapTaskDaemon: 10% user + 0% kernel
  169% 3716/com.android.providers.media.module: 83% user + 86% kernel / faults: 1496 minor
    64% 4322/AsyncTask #1: 48% user + 16% kernel
    59% 3903/ackgroundThread: 13% user + 45% kernel
    10% 3781/HeapTaskDaemon: 10% user + 0% kernel
    8% 3716/rs.media.module: 5.3% user + 2.6% kernel
    5.3% 3909/fg: 2.6% user + 2.6% kernel
    2.6% 3782/ReferenceQueueD: 2.6% user + 0% kernel
    2.6% 3948/emulated;0: 0% user + 2.6% kernel
    2.6% 8076/binder:3716_9: 2.6% user + 0% kernel
    2.6% 27755/Thread-786: 0% user + 2.6% kernel
    2.6% 27776/Thread-787: 0% user + 2.6% kernel
    2.6% 27831/Thread-793: 0% user + 2.6% kernel
   +0% 27864/Thread-791: 0% user + 0% kernel
   +0% 27866/Thread-791: 0% user + 0% kernel
  128% 2062/system_server: 86% user + 41% kernel / faults: 1029 minor
    34% 27863/AnrConsumer: 12% user + 22% kernel
    17% 2086/HeapTaskDaemon: 17% user + 0% kernel
    17% 2090/binder:2062_1: 14% user + 2.4% kernel
    17% 4428/binder:2062_11: 14% user + 2.4% kernel
    14% 3740/binder:2062_B: 9.8% user + 4.9% kernel
    4.9% 2122/android.ui: 2.4% user + 2.4% kernel
    4.9% 2131/ActivityManager: 2.4% user + 2.4% kernel
    4.9% 2143/bgres-controlle: 4.9% user + 0% kernel
    2.4% 2062/system_server: 2.4% user + 0% kernel
    2.4% 2087/ReferenceQueueD: 0% user + 2.4% kernel
    2.4% 2138/batterystats-ha: 2.4% user + 0% kernel
    2.4% 2148/PowerManagerSer: 2.4% user + 0% kernel
  62% 27846/toybox: 15% user + 46% kernel
  50% 27847/toybox: 31% user + 19% kernel
  12% 144/kswapd0: 0% user + 12% kernel
  19% 27412/com.fmwhatsapp: 15% user + 3.8% kernel / faults: 119 minor
    7.7% 27412/com.fmwhatsapp: 3.8% user + 3.8% kernel
    3.8% 27439/.88(531124113: 3.8% user + 0% kernel
    3.8% 27457/High Pri Worker: 3.8% user + 0% kernel
    3.8% 27632/EphremeralExecu: 3.8% user + 0% kernel
    3.8% 27634/Notifications: 3.8% user + 0% kernel
  8.1% 253/kworker/u16:4: 0% user + 8.1% kernel
  8.8% 5608/com.google.android.gms:persistent: 5.8% user + 2.9% kernel / faults: 19 minor 11 major
    2.9% 5608/.gms:persistent: 2.9% user + 0% kernel
    2.9% 5634/McsHandler: 0% user + 2.9% kernel
  10% 9660/com.f0x1d.logfox: 10% user + 0% kernel / faults: 130 minor
    7.1% 11122/DefaultDispatch: 7.1% user + 0% kernel
  4.2% 539/logd: 2.1% user + 2.1% kernel
  4.5% 1294/surfaceflinger: 2.2% user + 2.2% kernel
    2.2% 1318/binder:1294_1: 2.2% user + 0% kernel
    2.2% 1340/app: 2.2% user + 0% kernel
  2% 62/rcuop/6: 0% user + 2% kernel
  2% 70/rcuop/7: 0% user + 2% kernel
  2% 269/kgsl_worker_thr: 0% user + 2% kernel
  2.1% 783/lspd: 2.1% user + 0% kernel
  2.1% 1126/statsd: 2.1% user + 0% kernel
    2.1% 1823/statsd.writer: 0% user + 2.1% kernel
  2.3% 1353/cameraserver: 0% user + 2.3% kernel
  2.7% 3777/com.tombayley.volumepanel: 2.7% user + 0% kernel / faults: 10 minor
    5.5% 3777/ley.volumepanel: 2.7% user + 2.7% kernel
  2.9% 5016/com.android.systemui: 2.9% user + 0% kernel / faults: 2 minor
  3.5% 10349/com.aliucord: 3.5% user + 0% kernel / faults: 1 minor
    3.5% 10443/RenderThread: 3.5% user + 0% kernel
  3.8% 25630/toybox: 0% user + 3.8% kernel
  3.9% 27840/toybox: 0% user + 3.9% kernel
94% TOTAL: 59% user + 31% kernel + 1.7% irq + 1.5% softirq
Completed ANR of im.molly.app in 16214ms, latency 0ms

Wallshow crash:
ANR in com.angolix.android.wallpaper.slideshow
PID: 6288
Reason: executing service com.angolix.android.wallpaper.slideshow/com.code.app.service.WallpaperService
ErrorId: 2f277ce0-15eb-48b1-b2f5-4b403961be68
Frozen: false
Load: 15.91 / 7.88 / 3.08
----- Output from /proc/pressure/memory -----
some avg10=0.01 avg60=0.88 avg300=0.56 total=2712878
full avg10=0.00 avg60=0.25 avg300=0.15 total=1088648
----- End output from /proc/pressure/memory -----
CPU usage from 0ms to 19836ms later (2023-12-01 20:32:43.533 to 2023-12-01 20:33:03.368):
  186% 7127/com.machiav3lli.backup: 168% user + 18% kernel / faults: 120792 minor 71 major
  67% 8869/nekox.messenger: 57% user + 9% kernel / faults: 156320 minor 598 major
  44% 2062/system_server: 32% user + 12% kernel / faults: 95154 minor 228 major
  40% 5016/com.android.systemui: 33% user + 7.2% kernel / faults: 42646 minor 161 major
  26% 8134/eu.kanade.tachiyomi.sy: 23% user + 3.8% kernel / faults: 25225 minor 155 major
  25% 3716/com.android.providers.media.module: 13% user + 11% kernel / faults: 16620 minor 25 major
  17% 144/kswapd0: 0% user + 17% kernel
  16% 1294/surfaceflinger: 9.3% user + 7.2% kernel / faults: 1057 minor 1 major
  11% 9660/com.f0x1d.logfox: 9.2% user + 1.9% kernel / faults: 10007 minor
  6.4% 3777/com.tombayley.volumepanel: 4.9% user + 1.4% kernel / faults: 4693 minor 35 major
  4.6% 4621/com.android.externalstorage: 2.8% user + 1.8% kernel / faults: 5005 minor 6 major
  4.2% 1210/android.hardware.graphics.composer@2.4-service: 2.4% user + 1.7% kernel / faults: 32 minor
  3.4% 6617/im.molly.app: 2.3% user + 1.1% kernel / faults: 456 minor
  3.3% 6082/com.google.android.inputmethod.latin: 2% user + 1.3% kernel / faults: 10399 minor 41 major
  1% 3028/com.android.settings: 0.9% user + 0.1% kernel / faults: 6394 minor 101 major
  2.6% 3865/de.nulide.findmydevice: 2.1% user + 0.5% kernel / faults: 4510 minor
  2.5% 8218/toybox: 0.1% user + 2.4% kernel
  2.3% 3753/com.saggitt.omega: 2.1% user + 0.2% kernel / faults: 2220 minor 17 major
  2.2% 327/kworker/u16:14: 0% user + 2.2% kernel
  2.1% 262/crtc_commit:96: 0% user + 2.1% kernel
  1.9% 8089/toybox: 0.1% user + 1.8% kernel
  1.6% 539/logd: 0.7% user + 0.9% kernel / faults: 1196 minor
  1.3% 3490/kworker/u16:17: 0% user + 1.3% kernel
  1.2% 252/kworker/u16:3: 0% user + 1.2% kernel
  1.2% 269/kgsl_worker_thr: 0% user + 1.2% kernel
  0.3% 4825/net.kollnig.missioncontrol.fdroid: 0.1% user + 0.2% kernel / faults: 56 minor
  0.3% 1282/audioserver: 0.1% user + 0.2% kernel / faults: 273 minor 91 major
  1% 8313/toybox: 0% user + 1% kernel
  0.3% 1397/media.swcodec: 0.1% user + 0.1% kernel / faults: 5244 minor 48 major
  0.9% 3025/com.android.phone: 0.7% user + 0.2% kernel / faults: 4243 minor 49 major
  0.8% 4750/com.fmwhatsapp: 0.2% user + 0.6% kernel / faults: 285 minor 6 major
  0.7% 253/kworker/u16:4: 0% user + 0.7% kernel
  0.7% 3526/irq/78-90cd000.: 0% user + 0.7% kernel
  0.6% 9/rcu_preempt: 0% user + 0.6% kernel
  0.5% 1126/statsd: 0.3% user + 0.2% kernel / faults: 148 minor 6 major
  0.5% 1232/vendor.qti.hardware.display.allocator-service: 0% user + 0.5% kernel
  0.1% 1378/media.codec: 0.1% user + 0% kernel / faults: 3630 minor 34 major
  0.5% 3524/irq/77-90b6300.: 0% user + 0.5% kernel
  0.5% 46/rcuop/4: 0% user + 0.5% kernel
  0.5% 62/rcuop/6: 0% user + 0.5% kernel
  0.5% 95/system: 0% user + 0.5% kernel
  0.1% 2967/.qtidataservices: 0.1% user + 0% kernel / faults: 3933 minor 10 major
  0.5% 3854/io.github.jd1378.otphelper: 0.3% user + 0.2% kernel / faults: 414 minor 5 major
  0.5% 9708/logcat: 0.1% user + 0.4% kernel / faults: 2 minor
  0.4% 12/rcuop/0: 0% user + 0.4% kernel
  0.4% 75/kworker/u16:1: 0% user + 0.4% kernel
  0.4% 1127/netd: 0.1% user + 0.3% kernel / faults: 435 minor 14 major
  0.1% 2650/com.android.launcher3: 0.1% user + 0% kernel / faults: 509 minor 1 major
  0.4% 8659/toybox: 0% user + 0.4% kernel
  0.4% 54/rcuop/5: 0% user + 0.4% kernel
  0.4% 263/crtc_event:96: 0% user + 0.4% kernel
  0.4% 770/magiskd: 0% user + 0.4% kernel / faults: 468 minor
  0.4% 1222/android.hardware.wifi@1.0-service: 0.1% user + 0.2% kernel / faults: 205 minor
  0.1% 2047/cds_ol_rx_threa: 0% user + 0.1% kernel
  0.1% 2464/com.drdisagree.iconify: 0.1% user + 0% kernel / faults: 451 minor 4 major
  0.4% 2641/com.android.networkstack.process: 0.2% user + 0.2% kernel / faults: 3818 minor 16 major
  0.4% 8121/toybox: 0% user + 0.3% kernel
  0.4% 9220/toybox: 0% user + 0.4% kernel
  0.3% 8162/toybox: 0% user + 0.3% kernel
  0.3% 1217/android.hardware.sensors-service.samsung-multihal: 0.1% user + 0.2% kernel
  0.1% 3000/com.android.se: 0% user + 0% kernel / faults: 3631 minor 2 major
  0.1% 3724/com.android.nfc: 0% user + 0% kernel / faults: 3554 minor 2 major
  0.1% 3736/org.lineageos.audiofx: 0% user + 0% kernel / faults: 3615 minor 2 major
  0.3% 5651/advanced.scientific.calculator.calc991.plus: 0.2% user + 0% kernel / faults: 176 minor 3 major
  0.2% 8/ksoftirqd/0: 0% user + 0.2% kernel
  0.2% 10/rcu_sched: 0% user + 0.2% kernel
  0.2% 30/rcuop/2: 0% user + 0.2% kernel
  0.2% 70/rcuop/7: 0% user + 0.2% kernel
  0% 1364/media.extractor: 0% user + 0% kernel / faults: 1990 minor 28 major
  0.2% 2653/com.topjohnwu.magisk: 0.1% user + 0.1% kernel / faults: 102 minor 1 major
  0% 3729/org.lineageos.settings.doze: 0% user + 0% kernel / faults: 3572 minor 2 major
  0.2% 1/init: 0.1% user + 0.1% kernel
  0.2% 4/kworker/0:0: 0% user + 0.2% kernel
  0.2% 329/irq/231-fts_tou: 0% user + 0.2% kernel
  0.2% 540/lmkd: 0% user + 0.1% kernel
  0% 541/servicemanager: 0% user + 0% kernel
  0% 641/tombstoned: 0% user + 0% kernel / faults: 43 minor 50 major
  0.2% 7175/sh: 0.1% user + 0.1% kernel / faults: 421 minor
  0.1% 22/rcuop/1: 0% user + 0.1% kernel
  0.1% 38/rcuop/3: 0% user + 0.1% kernel
  0.1% 783/lspd: 0% user + 0.1% kernel / faults: 2 minor
  0.1% 1209/android.hardware.gnss@2.1-service-qti: 0% user + 0.1% kernel / faults: 18 minor
  0% 1646/magiskhide_daemon: 0% user + 0% kernel / faults: 27 minor
  0.1% 3787/eu.darken.sdmse: 0.1% user + 0% kernel / faults: 6 minor
  0% 3835/com.google.android.gms: 0% user + 0% kernel / faults: 170 minor 50 major
  0.1% 5764/app.rvx.android.youtube: 0.1% user + 0% kernel / faults: 34 minor 17 major
  0.1% 5/kworker/0:0H: 0% user + 0.1% kernel
  0.1% 63/rcuos/6: 0% user + 0.1% kernel
  0.1% 110/kworker/3:1: 0% user + 0.1% kernel
  0.1% 151/kworker/5:1: 0% user + 0.1% kernel
  0.1% 629/f2fs_discard-25: 0% user + 0.1% kernel
  0.1% 631/android.hardware.power-service.samsung-libperfmgr: 0% user + 0% kernel
  0.1% 1353/cameraserver: 0% user + 0.1% kernel / faults: 74 minor 7 major
  0% 1371/mediaserver: 0% user + 0% kernel / faults: 206 minor 63 major
  0.1% 1379/rild: 0% user + 0% kernel
  0.1% 1830/kworker/4:2: 0% user + 0.1% kernel
  0.1% 3666/shizuku_server: 0% user + 0% kernel / faults: 24 minor
  0.1% 7893/io.heckel.ntfy: 0% user + 0% kernel / faults: 102 minor 8 major
  0% 31/rcuos/2: 0% user + 0% kernel
  0% 47/rcuos/4: 0% user + 0% kernel
  0% 55/rcuos/5: 0% user + 0% kernel
  0% 59/ksoftirqd/6: 0% user + 0% kernel
  0% 83/kcompactd0: 0% user + 0% kernel
  0% 123/kworker/2:1: 0% user + 0% kernel
  0% 456/kworker/7:1H: 0% user + 0% kernel
  0% 480/ueventd: 0% user + 0% kernel
  0% 554/vold: 0% user + 0% kernel / faults: 51 minor 14 major
  0% 598/keystore2: 0% user + 0% kernel / faults: 53 minor 1 major
  0% 655/loop7: 0% user + 0% kernel
  0% 673/loop16: 0% user + 0% kernel
  0% 726/loop27: 0% user + 0% kernel
  0% 735/loop29: 0% user + 0% kernel
  0% 1128/zygote64: 0% user + 0% kernel / faults: 50 minor
  0% 1181/qrtr_rx: 0% user + 0% kernel
  0% 1199/android.hardware.audio.service: 0% user + 0% kernel / faults: 31 minor 36 major
  0% 1239/vendor.samsung.hardware.thermal@1.0-service: 0% user + 0% kernel
  0% 1363/installd: 0% user + 0% kernel / faults: 44 minor
  0% 1372/storaged: 0% user + 0% kernel
  0% 2046/scheduler_threa: 0% user + 0% kernel
  0% 4184/com.android.vending: 0% user + 0% kernel / faults: 5 minor 2 major
  0% 4363/eu.faircode.email: 0% user + 0% kernel / faults: 7 minor
  0% 7320/com.radolyn.ayugram: 0% user + 0% kernel
  0% 7400/com.simplemobiletools.gallery.pro: 0% user + 0% kernel / faults: 5 minor
  0% 8392/im.vector.app: 0% user + 0% kernel / faults: 2 minor
  0% 8790/ml.docilealligator.infinityforreddit: 0% user + 0% kernel / faults: 1 minor
  0% 8954/org.mozilla.fenix: 0% user + 0% kernel / faults: 3 minor
 +0% 10349/com.aliucord: 0% user + 0% kernel
 +0% 10404/logcat: 0% user + 0% kernel
 +0% 10529/magiskd: 0% user + 0% kernel
 +0% 10530/24: 0% user + 0% kernel
 +0% 10548/magiskd: 0% user + 0% kernel
 +0% 10550/24: 0% user + 0% kernel
78% TOTAL: 54% user + 19% kernel + 0.7% iowait + 1.9% irq + 1.5% softirq
CPU usage from 70ms to 565ms later (2023-12-01 20:32:43.603 to 2023-12-01 20:32:44.098):
  225% 7127/com.machiav3lli.backup: 209% user + 15% kernel / faults: 2797 minor
    33% 8196/DefaultDispatch: 30% user + 3% kernel
    30% 7238/DefaultDispatch: 30% user + 0% kernel
    24% 7206/WM.task-4: 21% user + 3% kernel
    24% 7240/DefaultDispatch: 21% user + 3% kernel
    24% 7241/DefaultDispatch: 21% user + 3% kernel
    24% 8198/DefaultDispatch: 21% user + 3% kernel
    21% 7127/hiav3lli.backup: 18% user + 3% kernel
    18% 7236/DefaultDispatch: 15% user + 3% kernel
    18% 8197/DefaultDispatch: 18% user + 0% kernel
    12% 7141/HeapTaskDaemon: 9.2% user + 3% kernel
    3% 7232/DefaultDispatch: 3% user + 0% kernel
  74% 2062/system_server: 33% user + 40% kernel / faults: 910 minor 1 major
    48% 10082/AnrConsumer: 14% user + 33% kernel
    9.6% 5002/binder:2062_15: 7.2% user + 2.4% kernel
    7.2% 3046/binder:2062_9: 4.8% user + 2.4% kernel
    2.4% 2062/system_server: 2.4% user + 0% kernel
    2.4% 2130/android.bg: 0% user + 2.4% kernel
    2.4% 2203/SensorService: 2.4% user + 0% kernel
    2.4% 2267/ranker: 0% user + 2.4% kernel
  98% 10085/24: 82% user + 15% kernel / faults: 12063 minor
    94% 10085/main: 82% user + 11% kernel
   +0% 10091/Jit thread pool: 0% user + 0% kernel
   +0% 10092/Runtime worker : 0% user + 0% kernel
   +0% 10093/Runtime worker : 0% user + 0% kernel
   +0% 10094/Runtime worker : 0% user + 0% kernel
   +0% 10095/Runtime worker : 0% user + 0% kernel
   +0% 10096/Signal Catcher: 0% user + 0% kernel
   +0% 10097/perfetto_hprof_: 0% user + 0% kernel
   +0% 10098/HeapTaskDaemon: 0% user + 0% kernel
   +0% 10099/ReferenceQueueD: 0% user + 0% kernel
   +0% 10100/FinalizerDaemon: 0% user + 0% kernel
   +0% 10101/FinalizerWatchd: 0% user + 0% kernel
  55% 3716/com.android.providers.media.module: 32% user + 22% kernel / faults: 1057 minor
    17% 3786/binder:3716_2: 15% user + 2.5% kernel
    7.5% 3903/ackgroundThread: 2.5% user + 5% kernel
    5% 9959/Thread-128: 2.5% user + 2.5% kernel
    5% 10057/Thread-138: 2.5% user + 2.5% kernel
    5% 10058/Thread-139: 2.5% user + 2.5% kernel
    2.5% 3909/fg: 2.5% user + 0% kernel
    2.5% 9926/Thread-133: 0% user + 2.5% kernel
    2.5% 9961/Thread-131: 0% user + 2.5% kernel
    2.5% 10055/Thread-137: 0% user + 2.5% kernel
    2.5% 10059/Thread-140: 2.5% user + 0% kernel
  35% 5016/com.android.systemui: 35% user + 0% kernel / faults: 217 minor
    29% 5016/ndroid.systemui: 29% user + 0% kernel
    2.7% 5355/RenderThread: 2.7% user + 0% kernel
  35% 8134/eu.kanade.tachiyomi.sy: 32% user + 3.2% kernel / faults: 317 minor
    26% 8134/de.tachiyomi.sy: 26% user + 0% kernel
    6.5% 8166/HeapTaskDaemon: 6.5% user + 0% kernel
    3.2% 8168/FinalizerDaemon: 3.2% user + 0% kernel
  12% 144/kswapd0: 0% user + 12% kernel
  13% 4621/com.android.externalstorage: 10% user + 2.6% kernel / faults: 28 minor
    8% 4721/binder:4621_1: 5.3% user + 2.6% kernel
    2.6% 7253/binder:4621_9: 2.6% user + 0% kernel
  6.9% 1294/surfaceflinger: 2.3% user + 4.6% kernel
    2.3% 1318/binder:1294_1: 0% user + 2.3% kernel
    2.3% 1340/app: 0% user + 2.3% kernel
    2.3% 1572/binder:1294_3: 0% user + 2.3% kernel
  7.7% 3777/com.tombayley.volumepanel: 5.1% user + 2.5% kernel / faults: 14 minor
    7.7% 3777/ley.volumepanel: 5.1% user + 2.5% kernel
  7.9% 3865/de.nulide.findmydevice: 2.6% user + 5.2% kernel / faults: 341 minor
    5.2% 3865/de.findmydevice: 2.6% user + 2.6% kernel
    2.6% 4183/Jit thread pool: 0% user + 2.6% kernel
  4.1% 327/kworker/u16:14: 0% user + 4.1% kernel
  4.2% 539/logd: 2.1% user + 2.1% kernel
  2% 9/rcu_preempt: 0% user + 2% kernel
  2% 46/rcuop/4: 0% user + 2% kernel
  2% 62/rcuop/6: 0% user + 2% kernel
  2% 253/kworker/u16:4: 0% user + 2% kernel
  2% 262/crtc_commit:96: 0% user + 2% kernel
  2.2% 783/lspd: 0% user + 2.2% kernel
  2.3% 1830/kworker/4:2: 0% user + 2.3% kernel
  2.5% 3490/kworker/u16:17: 0% user + 2.5% kernel
  2.5% 3666/shizuku_server: 2.5% user + 0% kernel / faults: 1 minor
  2.6% 3854/io.github.jd1378.otphelper: 2.6% user + 0% kernel / faults: 7 minor
  2.9% 6617/im.molly.app: 2.9% user + 0% kernel / faults: 3 minor
    2.9% 6617/im.molly.app: 2.9% user + 0% kernel
  3.2% 8089/toybox: 0% user + 3.2% kernel
  3.2% 8218/toybox: 0% user + 3.2% kernel
  3.8% 9660/com.f0x1d.logfox: 3.8% user + 0% kernel / faults: 59 minor
  3.9% 9708/logcat: 0% user + 3.9% kernel
  3.9% 10064/24: 0% user + 3.9% kernel / faults: 63 minor
    3.9% 10064/main: 0% user + 3.9% kernel
83% TOTAL: 61% user + 18% kernel + 1% iowait + 1.5% irq + 1.2% softirq
Completed ANR of com.angolix.android.wallpaper.slideshow in 19980ms, latency 1ms

**Comment by amk316** [comment]
after updating 8.3.5 i have the same problem

**Comment by Turhvjbufv** [comment]
Just make it so that the backup is in your sleeping time so it won't matter

**Comment by hg42** [comment]
do ypu use backupSuspendApps?

This usually leads to such problems.
E.g. suspending a keyboard app, leaves you with the default keyboard etc.

backupPauseApps might also create Problems, if apps cannot handle the stop/cont signals (e.g. some crash)

**Comment by hg42** [comment]
both options are thought to improve consistency, but they don't help much, in times when the (Google or alternate) framework does much of the background work for apps. NB cannot stop the framework, so there are still writes to the app data.

**Comment by hg42** [comment]
> > backupPauseApps

it's an option in developer settings
