### ISSUE TITLE
[Bug] Failed to restore all data

### ISSUE THREAD

**Issue by Jacob1Tm** [NeoApplications/Neo-Backup#819]
**Description**
All 104 apps i tried to restore failed to restore data

**Steps To Reproduce**

1. Start Restoring Data
2. Wait ~30s
3. All apps fails

**Expected behavior**
Restore Succeed

**Screenshots**
![Screenshot_20231211-221430_Neo Backup_1](https://github.com/NeoApplications/Neo-Backup/assets/84023677/018df04b-4826-4662-9214-09ddf5bb6bfb)

**System Information(please complete the following information):**

- Device: Redmi Note 12 4g NFC (topaz)
- Android Version: 13
- ROM: crDroid 9.9
- App's Version: 8.3.4

**Additional Notes**

Backup was made on the same device just 1 or 2 hours ago.

**Comment by machiav3lli** [comment]
So you had them encrypted, right? Could you please recheck your password

**Comment by Jacob1Tm** [comment]
> So you had them encrypted, right? Could you please recheck your password

nope i didn't use encryption

**Comment by hg42** [comment]
we got no answer...

additional, there were fixes in this area, NB is now autodetecting the format by looking for combinations of the extensions.
Also the error messages were improved in case of encryption failing.
Feel free to reopen this if it still happens.
