### ISSUE TITLE
[Bug] Let's Go button is off the screen

### ISSUE THREAD

**Issue by a1291762** [NeoApplications/Neo-Backup#829]
**Description**
I cannot get past the first screen as the Let's Go button is off the screen (below the navigation bar). I use old school button navigation rather than gestures.

**Steps To Reproduce**

1. use button navigation rather than gesture navigation 
2. launch Neo Backup for the first time
3. let's go button is below the navigation bar

**Expected behavior**
UI should not go underneath the navigation bar, or a scroll bar should allow the UI to be reached

**Screenshots**
Attached

**System Information(please complete the following information):**

- Device: pixel 8
- Android Version: 14
- ROM: (AOSP, MIUI, OOS...)  Stock 
- App's Version: 8.3.4 (fdroid)

-----------------------------

**Additional Notes**

* If you're on the latest Test version(from the TG-Channel or Matrix-Room) please report there directly, not here.

* If you're on the latest github version:
  
  * Please read the [FAQ](https://github.com/NeoApplications/Neo-Backup/blob/master/FAQ.md) first.
  * Please read all the open Issues. If one does match yours, leave a comment there if there's some extra information you can provide.

* If you're not on the latest github version. Update, then make sure that the bug is still there. If it's go further with reporting.

Thanks for reporting.

**Comment by a1291762** [comment]
![Uploading Screenshot_20240115-093003.png…]()

**Comment by hg42** [comment]
this should be solved, open a new issue, if it's still happening for you
