### ISSUE TITLE
[Bug] special backup does not work

### ISSUE THREAD

**Issue by HerroBert** [NeoApplications/Neo-Backup#831]
**Description**
special backup does not work and shows error for each type (wifi, sms, calllog and accounts):
"special backup only backups data, but data was not selected for backup"

**Steps To Reproduce**

1. enable special backup
2. select wifi, sms, calllog and accounts for backup
3. start predefined backup job
4. error message

**Expected behavior**
Backup special data

**System Information(please complete the following information):**

- Device: Samsung s9
- Android Version: 13
- ROM: LineageOS 20
- App's Version: 8.3.5

**Comment by HerroBert** [comment]
got it, had to set some things for my scheduled backup...

**Comment by Techwolf** [comment]
What was the "[things](https://xkcd.com/979/)"?
