### ISSUE TITLE
[Feature Request] Improve error message "Input is not in the .gz format"/ Allow restore of encrypted backup when backup encryption is disabled

### ISSUE THREAD

**Issue by JustMyGithub** [NeoApplications/Neo-Backup#835]
**Is your feature request related to a problem? Please describe it.**
Improve error message: "Input is not in the .gz format". In my tests, the good error messages would have been "password is wrong" or "backup is encrypted but settings are set to not encrypt"
when encryption is disabled in Neo [even if correct password is set])

**Describe the primary solution**
1. The encryption toggle should only be applied to backups, not to restores. Even if the password is correct the restore fails when encryption is disabled in the settings. However: If encryption is enabled and the backup is unencrypted, restore works fine (which is good). 
2. If the password is wrong, give the proper error message instead of "Input is not in the .gz format"

**System Information(please complete the following information):**

- Device: Pixel 7a
- Android Version: 14
- ROM: (AOSP, MIUI, OOS...)  Stock + Magisk
- App's Version: 8.3.5

**Comment by TheNeutrinoRaged** [comment]
I'd forgotten I enabled encryption and couldn't figure out what this error message referred to until I found this issue.

Maybe a reminder would be good when you backup or restore that encryption is enabled? (if that's possible)

**Comment by hg42** [comment]
I think the error message should be better now (maybe in the next release, not sure if it's already part of 8.3.8)
