### ISSUE TITLE
[Bug] Crash using backup via startpage (first tab) but not via backup tab on one device (Pixel 5)

### ISSUE THREAD

**Issue by JustMyGithub** [NeoApplications/Neo-Backup#837]
**Description**
If I use 
startpage tab -> click on app -> backup app -> (select components) -> OK
the app crashes - even if I select APK only. Backup works fine if the backup tab is used.
This does only affect one of my devices.

**System Information(please complete the following information):**

- Device: Pixel 5
- Android Version: 13
- ROM: (AOSP, MIUI, OOS...)  Stock + Magisk
- App's Version: 8.3.5

-----------------------------

**Comment by machiav3lli** [comment]
8.3.6 is already released fixing this

**Comment by antivirtel** [comment]
I don't see that latest version on F-droid, is it delayed or so? Thanks @machiav3lli

**Comment by machiav3lli** [comment]
Actually both got released on the same day (check GH), but Fdroid seems to have delayed the 8.3.6 build…
