### ISSUE TITLE
[Feature Request] Exclude `Cache` from backup

### ISSUE THREAD

**Issue by thomas-mc-work** [NeoApplications/Neo-Backup#838]
**Is your feature request related to a problem? Please describe it.**

The backup of the app data also include a `cache` folder. This is ephemeral data which can grow a lot depending on the application. This leads to blown up backups containing data that isn't really required.

**Describe the primary solution**

A solution could be to exclude this folder per default and provide an option to include it.

**Describe alternative solutions, if any**

Like before, just as opt-in instead of opt-out.

**Screenshots**

![backup data cache](https://github.com/NeoApplications/Neo-Backup/assets/6542498/fb72c774-c0f6-450a-b2c3-0fad79dcbd76)

**System Information (please complete the following information):**

- Device: Sony XA2
- Android Version: `11`
- ROM: LineageOS official
- App Version: `8.3.4`

Thanks!

**Comment by machiav3lli** [comment]
There's already an option under settings → service
