### ISSUE TITLE
Restoring and backup app workspace 

### ISSUE THREAD

**Issue by xunil89** [NeoApplications/Neo-Backup#845]
I wonder if it would be possible to introduce the possibility of backing up and restoring apps created in the workspace managed by apps such as insular and shelter.

**Comment by MichaelZ4714** [comment]
In the FAQ it is stated that it is not supported. There is a workaround if you install Neo Backup in the work profile. You have to ensure that NB can get root access, that depends on your root solution. But then there are issues, e.g. 
[https://github.com/NeoApplications/Neo-Backup/issues/795](https://github.com/NeoApplications/Neo-Backup/issues/795)
[https://github.com/NeoApplications/Neo-Backup/issues/772](https://github.com/NeoApplications/Neo-Backup/issues/772)
[https://github.com/NeoApplications/Neo-Backup/issues/583](https://github.com/NeoApplications/Neo-Backup/issues/583)
The good news: quite a few people ask for it. so the devs consider to fully support it in a future release. But it's unknown when it will be available.

**Comment by machiav3lli** [comment]
Further discussion at #795
