### ISSUE TITLE
[Feature Request] Feature Enhancements

### ISSUE THREAD

**Issue by RaXorX** [NeoApplications/Neo-Backup#847]
- Button to Clear App Data (we already have buttons to clear cache, kill the app and disable the app but not to clear app data)
- Button to open App Settings (to open the select app's settings in the Settings app directly)
- Create App specific profiles. (Ability to select what data to backup when we click on the Backup button per app).
- Tags filter in the Schedules. 
- Option to make the Schedules follow app specific profiles if there are profiles for any app created.

**Comment by machiav3lli** [comment]
Please check issues for duplicates (specifically I'm aware that point 4 already has duplicates). Furthermore, point 2 is already implemented (the info button in the app sheet). 

Also it's better to close this issue and open a specific issue for each of the features. This would help other users or community memebers better navigate the issues and discover duplicates.
