### ISSUE TITLE
Restoring old pictures and media

### ISSUE THREAD

**Issue by Kruszz** [NeoApplications/Neo-Backup#852]
**Description**
Please excuse my ignorance, as I am not entirely sure if this is even a functionality of the application itself, but I am trying to recover my old media files(which were stored in the Downloads, Documents, Pictures etc directories). After restoring all the applications that could have been safely restored, I notice some media files missing.

**Steps To Reproduce**

1. Backup everything 
2. Recover everything 
3. Check the gallery app
4. Media files have not been recovered

**Expected behavior**
Old media files are recovered as well.

**System Information(please complete the following information):**

- Device: Oneplus 8 pro
- Android Version: 14
- ROM:  LOS
- App's Version: 8.3.6

-----------------------------

**Comment by machiav3lli** [comment]
NB isn't meant for files, only apps and their data. Images, videos and such are usually saved in the respective folders. NextCloud as a cloud instance with sync or SyncThing with simple setup are two of the usual solutions.
