### ISSUE TITLE
[Feature Request] Perform app backup when a new version is installed/updated

### ISSUE THREAD

**Issue by whitedavidp** [NeoApplications/Neo-Backup#853]
**Is your feature request related to a problem? Please describe it.**
There is not a problem. But this is a suggestion...

**Describe the primary solution**
Perform app backup automatically when a new version is installed/updated...

**Describe alternative solutions, if any**
Already, many Android apps detect when an app is installed/updated. There is a broadcast that can be captured. Since the app package and the update vs install status is known via the broadcast, the app could be automatically backed up - at that time.

I recognize there is a batch mode "new/updated app" mechanism. But works depending on if this action is scheduled. And even if it is, there may be conditions whereby this does not actually get done. So doing so at the time of the install/update can be valuable.

**Screenshots**
N/A

**System Information (please complete the following information):**

- Device: Lg V40
- Android Version: 9
- ROM: (AOSP, MIUI, OOS...)  standard firmware, rooted with Magisk
- App Version: 8.2.5

**Comment by machiav3lli** [comment]
Why are you still on 8.2.5 and not on 8.3.6?
It's already there. Just create a schedule with the filter updated apps (new and updated were separated since 8.3.x). Furthermore in future versions it'll be possible to schedule backups on hour basis

**Comment by whitedavidp** [comment]
Hi and thanks again. Neo is great!

> Why are you still on 8.2.5 and not on 8.3.6? 

1. I was not aware of it.
2. When I did download, installed the updated version, and tried to run it the app crashed within seconds ever single time I tried. I did it all again and it still does it. This necessitated restoring my TWRP backup from last night.

> It's already there. Just create a schedule with the filter updated apps (new and updated were separated since 8.3.x). Furthermore in future versions it'll be possible to schedule backups on hour basis

As I wrote "I recognize there is a batch mode "new/updated app" mechanism" and I do use it. But as I also wrote, "And even if it is, there may be conditions whereby this does not actually get done." If scheduling can be done more frequently (like every hour) I suppose that might help. But it is NOT the same thing I was suggesting.

Cheers

**Comment by machiav3lli** [comment]
> 2. When I did download, installed the updated version, and tried to run it the app crashed within seconds ever single time I tried. I did it all again and it still does it. This necessitated restoring my TWRP backup from last night.

Crash logs could have possibly helped, as I never planned for such jumps (I can imagine that these crashes are either caused by backup properties or databases). And what does a TWRP backup has to do with this?

> If scheduling can be done more frequently (like every hour) I suppose that might help. But it is NOT the same thing I was suggesting.

To be more clear, running a constant service to catch all apps updated and then run backup of updated apps would be a battery killer. Even hourly schedules are not expected to be battery-friendly, but still far more efficient.

**Comment by whitedavidp** [comment]
> > 2. When I did download, installed the updated version, and tried to run it the app crashed within seconds ever single time I tried. I did it all again and it still does it. This necessitated restoring my TWRP backup from last night.
> 
> Crash logs could have possibly helped, as I never planned for such jumps (I can imagine that these crashes are either caused by backup properties or databases). And what does a TWRP backup has to do with this?

Simply that restoring the TWRP full backup I make every night (in addition to using Neo) was the quickest and surest way for me to put Humpty-Dumpty back together again...

> 
> > If scheduling can be done more frequently (like every hour) I suppose that might help. But it is NOT the same thing I was suggesting.
> 
> To be more clear, running a constant service to catch all apps updated and then run backup of updated apps would be a battery killer. Even hourly schedules are not expected to be battery-friendly, but still far more efficient.

Point taken regarding potential battery use. All I can say is that I have written an app (called Hide Updates in Play Store - now removed by Google from Play Store because I would not update it - didn't need it) that does this (and very little else). And it is far from a battery killer or memory user. I have long monitored my phone with 3C tools and that app doesn't every show up on the list.

Cheers
