### ISSUE TITLE
[Bug] .properties is now generated as a blank file (empty)

### ISSUE THREAD

**Issue by itsmeodx** [NeoApplications/Neo-Backup#854]
The backup is malfunctioning, it backs up all the necessary data but the .properties file is blank therefore the backup is not visible to the app itself and it can't restore like it's not even there, this is HyperOS A14, is this issue is rom specific?
![Screenshot_2024-03-22-05-54-03-293_nextapp fx-edit](https://github.com/NeoApplications/Neo-Backup/assets/63597426/7a004bcd-d345-4132-819d-ab5d6bc474db)

**Comment by itsmeodx** [comment]
Bro is this project dead or what?

**Comment by MrEngineerMind** [comment]
Bro, did you bother to check the last edit dates before your post?

**Comment by itsmeodx** [comment]
> Bro, did you bother to check the last edit dates before your post?

I did but i said that cz almost all the issues here isn't answered!

**Comment by itsmeodx** [comment]
> Bro, did you bother to check the last edit dates before your post?

Sorry, im just upset!

**Comment by MrEngineerMind** [comment]
There are 155 issues open, but 356 have been closed, with some in the last few months.

The issues are addressed by importance and/or number of user's reporting the same issue. As with all apps, if you are the only one reporting an issue, the lower it will be on the todo list.

The more details you provide, the easier it will be for the devs to test it.

**Comment by itsmeodx** [comment]
> There are 155 issues open, but 356 have been closed, with some in the last few months.
> 
> The issues are addressed by importance and/or number of user's reporting the same issue. As with all apps, if you are the only one reporting an issue, the lower it will be on the todo list.
> 
> The more details you provide, the easier it will be for the devs to test it.

Idk I just really need it to work cz I'm stuck in this buggy ROM and I can't to another one cz I can't backup my data idk if I'm the only experiencing this bug cz i didn't find anyone else having this issue and Idk how to fix it either.
Anyway thanks!

**Comment by MrEngineerMind** [comment]
Understood. Sorry to heard that.

Maybe see if Swift backup will work with that buggy ROM so at least you can do a backup of important apps and switch to a different ROM that works with NEO Backup.

**Comment by hg42** [comment]
I guess that's a thing of the past, empty properties files while the archives are written sounds very weird...
I close this now, if anyone thinks it's a thing, just create an new issue

**Comment by itsmeodx** [comment]
Sorry i found the solution long time ago but i forgot this issues is still open.
The bug was because of a problem with a SAF file explorer i installed while not knowing that it has that SAF thing, and it was selected as the default rather than built-in one in the system, i uninstalled it and things went back normall, thats it!
