### ISSUE TITLE
[Feature Request] Add an option to use tags in schedules

### ISSUE THREAD

**Issue by tukusejssirs** [NeoApplications/Neo-Backup#863]
Related #54 

---

**Is your feature request related to a problem? Please describe it.**

ATM, I need to manually and staticly define a list of apps that should backed up in a schedule. I want to be able to dynamically define the apps to back up using tags.

A related issue is to back up only changed apps (based on what is to be backed up, e.g. APK, data, ext data), but that could be discussed in a separate issue (it was already discussed but rejected in #54, however, it makes sense if you want to back up 200+ apps every night).

**Describe the primary solution**

All I miss is the tag selection in schedule configuration.

**Describe alternative solutions, if any**

This feature can be already found in Titanium Backup and Swift Backup.

1. I want to manually assign tags too all apps installed on my phone, e.g. `bu::on_data_change`, `bu::on_apk_change`.
2. Then, I’d select some tags in schedule configuration which would select all apps with matching tags. Note that I don’t want to _statically_ select apps, but _dynamically_ (i.e. whenever I tag another app with a matching tag, it would be automatically selected during next schedule run).
3. In the schedule config, I’d select what should be backed up (APK, cata, external data, …).

**Screenshots**

n/a

**System Information (please complete the following information):**

- Device: any (tested with Samsung Galaxy Note 10 Plus and Samsung Galaxy S22 Ultra)
- Android Version: any (tested on Android 11 and 14)
- ROM: any (tested on Dr.Ketan)
- App Version: 8.3.6

**Comment by machiav3lli** [comment]
Duplicate #526
