### ISSUE TITLE
[Bug] 8.3.6 flagged as malicious by Google Play Protect

### ISSUE THREAD

**Issue by singingtelegram** [NeoApplications/Neo-Backup#867]
**Description**
Neo-Backup 8.3.6 is flagged as malicious by Google Play Protect.

**Steps To Reproduce**

1. Download Neo Backup 8.3.6 from GitHub releases (SHA256: 118ae83d5c5d63835b8c3188401aecda25584c159fa791aded54f2f0c3fa27dd) or F-Droid (SHA256: b4a287f7cd779f91c174dcbf00bdf640f0f5a938bd9cca1d51a8b2d70f189142)
2. Proceed to install as normal
3. Installation is blocked by Google Play Protect (This app may be harmful popup)

**Expected behavior**
The app installs normally.

**Screenshots**
See attached.
![blocked](https://github.com/NeoApplications/Neo-Backup/assets/5357230/9c4528c4-88cc-4c46-a6cb-e223c3fbb9d7)

**System Information(please complete the following information):**

- Android Version: 14
- ROM: AOSP + GMS
- App's Version: 8.3.6

-----------------------------

**Additional Notes**

* If you're on the latest Test version(from the TG-Channel or Matrix-Room) please report there directly, not here.

* If you're on the latest github version:
  
  * Please read the [FAQ](https://github.com/NeoApplications/Neo-Backup/blob/master/FAQ.md) first.
  * Please read all the open Issues. If one does match yours, leave a comment there if there's some extra information you can provide.

* If you're not on the latest github version. Update, then make sure that the bug is still there. If it's go further with reporting.

Thanks for reporting.

**Comment by singingtelegram** [comment]
I was able to install 8.3.5 from F-Droid.

**Comment by machiav3lli** [comment]
If I remember good, this was discussed by the community at the release day and seems to be a hash false hit, you should be able to install it fine by tapping "install anyway"
