### ISSUE TITLE
[Bug] Fingerprint backup fails on valid filenames

### ISSUE THREAD

**Issue by b02860de585071a2** [NeoApplications/Neo-Backup#875]
**Description**
Per [AOSP source](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/services/core/java/com/android/server/biometrics/sensors/fingerprint/FingerprintUtils.java#42), data for the fingerprint sensor may be stored in `[...]/settings_fingerprint.xml` (legacy location), or in a file generated per given sensor, ie `[...]/settings_fingerprint_<sensorId>.xml` (for my P8P, this happens to be `settings_fingerprint_0.xml`).

The fingerprint backup function only checks for (hardcoded) `settings_fingerprint.xml`:
https://github.com/NeoApplications/Neo-Backup/blob/672dd22879c674aada640a4618fffd2f070d64a4/app/src/main/java/com/machiav3lli/backup/dbs/entity/SpecialInfo.kt#L168-L179

This results in failure of the backup, because the expected file does not exist.

**Steps To Reproduce**

1. Rename `settings_fingerprint.xml` to `settings_fingerprint_<number>.xml` in a test environment
2. Select `$ Fingerprints` under special backups
3. Attempt to back up
4. Error thrown: "BackupAppAction$BackupFailedException: ls: /data/system/users/0/settings_fingerprint.xml: no such file or directory - null"

**Expected behavior**
All possible files should be considered when performing checks. Assuming file existence is being checked with some android shell function like:

```
if ls <file> 1>/dev/null 2>&1; then
    <some backup action>
else
    <return error>
fi
```

I believe just globbing `settings_fingerprint*.xml` would work? kt is not my wheelhouse.

**Screenshots**
N/A

**System Information(please complete the following information):**

- Device: Pixel 8 Pro
- Android Version: 14 (AP1A.240505.005)
- ROM: [Evolution XYZ](https://github.com/Evolution-XYZ/)
- App's Version: 8.3.6

**Comment by hg42** [comment]
I am in the process of implementing plugins...
First step is a simple file list, that can be overridden by users in `Android/data/NBs.package.name/files/plugin/`.
I will probably improve the capabilities of this.
The current implementation of that SpecialInfo mechanism is a bit difficult.
I think to remember that originally the files were optional and they are stored flat.

To restore the saved files, the flat filename must be found in the list and then the file is copied to the corresponding folder.
With wildcards this might usually work, but it may become undefined in a more general case (the star covering a longer string).
E.g. as extreme, if it's simply `path-to-folder/*` then every file matches that filename pattern.
I'm sure if I allow wildcards with this implementation at some point users will do such things.

Currently, I would think to store the files with a path relative to the variable part (e.g. $userDir), maybe even including those variables and replace the variables just like when collecting the files. Currently, I use something like <userData> as pattern, so the file would be stored as
`"<userData>/settings_fingerprint.xml"`
and on restore, the `<userData>` would be replaced by the corresponding value, e.g. `/data/user/0`.
However, this does not directly fit to the way archives are unpacked (a single archive extracted by tar).
But -- wait -- maybe that doesn't matter, I think it is unpacked to a temprary directory and then copied to the system, so we can intercept at that stage and process the file name when copying single files.

I will check that later in the plugin implementation process.

With the simple "plugin" implementation (file lists),
there could be two plugins, one with 0 and one without (and 1, 2, ...) maybe called
`fingerprint`, `fingerprint_sensor_0`, `fingerprint_sensor_1`, ...

**Comment by hg42** [comment]
btw. I just had a discussion about that `settings_fingerprint_0.xml` on Telegram. What a coincidence.

**Comment by hg42** [comment]
the current pumpkin apks (see telegram) and I think also release 8.3.8 have a first incarnation of such plugins and a possibility to copy and edit them (see DevTools/plugins, see FAQ.md).

**Comment by b02860de585071a2** [comment]
> the current pumpkin apks (see telegram) and I think also release 8.3.8 have a first incarnation of such plugins and a possibility to copy and edit them (see DevTools/plugins, see FAQ.md).

Amazing, I'll check it out whenever I have free time (which could be a while) :)
