### ISSUE TITLE
[Feature Request] Backup to connected PC.

### ISSUE THREAD

**Issue by yum13241** [NeoApplications/Neo-Backup#879]
**Is your feature request related to a problem? Please describe it.**
If you plug in a USB flash drive, you can't charge your device. This could lead to a corrupted back up.

**Describe the primary solution**
The ability to connect my device to my PC and have it put the backed up files there.

**Describe alternative solutions, if any**
Plug in a flash drive and pray it doesn't use all your battery.

**System Information**
- Device: gta4xlwifi
- Android Version: 13
- ROM: LineageOS
- App Version: 8.3.6

**Comment by machiav3lli** [comment]
It's not fully clear what you want from your description, but if it's what the title says, you're on the wrong project. For such direct backup to happen Android should have access to the storage of the "connected PC", which is not there. I would suggest you read the FAQ, mainly: https://github.com/NeoApplications/Neo-Backup/blob/main/FAQ.md#does-nb-support-remote-backup-locations

**Comment by hg42** [comment]
I'd add that the PC uses the device storage not vice versa. It's about who controls the other side of the cable. A.k.a usb host vs usb device. The Android device is the usb device, so it cannot use the storage of the PC.
As @machiav3lli pointed out, it is theoretically possible to offer PC storage to the Android device via remote storage methods. Though this is usually working via network not via the usb cable.
It is theoretically possible to do something like this over USB, but I don't know a solution.
