### ISSUE TITLE
[Bug] Neo-Backup blocked by Google Play Protect

### ISSUE THREAD

**Issue by DottoreG** [NeoApplications/Neo-Backup#888]
**Description**
I installed Neo-Backup via the FDroid app store. But the newest update (version 8.3.7) is blocked by Google. Older versions could be installed just fine.

**Steps To Reproduce**

1. Try to install Neo-Backup version 8.3.7
2. Google complains about a possibly dangerous application. (The complaint can be ignored. But I'm feeling uncomfortable.)

**Expected behavior**
I would like to be able to install Neo-Backup without complaint. At least I would like to get aided with some information that I can ignore the complaint. Some background information about the situation would be very good.

**Screenshots**
![Screenshot_2024-08-04-11-16-46-76_b5a5c5cb02ca09c784c5d88160e2ec24](https://github.com/user-attachments/assets/cbe3123c-e8c6-4893-817a-4f7e3f375dfb)

**System Information(please complete the following information):**

- Device:  OnePlus 9 Pro
- Android Version: 14
- ROM: OxygenOS  
- App's Version: 8.3.7

**Comment by machiav3lli** [comment]
Users reported such already in the last two years, seems Google uses and tests different checks giving such results at some points. This is possibly because my account is not registered as developer at Play's platform. Would suggest to just ignore.

**Comment by DottoreG** [comment]
I didn't find anybody reporting this issue. So I opened the case. Perhaps some mention in the FAQ is helpful?

04.08.2024 14:51:30 machiav3lli ***@***.***>:
