### ISSUE TITLE
[Feature Request] Show `versionCode` beside `versionName`

### ISSUE THREAD

**Issue by pingu8007** [NeoApplications/Neo-Backup#896]
**Is your feature request related to a problem? Please describe it.**
Show backup's corresponding version code on the UI, either by default or can be enabled in settings.

**Describe the primary solution**
Play Store manage app releasing with version code, and it's required to download specific version from Aurora Store.
If a restoration is failed due to broken Apk, user can find and install from other source with version code and restore data later. 

(TiBu doesn't support splited apk so it failed to restore such backup. But it can restore data without issue in most cases if user has correct version installed.)

Without version code, user need more time to find correct version from other mirror site.

**Comment by hg42** [comment]
ok, I just added it as "versionName #versionCode"

I also made the versionName smaller to have more room for notes
